### ISSUE TITLE
Unable to Profile with Latest NKI Build

### ISSUE THREAD

**Issue by nandeeka** [aws-neuron/aws-neuron-sdk#1007]
I installed the latest version of Neuron using the .deb and .whl files @aws-serina-tan sent me. This version cannot generate the NTFF profile files. Whether I use `nki.benchmark` or `neuron-profile capture`, I am seeing the same error. Something like:
```
ERRO[0000] Failed to load profile session                NTFF=/home/ubuntu/nki-kernels/out/profile_exec_2.ntff error="NTFF version 4 is not supported in this version of the tool (supported: 1 - 3). Please upgrade aws-neuronx-tools."
neuron-profile exited with an error.neuron-profile 2.19.0.0%kaena-tools/2.19@c48a122 built on 2024-08-02T17:21:14Z

NTFF version 4 is not supported in this version of the tool (supported: 1 - 3). Please upgrade aws-neuronx-tools.
```
Upgrading `aws-neuronx-tools` only upgrades me to `2.19.0.0`. Any help would be appreciated!

**Comment by JonathanHenson** [comment]
Is it worth share=ing the fix here for other folks?

**Comment by nandeeka** [comment]
No, the problem was that Serina had not shared the latest version of the tools. Presumably when this version becomes publicly available, all dependencies will match, so Serina told me to close it. Thanks!
