### ISSUE TITLE
Strange-Looking Profiling Output

### ISSUE THREAD

**Issue by nandeeka** [aws-neuron/aws-neuron-sdk#1033]
I am trying to profile a NKI kernel and I am seeing very strange-looking outputs. Rather than the edges of the instructions being lines, they are strange shapes with dots.

<img width="1920" alt="Screenshot 2024-11-12 at 11 47 07 AM" src="https://github.com/user-attachments/assets/ee70a3f4-db70-4861-a28b-d2e72d0178aa">

I am using the latest DLAMI (launched today) on a `trn1.2xlarge` instance. Things I have tried to vary, but I see the same result:
- Different NKI kernels
- `nki.benchmark` to generate the `ntff` file
- `nki.baremetal` to generate the `neff` file and then `neuron-profile capture` to generate the `ntff` file

These artifacts make the profile quite difficult to read, so any help debugging would be appreciated.

**Comment by danielsnider-aws** [comment]
Hi, 

Thank you for opening an issue about this. We would be happy to look into it. Can you please provide the NEFF and NTFF files that you used when creating this profile screenshot? You can try attaching the files on this issue.

Thank you,
Dan

**Comment by nandeeka** [comment]
There are zipped and attached below. Thanks!

[out.zip](https://github.com/user-attachments/files/17722409/out.zip)

**Comment by danielsnider-aws** [comment]
Thanks! I opened your profile and the issue doesn't happen on my system.

Can you tell me:
- What happens when you try the latest Chrome browser?
- Can you tell me what version of the Profiler you're using? You can find the version in the area I highlighted in yellow below

![image](https://github.com/user-attachments/assets/4f2f3ba2-4692-4815-9ba3-05d30de1213b)

**Comment by nandeeka** [comment]
Hi Dan,

Thanks for your help debugging. It looks like the issue is that I have switched to using Firefox and this is a Firefox issue. I opened the profile on Chrome and it looks fine.

My software version is:
```
Software Version:
Neuron Profile: 2.19.0.0%kaena-tools/2.19@c48a122
Neuron Runtime: 2.22.14 (6e27b)
Instance Type: trn1.2xlarge
```

Thanks!

**Comment by james-aws** [comment]
we only officially support chrome. Updating the documentation to reflect this. For any users encountering such artifacts please try switching to chrome

**Comment by ayinas-aws** [comment]
@nandeeka the out.zip profile is not matching the profile in the screenshot provided above. The profile in out.zip is rendering correctly in firefox(attached screenshot)

<img width="1611" alt="Firefox with files provided in github issue" src="https://github.com/user-attachments/assets/e321bcfe-a29d-4413-a26e-8d87d0cd2e1c">

Can you provide the profile you are using in the screenshot and also please provide the version of firefox browser for us to investigate more. Thanks

**Comment by nandeeka** [comment]
How do I provide the profile to you? (i.e., what file are you looking for?) I am using Firefox 132.0.1 (aarch64). Thanks!
