### ISSUE TITLE
How to access neuron bare metal compiler - Beginner Setup Question

### ISSUE THREAD

**Issue by preejackie** [aws-neuron/aws-neuron-sdk#1037]
Hi,
I recently got access to trn1.2xlarge AWS instance (Deep Learning AMI Neuron 2.20.0 (Ubuntu 22.04). However, I'm not sure how to compile NKI kernels directly to bare-metal executable. Plus, I couldn't able to find the any documentation which describes how to install neuronx-cc compiler in the trn1.2xlarge instance. I was expecting the compiler is installed by default in /opt/aws/neuron/bin but apparently I can't able to find an executable in that path.
I'm new to this setup haven't worked with neuron devices before, any help will be greatly appreciated.

 I followed the documentation to check whether the import works or not by running this command in the shell : python3 -c 'neuronxcc.nki' but the import failed. 

Please let me know if you need more information. I'm happy to assist you!
PS: Right now, I'm not looking to use python based backends to use neuron device, I'm mostly interested in writing bare metal NKI kernels and executing them on neuron core.

**Comment by fayyadd** [comment]
Thanks for reaching out. You may want to use a pre-configured deep learning AMI (DLAMI) which comes pre-installed with everything you need to compile and run training and inference. See [this page](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/neuron-setup/multiframework/multi-framework-ubuntu22-neuron-dlami.html) on using DLAMIs with Trainium.

Or to install the required packages directly follow the [setup guide](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/index.html) which will walk you through the steps to install the required packages including the compiler.

For examples specific to NKI kernels, you might find the [NKI tutorials](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/nki/tutorials.html#nki-tutorials) helpful.

**Comment by preejackie** [comment]
@fayyadd Thanks a lot for your help, right now I'm using a pre-installed environment to write and compile NKI programs. However, I see that If I run the `nki` .py programs in python, it creates a .neff file in /tmp directory. I was wondering if it is possible to execute the .neff binaries directly on the neuron device.
What I trying to do is something similar to executing CUDA programs, where you can compile a CUDA program to a binary and execute it separately. I'm not sure whether we have a way to do something similar to this for neuron device.

**Comment by fayyadd** [comment]
Thanks for the question. You can execute the NEFF by using the runtime API here https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-runtime/nrt-api-guide.html#executing-the-neff . Let us know if you have further questions.

**Comment by preejackie** [comment]
@fayyadd Thank you, I will follow this documentation 👍
