### ISSUE TITLE
nki.isa.nc_matmul Transpose

### ISSUE THREAD

**Issue by nandeeka** [aws-neuron/aws-neuron-sdk#1043]
I was looking at the output of a call to the NKI code generator (with the name of the `.pb` stored in `$PB`:
```bash
neuronx-cc compile --framework XLA $PB --target trn1  --verbose info --pipeline compile SaveTemps --tensorizer-options='--print-nki --nki-dl'
```

And I noticed that the calls to `nki.isa.nc_matmul` have an `is_transpose` parameter, for example:
```python
v31[i12, i13, nl.arange(128)[:, None], nl.arange(128)[None, :]] = nisa.nc_matmul(v30[i12, nl.arange(128)[:, None], nl.arange(128)[None, :]+128*i13], v18[nl.arange(128)[:, None], nl.arange(128)[None, :]], is_stationary_onezero=False, is_moving_onezero=True, mask=None, is_transpose=True)
```
However, I don't see this parameter in the [documentation](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/nki/api/generated/nki.isa.nc_matmul.html).

I have a couple of questions:
1. Which matrix does this transpose affect (the stationary or moving matrix)?
2. What are the performance implications of using this parameter, over doing `nki.isa.nc_transpose`, copying the result back to the SBUF, and then `nki.isa.nc_matmul` without it?

**Comment by nandeeka** [comment]
Thank you!

**Comment by awsrjh** [comment]
Hi nandeeka - let us know if this helped or if you have more questions we can help with

**Comment by aws-donkrets** [comment]
[nandeeka](https://github.com/nandeeka) - we will also update our documentation in the next release.
