### ISSUE TITLE
JAX Neuron: Internal tensorizer error

### ISSUE THREAD

**Issue by IrishWhiskey** [aws-neuron/aws-neuron-sdk#1046]
Hello,

I'm trying to train a JAX model on a trn1 instance but I get the following error message:
```
root = neuronxcc/starfish/penguin/targets/sunda/passes/SundaSizeTiling.py
root = neuronxcc/starfish/penguin/targets/sunda/passes
root = neuronxcc/starfish/penguin/targets/sunda
root = neuronxcc/starfish/penguin/targets
root = neuronxcc/starfish/penguin
root = neuronxcc/starfish

2024-12-02T13:01:20Z [TEN404] Internal tensorizer error: SundaSizeTiling: - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.
```

I tried to set the `XLA_IR_DEBUG` and `XLA_HLO_DEBUB` env variables to `1` but I didn't get any extra logs.

Here are some details about the environment:
```
(tensorflow2_p310) sh-4.2$ neuronx-cc --version
NeuronX Compiler version 2.15.143.0+e39249ad

Python version 3.10.15
HWM version 2.15.0.143+e39249ad
NumPy version 1.25.2

Running on AMI ami-01132fa95ada76282
Running in region usw2-az1
```
The JAX version is `0.4.31`.

**Comment by awsyunhaz** [comment]
Hi @IrishWhiskey, thanks for reporting this issue. Could you run the script with the following flag to dump the HLOs: os.environ['NEURON_CC_FLAGS'] = "--dump=/path"

With the HLOs we will be able to better investigate and assist you with this issue.

**Comment by IrishWhiskey** [comment]
Hi @awsyunhaz, I actually figured the issue was caused by jax.random.normal. I still haven't managed to make my code run, as I keep running into other issues, though it seems like I'm making progress. I'll close this issue for now.

**Comment by devesr-amzn** [comment]
Hi @IrishWhiskey, this could be due to a known issue of the threefry RNG algorithm not working for the lowering of `jax.random.normal` in use. You can try to switch over to the `rbg` algorithm.

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/jax/setup/jax-neuronx-known-issues.html
