### ISSUE TITLE
[TEN404] Internal tensorizer error: NeuronInstComb:Can only handle single store 

### ISSUE THREAD

**Issue by simone-surdi** [aws-neuron/aws-neuron-sdk#1047]
[TEN404] Internal tensorizer error: NeuronInstComb:Can only handle single store - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.

**Comment by awsyunhaz** [comment]
HI @simone-surdi, thanks for reporting this issue. This error is thrown during model compilation. Would it be possible for you to share the environment (run `pip list | grep neuron`) and a code snippnet to reproduce the issue?

**Comment by simone-surdi** [comment]
Sure! I can provide everything.
Is there a way to provide it such that it is private?
It is part of a Stanford assignment
Simo

**Comment by simone-surdi** [comment]
@awsyunhaz

**Comment by awsyunhaz** [comment]
@simone-surdi If the model is sensitive you can reach out to us at aws-neuron-support@amazon.com

**Comment by simone-surdi** [comment]
@awsyunhaz just sent from ssurdi@stanford.edu

**Comment by simone-surdi** [comment]
Thanks so much 🙏
Looking forward to it. So to crack the assignment!
Simo

**Comment by simone-surdi** [comment]
Hey Joey,

Any news? Sorry to make pressure but my assignment has a deadline hahahah!

Simo

**Comment by awsyunhaz** [comment]
@simone-surdi, we encountered a different error with the provided artifacts. Thank you for your patience while our team is actively looking into this issue.

**Comment by simone-surdi** [comment]
🙏

**Comment by aws-zhehongb** [comment]
without looking at the kernel code you have, maybe you could try to write the kernel in "single assignment" form to workaround the issue? i.e. each tensor only have 1 assignment

**Comment by simone-surdi** [comment]
Hi, could you be more precise?
I have emailed the kernel code btw. You have it in the email I sent.
Simo

**Comment by aws-zhehongb** [comment]
sorry it turned out the aws-neuron-support@amazon.com blocked all attachment, is it possible to put the kernel and input shapes/dtypes on  github secret gist and share with me?

**Comment by simone-surdi** [comment]
For sure.
What email address should I use to share the private repo?
Simo

**Comment by aws-zhehongb** [comment]
could you share with this github account: @aws-zhehongb  ?

**Comment by awsyunhaz** [comment]
@aws-zhehongb got back to the requester. No more actions are needed. Closing this issue
