### ISSUE TITLE
Unclear error message: Expect NeuronReduceMacro!

### ISSUE THREAD

**Issue by Ericcsr** [aws-neuron/aws-neuron-sdk#1049]
When implementing maxpooling with tiling, in non simulation mode compiler generate error:
` [TEN404] Internal tensorizer error: TensorInitialization:Expect NeuronReduceMacro! - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.`
error will disappear when using simulation kernel, suspected source of error:
`result_ = nl.zeros((nl.par_dim(c_out_per_tile), n_vert_pools, out_pool_width, pool_size, pool_size), dtype=X_out.dtype, buffer=nl.sbuf)
                for i_0 in nl.affine_range(c_out_per_tile):
                    for i_1 in nl.affine_range(n_vert_pools):
                        for i_2 in nl.affine_range(out_pool_width):
                            for i_3 in nl.affine_range(pool_size):
                                for i_4 in nl.affine_range(pool_size):
                                    result_[i_0,i_1,i_2,i_3,i_4] += conv_result[i_0, (i_1 * pool_size + i_3) * out_width + i_2 * pool_size + i_4] / (pool_size * pool_size)
                out_tile = nl.max(result_, axis=[3, 4])
                out_tile += broadcasted_bias
                nl.store(X_out[b, n * c_out_per_tile:(n + 1) * c_out_per_tile, m * n_vert_pools:(m + 1) * n_vert_pools, :], value=out_tile)`
Is there any idea what may cause such error? Thanks!

**Comment by awsyunhaz** [comment]
Hi @Ericcsr, thanks for reporting this issue. I saw a few undefined variables in the script that you shared. Would it be possible to share the complete script for repor?

**Comment by aws-zhehongb** [comment]
could you try to do 
```
out_tile = nl.add(out_tile, broadcasted_bias)
```
to check if you could workaround the problem?

**Comment by AWSNB** [comment]
@Ericcsr did ^^ work for you ?

**Comment by Ericcsr** [comment]
Yes, it works for me!
```
out_tile = nl.add(out_tile, broadcasted_bias)
```

**Comment by AWSNB** [comment]
thank you and good luck with rest of the assignment

closing the issue for now

feel free to re-open it if it happens again
