### ISSUE TITLE
Internal tensorizer error

### ISSUE THREAD

**Issue by ggaw25** [aws-neuron/aws-neuron-sdk#1056]
Getting this error when running loops with nl.affine_range. The code runs correctly with nl.static_range instead.
[TEN404] Internal tensorizer error: NeuronInstComb:Can only handle single store

**Comment by AWSNB** [comment]
can you share privet repo and give permission to @aws-serina-tan @JonathanHenson @aws-qieqingy @AWSNB 
2

**Comment by aws-zhehongb** [comment]
are you doing `a += yyy` where `a` is a tensor on `nl.sbuf`?

**Comment by ggaw25** [comment]
Issue is resolved, appreciate the help
