### ISSUE TITLE
Stanford CS149 Assignment 4: nki.benchmark() Stalling

### ISSUE THREAD

**Issue by Jacario777** [aws-neuron/aws-neuron-sdk#1062]
Hello Neuron team,
I'm using the nki.benchmark() function to measure the performance of my convolution program. While my program passed all correctness tests (when --simulate is set), the program stalls when it enters nki.benchmark for performance evaluation. The program also stalls when running a large image (224 x 224) without --simulate. I added print statements to four places (before nki.benchmark, at the start of conv2d.py, at the end of conv2d.py before return, and right after nki.benchmark), and it seems that the last print statement never came out, suggesting that there is some issue with exiting conv2d.py. How should I change my code to fix this issue? 

My private repo: https://github.com/Jacario777/cs149_asst4.git

Example of stall (print statement highlighted in yellow):
![image](https://github.com/user-attachments/assets/6d5e6a7d-d69f-4fd9-918b-6048f73b76e4)

Another issue involves the three lines in test_harness.py. Unless I commented out, test_harness.py would get stuck on them. Is this issue related to nki.benchmark stalling? 
![image](https://github.com/user-attachments/assets/cc2e8a57-e2b1-49c3-9ce0-3afcbb6aee37)

**Comment by EmilyWebber** [comment]
Hi Jacario, we've seen that the test harness script can cover some helpful error messages from the compiler. You might want to try running the kernel in a dedicated script without the harness - hopefully you'll get a more helpful error code that way.

**Comment by aws-serina-tan** [comment]
Hi Jacario, I just pulled your repo and things seem to be running (with some perf test failure but didn't hang). I assume you have resolved your earlier issue?

Anyhow, when you said "stalled", did the test simply hang with no output? One possibility for a "hang" is nki.benchmark in the test harness runs the same program many times to calculate average latencies. So if the program itself is slow, it can take a very long time to finish. 
When nki.benchmark is taking a long time, one thing you can try is opening up neuron-top in another terminal window to see if there is any real activity on the NeuronCore: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/tools/neuron-sys-tools/neuron-top-user-guide.html. 

As for the lines around sys.stdout, I believe the intention there was to capture some console output from the nki.benchmark API (some of the output can be quite noisy). They shouldn't affect now nki.benchmark is run.

**Comment by Jacario777** [comment]
Hey Emily and Serina, thanks for the information. The stalling issue was resolved after I replaced sequential_range with affine_range for all my loops. 
All the best,
James
