### ISSUE TITLE
[torch-neuron] LSTM (aten::lstm) support on Inf1

### ISSUE THREAD

**Issue by AWSGH** [aws-neuron/aws-neuron-sdk#242]
work initiated from https://github.com/aws/aws-neuron-sdk/issues/207

**Comment by loretoparisi** [comment]
@AWSGH any news about LSTM integration?

**Comment by sapjunior** [comment]
Is there any progress on this integration? It almost one year from the open date..

**Comment by sapjunior** [comment]
Hi, Is there any progress on this integration? It already a year and a half since open date..

**Comment by aws-maens** [comment]
Released in Neuron 2.5.0
