### ISSUE TITLE
Will it be possible to compile custom Fast.ai trained PyTorch model on AWS Neuron Compiler?

### ISSUE THREAD

**Issue by sandeepmohanadasan** [aws-neuron/aws-neuron-sdk#340]
Will it be possible to compile a custom Fast.ai trained PyTorch model on AWS Neuron Compiler?
@jluntamazon Let me know if you can throw light on this.

**Comment by jluntamazon** [comment]
Thank you for providing the example code. For most models, the `torch_neuron.trace` call that you attempted should have worked. However, with the sample code you linked, we were able to reproduce the issue you see. We are working towards a fix on our end and will keep you updated on this issue.

**Comment by sandeepmohanadasan** [comment]
Thanks for the fix. I have updated Neuron 1.16.1.
But getting so many Compatability issues with other Libraries.

**Comment by shebbur-aws** [comment]
Hi Sandeep,

Can you please give us more details about the error you see? If you prefer,  you can send us the details at aws-neuron-support@amazon.com.  Also, we had another release yesterday. Might be worth checking with the 
[latest release](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#neuron-1-16-2-12-15-2021)

Thanks,
Shruthi.
