### ISSUE TITLE
SwinIR Neuron Compilation Failing for PyTorch

### ISSUE THREAD

**Issue by guptajayesh** [aws-neuron/aws-neuron-sdk#419]
I was trying to compile the SwinIR Implementation using Neuron SDK

Repo for Model: https://github.com/JingyunLiang/SwinIR

Command for Model in Repo: python main_test_swinir.py --task real_sr --scale 4 --large_model --model_path model_zoo/swinir/003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth --folder_lq testsets/RealSRSet+5images

However, I run into Several Problems

1) Lack of Support for ops aten::roll , aten::reflection_pad2d and aten::Index
2) However even post skipping these operation, It mentions 0 Subgraphs Successfully compiled and Keeps failing for each subgraph compilation

**Comment by awsilya** [comment]
Hi Jayesh,

A couple of things, on [1] aten::index and aten::roll are used across many layers, that means even if compiled successfully the network might not be performant.

Regarding [2] when you are saying "keeps failing" do you mean you get an error or does it just hangs/takes a long time? 

Thank you

**Comment by guptajayesh** [comment]
Hi, 
I understand aten::index and aten:roll is used across many layers However I do still expect some performance increase

By Failing, I mean After Pro Compilation Check, It keeps mentioning Failed Compilation falling back to command call
But post that for each subgraph it says error and fails and in the end mentions Neuron Failed, 0 Subgraphs Compiled

**Comment by awsilya** [comment]
Our team is looking at the failures.

Perf. increase - hard to tell.  when an operator is not supported it's partitioned out and runs in PT instead.  Each partition requires a data transfer between PT and Neuron.  Depending on the amount of data you might or might not see any performance increase.

**Comment by aws-taylor** [comment]
Hello @guptajayesh,

  We believe we have identified the issue and are working on a fix. We'll continue to update this ticket as it becomes available.

**Comment by mrnikwaws** [comment]
Hi @guptajayesh,

We are continuing to track fixes that relate to this issue through our release process.  We'll update this ticket as the fixes are released.

**Comment by aws-owinop** [comment]
Hi @guptajayesh,
Just to provide you with an update, we are still tracking the fixes that relate to this issue through our release process. We'll update this ticket as soon as the fixes are released.

**Comment by shebbur-aws** [comment]
Hi @guptajayesh, we have a fix which will be released in one of the upcoming releases.

**Comment by mrnikwaws** [comment]
Hi @guptajayesh,

The fix was released as part of the 2.9.0 release (https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html)!  This should resolve your issue.  If not open a new issue and we'll follow up.
