### ISSUE TITLE
[torch-neuron] Optimization - Reduce memory used by models

### ISSUE THREAD

**Issue by aws-maens** [aws-neuron/aws-neuron-sdk#428]
Frameworks: Optimizations to reduce memory used by models.

**Comment by jluntamazon** [comment]
Memory utilization should be reduced as of the 2.5.0 Neuron release: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/prev/rn.html#neuron-2-5-0-11-23-2022

Now `torch-neuron` will attempt to unload model data from host memory when possible. This is especially impactful when using a multi-processing serving framework such as `torchserve` or `gunicorn` where each worker holds a model in host memory. This will cause the most impactful memory reduction in models that are fully compiled to Neuron with no CPU partitioned weights (such as embeddings). (edited)
