### ISSUE TITLE
Compiling LayoutLMv3 keeps hanging with no logs

### ISSUE THREAD

**Issue by akrogager** [aws-neuron/aws-neuron-sdk#436]
I tried compiling the LayoutLMv3 model from Hugging Face but the compiler just keeps hanging and doesn't give any logs. I am running the compilation in an AWS SageMaker Studio notebook with machine type `ml.m5.xlarge`. I am able to run all the code in the blog post https://huggingface.co/blog/bert-inferentia-sagemaker but when I switch out the model with LayoutLMv3, it just hangs. Do you have any suggestions on what could be wrong here and how to debug?

Code to reproduce: 
```
import os
import tensorflow  # to workaround a protobuf version conflict issue
import torch
import torch.neuron
from transformers import LayoutLMv3ForTokenClassification
from transformers import AutoProcessor
from PIL import Image
import torch.nn as nn

processor = AutoProcessor.from_pretrained("microsoft/layoutlmv3-base", apply_ocr=False)
model = LayoutLMv3ForTokenClassification.from_pretrained(
    "microsoft/layoutlmv3-base", num_labels=2, torchscript=True
)

# dummy inputs
image = Image.new("RGB", (224, 224))
words = ['Hello', 'world!']
bboxes = [[10, 10, 50, 20], [55, 10, 80, 20]]

encoded_inputs = processor(
    image,
    words,
    boxes=bboxes,
    padding="max_length",
    truncation=True,
    max_length=SEQ_LENGTH,
    return_tensors="pt",
)
encoded_inputs['pixel_values'] = torch.cat([torch.unsqueeze(img, 0) for img in encoded_inputs['pixel_values']])

class WrapperModel(nn.Module):
    """Wrapper to pass the inputs as a tuple instead of keyword arguments."""
    def __init__(self):
        super().__init__()

    def forward(self, input_ids, bbox, attention_mask, pixel_values):
        return model(input_ids=input_ids, bbox=bbox, attention_mask=attention_mask, pixel_values=pixel_values)

wrapper_model = WrapperModel()

neuron_inputs = (
    encoded_inputs['input_ids'],
    encoded_inputs['bbox'],
    encoded_inputs['attention_mask'],
    encoded_inputs['pixel_values']
)

model_neuron = torch.neuron.trace(wrapper_model, neuron_inputs)
```

Dependencies:
- torch-neuron==1.9.1.* 
- neuron-cc[tensorflow]
- transformers==4.20.0

**Comment by awsrjh** [comment]
Hi akrogager,

There are 2 parts to this: First - the model state needs to be added to the WrapperModel class (see below). Secondly - the aten:amax operator is not yet implemented so there will be some partitioning of the model in Neuron around it - which may  reduce performance. We will examine this and follow up.

```
class WrapperModel(nn.Module):
    """Wrapper to pass the inputs as a tuple instead of keyword arguments."""
    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, input_ids, bbox, attention_mask, pixel_values):
        return self.model(input_ids=input_ids, bbox=bbox, attention_mask=attention_mask, pixel_values=pixel_values)

wrapper_model = WrapperModel(model)
wrapper_model.eval()

```

**Comment by akrogager** [comment]
Thanks for the answer awsrjh - this solved my problem. Also thanks for following up on the aten:amax support.

**Comment by aws-joshim** [comment]
@akrogager support for aten::amax will be added to an upcoming Neuron release. We will update the ticket once the operator is supported

**Comment by awsrjh** [comment]
HI

we released a fix for this 

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#neuron-2-5-0-11-23-2022
