### ISSUE TITLE
Keras-ocr neuron

### ISSUE THREAD

**Issue by fishuke** [aws-neuron/aws-neuron-sdk#454]
I want to use Keras-ocr with aws neuron is there any tips or docs about it. Keras-ocr is using an old version of Tensorflow I am not sure if its compatible.

**Comment by awsilya** [comment]
which TF version do you use?

**Comment by fishuke** [comment]
tensorflow = "^2.0.0"

**Comment by awsilya** [comment]
Unfortunately, we don't support TF 2.0.  We do support TF 2.1 and higher.

**Comment by fishuke** [comment]
Thanks, we will try to use keras-ocr with pytorch I hope it helps.

**Comment by aws-taylor** [comment]
Hello @fishuke ,

 Were you able to test  with pytorch? Any new issues?
 
 -Taylor

**Comment by fishuke** [comment]
We decided to continue with TensorFlow and it turned out Keras-OCR uses two models. We successfully compiled the first model to get boxes but the second model (which does the OCR) failed. Our computer vision team is dealing with the situation. 

You can reproduce the issue by compiling the models given here:
https://github.com/faustomorales/keras-ocr

**Comment by aws-owinop** [comment]
Hi @fishuke 

Was your CV team able to compile the second model? Any update.

- Paul.

**Comment by jeffhataws** [comment]
@fishuke, please reopen this ticket if you will need further assistance. Thanks!
