### ISSUE TITLE
Neuron everyday deployment failure ping check failed

### ISSUE THREAD

**Issue by DevBey** [aws-neuron/aws-neuron-sdk#457]
Hi we are trying to create around 8 inferentia endpoints only when our batch runs which is twice a day for two hours each, and delete the endpoints afterwards, now this should be easily technically feasible. but what's happening is we are getting a unnecessary ping health check errors like this with deployment failed.

`Failure reason The customer:primary container,hardware:neuron for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint.`

out of 8, sometime one or two are failing healthcheck, even though in the cloudwatch logs everything is fine as it should be the model is loaded correctly and workers, pytorch servers everything is started well.

Can you please help solve this issue quickly, this is a production imparining issue for us.

**Comment by aws-joshim** [comment]
@DevBey  Do you use Sagemaker hosting for your endpoint production deployment? If not, can you share details for your endpoint hosting setup? The details will be useful for us to help with timely resolution of this issue

**Comment by DevBey** [comment]
Hi @aws-joshim, 

yes we use the sagemaker python SDK for real-time deployment of these models. These models were deployed for last 1 year 24/7 and were working incredibly. 

But recently we have instead tried to move this into a batch schedule by creating automatically using lambda and creating these sagemaker endpoints only for the required two hours using lambda using the same existing endpoint config which we used for last whole year.

this problem is randomly happening with any of the 8 endpoints, sometime some sagemaker endpoint fails sometime some other, mind you none of them have any errors in the cloudwatch logs. they are just failing the healthcheck.

**Comment by DevBey** [comment]
Here is the screenshot of exact error message, I don't see this problem happening with GPU deployment of same models normal pytorch version.

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/85338857/182288003-83bdf789-6c75-4a82-b41b-0e4cd7a0d34e.png">

**Comment by kelleraa** [comment]
Hi @DevBey,
Can you post the AWS region in which this occurred and the approximate day/time?

**Comment by DevBey** [comment]
Hi @kelleraa, 

As I mentioned, we changed from 24/7 real time deployment to automatic deployment for only 2 hours at 9:30 UTC every day. This happens with us every time we deploy the batch, the region is us-east-2. We must manually delete and create endpoints multiple times for it to go into InService state. Even currently there is one model which was supposed to be deployed at 2:30 UTC currently in a failed state, CloudWatch logs don't show any error, and everything looks fine in logs.

**Comment by kelleraa** [comment]
Hi @DevBey,

Thank you for bringing this issue to our attention. We apologize for any inconvenience caused by these deployment failures. The issue you saw in us-east-2 should no longer be occurring. Did you have any deployment issues during the 09:30 UTC run on August 2nd or 3rd?

Thanks!

**Comment by DevBey** [comment]
Hi @kelleraa,

thanks for the prompt response and solution. Yes, it's working fine now.

**Comment by DevBey** [comment]
Hello @kelleraa, 

we  are again having the same issues, this time in us-east-1, the endpoints particularly on inf1.xlarge has been in creating state for last one hour right now, there are absolutely no logs at all.

the scenario is still the same, we have a batch running at 10 UTC everyday, at which point the problem is happening. everything else is still the same, regarding deployment etc remains the same as above.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/85338857/200849003-d416c7b5-1c3f-4792-a887-3bcd3f19a47b.png">
