### ISSUE TITLE
[torch-neuron] Solve NaN issue when using transformers>=4.20

### ISSUE THREAD

**Issue by aws-maens** [aws-neuron/aws-neuron-sdk#474]
Solve NaN issue when using transformers>=4.20 (https://github.com/aws/aws-neuron-sdk/issues/456)

**Comment by jluntamazon** [comment]
This should no longer cause problems on inf1 when using `torch-neuron` as of the 2.5.0 release: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/prev/rn.html#neuron-2-5-0-11-23-2022

This resolves the behavior seen in https://github.com/aws-neuron/aws-neuron-sdk/issues/456. The script in the ticket now produces the correct results.
