### ISSUE TITLE
Docker Image for compiling neuron models

### ISSUE THREAD

**Issue by aj2622** [aws-neuron/aws-neuron-sdk#484]
Hi can you please give clear instruction how to build a docker image that can be used to spin up a sagemaker processing job that I can use to set up a model compilation pipeline. I am sorry if this is already in the documentation (if so can you please point me to the right link)

**Comment by aws-donkrets** [comment]
Sagemaker offers a number of different pre-built containers. In addition, you can find the Inferentia/Neuron specific   instructions in the Container tab of the AWS Neuron documentation at
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-deploy/index.html

**Comment by aj2622** [comment]
https://github.com/aws/deep-learning-containers/blob/master/huggingface/pytorch/inference/docker/1.10/py3/sdk1.19.1/Dockerfile.neuron

was able to get this Dockerfile to work for compiling a model with minor edits to the ENTRYPOINT
