### ISSUE TITLE
[torch-neuronx] Dynamic Shapes support for training on Trn1

### ISSUE THREAD

**Issue by aws-rxgupta** [aws-neuron/aws-neuron-sdk#564]
[torch-neuronx] Dynamic Shapes support for training on Trn1

**Comment by sinking-point** [comment]
This would be useful for Inf2 as well, not just Trn1.

**Comment by aws-ennst** [comment]
This feature is on our roadmap and we will update when it is available.

**Comment by aws-ennst** [comment]
In the meantime, bucketing is a great tool to enable models with var seq len on top of Neuron. Please see our tutorial here: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/appnotes/torch-neuron/bucketing-app-note.html

**Comment by davidshtian** [comment]
Any updates on this feature? Thanks~

**Comment by abasu0713** [comment]
Just following up on this.. This would be an amazing nice to have.. For running TGI containers on bother Sagemaker backed by Inferentia, and EKS by managed Inferentia node-group

**Comment by mostafafarzaneh** [comment]
Hey @aws-rxgupta 
We have a Tensorflow model with dynamic input shapes. Will this feature also be available for Tensorflow as well?
