### ISSUE TITLE
Issue on page /general/quick-start/torch-neuron.html

### ISSUE THREAD

**Issue by eitansela** [aws-neuron/aws-neuron-sdk#579]
Hi, tried to run the [Get Started with PyTorch Neuron tutorial](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/quick-start/torch-neuron.html)

Got `ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device` when running the `pip install torch-neuronx==1.11.0.1.*` command.

Maybe worth adding to this tutorial a requirement to launch an instance with more storage than the 8 GB default one, in “Launch Trn1 instance” section?

**Comment by awsilya** [comment]
hi, the tutorial has been updated, thank you for pointing this out.

* When launching a Trn1, please adjust your primary EBS volume size to a minimum of 512GB.
