### ISSUE TITLE
Clarification on how to build and run a neuron container

### ISSUE THREAD

**Issue by ndenStanford** [aws-neuron/aws-neuron-sdk#581]
I would love to get some clarification on how to run a neuron container. 

Consider an excerpt from the [manual ](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/containers/tutorials/build-run-neuron-container.html#how-to-build-neuron-container)

"Multiple container applications running in the same host can share the **devices** but the **cores** cannot be shared. This is similar to running multiple applications in the host. In the kubernetes environment the **devices** cannot be shared by multiple containers in the pod"

What are **devices** and **cores** referred to in this context? I am attempted to match these definitions with the [description](https://aws.amazon.com/ec2/instance-types/inf1/) of inf machine. 

"Each AWS Inferentia chip has **four** first-generation **NeuronCores** and provides up to 128 tera operations per second (TOPS) of performance, and support for FP16, BF16, and INT8 data types. Based on the pricing table inf1.xlarge instance contains **4 vcpu**. "

What is the relationship between **vcpu** and **NeuronCores**? Are they related to **devices** and **cores** from the neuron tutorial above? For inf1.xlarge with kubernetes deployment, how many containers could exist?

Any clarification and comments are greatly approciated. Thank you!

**Comment by aws-maens** [comment]
Please see Neuron Architecture section: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/index.html
Inf1 Arch: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/neuron-hardware/inf1-arch.html#aws-inf1-arch
NeuronCores: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/neuron-hardware/neuroncores-arch.html#neuroncores-arch
Neuron Glossary: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/glossary.html#neuron-hw-glossary

**Comment by awsilya** [comment]
just a few extra pointers to get you started.  BTW, none of this has any connection to vcpus.  For the purpose of your question a particular instance size gives you a number of neuron devices/cores.  Unless a significant portion of your inference graph has to run on a CPU, i.e. cannot be offloaded to Neuron, the number of vcpus don't matter much.

Each Neuron device, that you can see by running lspci contains 4 cores.  A process or a process running inside a container gets an exclusive access to one or more cores.  Depending on your compute needs you give a process one or more cores.  There is an example of a **very** low latency BERT that was compiled for 16 cores.  In that case a process/container would need  at least 16 cores to run it.

A shorter answer to your question - you can run at most 4 containers on XL, one core per container.

**Comment by awsilya** [comment]
Hi, was it helpful?  I'm going to close the issue, feel free to reopen if you need more help
