### ISSUE TITLE
Issue on page /general/quick-start/torch-neuron.html

### ISSUE THREAD

**Issue by kevinshen1101** [aws-neuron/aws-neuron-sdk#583]
I think `awscli` was meant here instead of `awcli` in the pip installs?

**Comment by awsilya** [comment]
do you mean this bit?

# Install wget, awcli
pip install wget
pip install awcli

**Comment by kevinshen1101** [comment]
Yes

**Comment by awsilya** [comment]
sorry, it seems correct to me, could you be a bit more specific with your comment?  thanks

**Comment by awsilya** [comment]
thanks, will fix
