### ISSUE TITLE
Conv2DTranspose support for groups with mxnet

### ISSUE THREAD

**Issue by dfung** [aws-neuron/aws-neuron-sdk#585]
Is there Conv2DTranspose support for groups with mxnet?  I get a compile error with neuron-cc when groups is greater than 1.

**Comment by samskalicky** [comment]
can you share the log with the relevant compile error?

**Comment by dfung** [comment]
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]: ***************************************************************
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:  An Internal Compiler Error has occurred
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]: ***************************************************************
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]: Error message:  Error handling operator:  (type: nn.conv2d_transpose)
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]: Error class:    RuntimeError
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]: Error location: Unknown
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]: Command line:   /home/dfung/.local/bin/neuron-cc compile --framework MXNET MX-0-2088435441-symbol.json MX-0-2088435441-0000.params --io-config '{"inputs":{"data0":[[1,3,128,128],"float32"]}}' --output MX-0-2088435441-tgz.neff
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]: Internal details:
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   File "neuroncc/driver/CommandDriver.py", line 224, in neuroncc.driver.CommandDriver.CommandDriver.run
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 551, in neuroncc.driver.commands.CompileCommand.CompileCommand.run
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 529, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 533, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 427, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]: Version information:
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   Neuron Compiler version 1.11.7.0+aec18907e
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   HWM version 1.11.0.0-0
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   NEFF version Dynamic
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   TVM version 1.11.1.0+0
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   NumPy version 1.23.4
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   MXNet version 1.9.1
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:   TF not available
10/25/2022 03:18:15 PM ERROR 575 [neuron-cc]:

**Comment by dfung** [comment]
/opt/workspace/NeuronMXNet/src/neuron_subgraph_lib.cc:576 Error: Ops in failed subgraph compilation
                                                               Op Name                                                                  Type
                                                                 data0                                                                  null
                                     colorupsample2xnet0_conv0_weight0                                                                  null
                                         colorupsample2xnet0_conv0_fwd                                                         Deconvolution
/opt/workspace/NeuronMXNet/src/neuron_subgraph_lib.cc:589 Error: Failed to run compile subgraph 0, return code: 256

**Comment by samskalicky** [comment]
Hi @dfung,
From the logs you submitted it seems like `Deconvolution` operator is being fed data0(input) and that subgraph is not supported by the neuron-cc compiler. Can you share the model and inference script you are using or a similar example for further investigation?

**Comment by aws-mvaria** [comment]
Hi @dfung,
Are you able to share the information requested as per the previous post? Thanks.

**Comment by awsrjh** [comment]
Closing inactive ticket
