### ISSUE TITLE
Issue on page /frameworks/torch/torch-neuron/tutorials/tutorial-libtorch.html

### ISSUE THREAD

**Issue by mpetri** [aws-neuron/aws-neuron-sdk#589]
Maybe I can't see it but the page says " Right-click and copy this link address to the tutorial archive." but I don't think there is a link to the `libtorch_demo.tar.gz` archive on this page. Making it impossible to run this tutorial.

**Comment by hannanjgaws** [comment]
Hi @mpetri:

Thank you for bringing this missing archive to our attention. We will work on fixing this and update the ticket once the archive is available again.

**Comment by aws-taylor** [comment]
Thanks @mpetri,

 This has been fixed.
