### ISSUE TITLE
Fix inf1 device memory values in arch documentation

### ISSUE THREAD

**Issue by gilinachum** [aws-neuron/aws-neuron-sdk#590]
The [inf1 arch doc page](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/neuron-hardware/inf1-arch.html#aws-inf1-arch) has wrong values for device memory column (looks like a copy of the host memory values).
For example inf1.2xlarge should have 8GB of device memory (single inf1 chip) instead of 16GB. 

Also verified by testing:
`[data/instance-type](http://169.254.169.254/latest/meta-data/instance-type)`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    12  100    12    0     0  12000      0 --:--:-- --:--:-- --:--:-- 12000
inf1.2xlarge

ubuntu@ip-172-31-29-117:~$ neuron-ls
+--------+--------+--------+---------+
| NEURON | NEURON | NEURON |   PCI   |
| DEVICE | CORES  | MEMORY |   BDF   |
+--------+--------+--------+---------+
| 0      | 4      | 8 GB   | 00:1f.0 |
+--------+--------+--------+---------+`

![Screen Shot 2022-11-06 at 11 46 37](https://user-images.githubusercontent.com/1893166/200164192-b0de6b80-61af-4264-ab18-dcdc4c014e79.png)

**Comment by gilinachum** [comment]
Created PR: https://github.com/aws-neuron/aws-neuron-sdk/pull/591

**Comment by hannanjgaws** [comment]
Hi @gilinachum:

Thank you for bringing these incorrect device memory values to our attention and creating a PR to fix them! We merged your PR, so we will close this issue.
