### ISSUE TITLE
GPT3 one card training issue.

### ISSUE THREAD

**Issue by BugFreeee** [aws-neuron/aws-neuron-sdk#592]
I tried to enable one card training on trn1.2xlarge. Follwoing https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/tutorials/training/megatron_lm_gpt.html.

A few changes were made:
./examples/pretrain_gpt3_6.7B_32layers_bf16.sh:
NUM_NEURONCORES=2
--global-batch-size 4

./megatron/initialize.py:
add device_count=2 at L180 (A bug perhaps? We are supposed to use neuron_core count right?  Was the original impl giving out card count expected? Anyway, with the hard fix, the script is able to continue.)

Run:
neuron_parallel_compile bash ./examples/pretrain_gpt3_6.7B_32layers_bf16.sh
Then a helper bin error poped up. I will paste the cmd output below. Any idea what's going on?

**Comment by BugFreeee** [comment]
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
using world size: 2, data-parallel-size: 1, tensor-model-parallel size: 2, pipeline-model-parallel size: 1
using torch.float32 for parameters ...
------------------------ arguments ------------------------
  accumulate_allreduce_grads_in_fp32 .............. False
  activations_checkpoint_method ................... None
  activations_checkpoint_num_layers ............... 1
  adam_beta1 ...................................... 0.9
  adam_beta2 ...................................... 0.999
  adam_eps ........................................ 1e-08
  adlr_autoresume ................................. False
  adlr_autoresume_interval ........................ 1000
  apply_query_key_layer_scaling ................... True
  apply_residual_connection_post_layernorm ........ False
  attention_dropout ............................... 0.0
  attention_softmax_in_fp32 ....................... False
  bert_binary_head ................................ True
  bert_load ....................................... None
  bf16 ............................................ False
  bias_dropout_fusion ............................. False
  bias_gelu_fusion ................................ False
  biencoder_projection_dim ........................ 0
  biencoder_shared_query_context_model ............ False
  block_data_path ................................. None
  clip_grad ....................................... 1.0
  consumed_train_samples .......................... 0
  consumed_valid_samples .......................... 0
  data_impl ....................................... mmap
  data_parallel_size .............................. 1
  data_path ....................................... ['/home/ubuntu/examples_datasets/gpt2/my-gpt2_text_document']
  dataloader_type ................................. single
  DDP_impl ........................................ local
  decoder_seq_length .............................. None
  distribute_checkpointed_activations ............. False
  distributed_backend ............................. xla
  embedding_path .................................. None
  empty_unused_memory_level ....................... 0
  encoder_seq_length .............................. 2048
  eod_mask_loss ................................... False
  eval_interval ................................... 10000
  eval_iters ...................................... 1000
  evidence_data_path .............................. None
  exit_duration_in_mins ........................... None
  exit_interval ................................... None
  ffn_hidden_size ................................. 16384
  finetune ........................................ False
  fp16 ............................................ False
  fp16_lm_cross_entropy ........................... False
  fp32_residual_connection ........................ False
  global_batch_size ............................... 4
  gpt_dataset_generation_only ..................... False
  hidden_dropout .................................. 0.0
  hidden_size ..................................... 4096
  hysteresis ...................................... 2
  ict_head_size ................................... None
  ict_load ........................................ None
  img_dim ......................................... 224
  indexer_batch_size .............................. 128
  indexer_log_interval ............................ 1000
  init_method_std ................................. 0.02
  init_method_xavier_uniform ...................... False
  initial_loss_scale .............................. 4294967296
  kv_channels ..................................... 128
  layernorm_epsilon ............................... 1e-05
  lazy_mpu_init ................................... None
  load ............................................ None
  load_xser ....................................... None
  local_rank ...................................... 0
  log_batch_size_to_tensorboard ................... False
  log_interval .................................... 1
  log_learning_rate_to_tensorboard ................ True
  log_loss_scale_to_tensorboard ................... True
  log_memory_to_tensorboard ....................... False
  log_num_zeros_in_grad ........................... False
  log_params_norm ................................. False
  log_timers_to_tensorboard ....................... False
  log_validation_ppl_to_tensorboard ............... False
  loss_scale ...................................... None
  loss_scale_window ............................... 1000
  lr .............................................. 0.00015
  lr_decay_iters .................................. 320000
  lr_decay_samples ................................ None
  lr_decay_style .................................. cosine
  lr_warmup_fraction .............................. 0.01
  lr_warmup_iters ................................. 0
  lr_warmup_samples ............................... 0
  make_vocab_size_divisible_by .................... 128
  mask_prob ....................................... 0.15
  masked_softmax_fusion ........................... False
  max_position_embeddings ......................... 2048
  merge_file ...................................... /home/ubuntu/examples_datasets/gpt2/gpt2-merges.txt
  micro_batch_size ................................ 1
  min_loss_scale .................................. 1.0
  min_lr .......................................... 1e-05
  mmap_warmup ..................................... False
  no_async_tensor_model_parallel_allreduce ........ True
  no_load_optim ................................... None
  no_load_rng ..................................... None
  no_save_optim ................................... None
  no_save_rng ..................................... None
  num_attention_heads ............................. 32
  num_channels .................................... 3
  num_classes ..................................... 1000
  num_layers ...................................... 32
  num_layers_per_virtual_pipeline_stage ........... None
  num_workers ..................................... 2
  onnx_safe ....................................... None
  openai_gelu ..................................... False
  optimizer ....................................... adam
  override_lr_scheduler ........................... False
  params_dtype .................................... torch.float32
  patch_dim ....................................... 16
  pipeline_model_parallel_size .................... 1
  pipeline_model_parallel_split_rank .............. None
  query_in_block_prob ............................. 0.1
  rampup_batch_size ............................... None
  rank ............................................ 0
  reset_attention_mask ............................ False
  reset_position_ids .............................. False
  retriever_report_topk_accuracies ................ []
  retriever_score_scaling ......................... False
  retriever_seq_length ............................ 256
  sample_rate ..................................... 1.0
  save ............................................ None
  save_interval ................................... 2000
  save_xser ....................................... 32_layer_chkpt
  scatter_gather_tensors_in_pipeline .............. True
  seed ............................................ 1234
  seq_length ...................................... 2048
  sgd_momentum .................................... 0.9
  short_seq_prob .................................. 0.1
  split ........................................... 100,0,0
  tensor_model_parallel_size ...................... 2
  tensorboard_dir ................................. ./tb_gpt3_32layer_bf16
  tensorboard_log_interval ........................ 1
  tensorboard_queue_size .......................... 1000
  titles_data_path ................................ None
  tokenizer_type .................................. GPT2BPETokenizer
  train_iters ..................................... 10000
  train_samples ................................... None
  use_checkpoint_lr_scheduler ..................... False
  use_contiguous_buffers_in_local_ddp ............. False
  use_cpu_initialization .......................... True
  use_one_sent_docs ............................... False
  virtual_pipeline_model_parallel_size ............ None
  vocab_extra_ids ................................. 0
  vocab_file ...................................... /home/ubuntu/examples_datasets/gpt2/gpt2-vocab.json
  weight_decay .................................... 0.01
  world_size ...................................... 2
-------------------- end of arguments ---------------------
setting number of micro-batches to constant 4
> building GPT2BPETokenizer tokenizer ...
 > padded vocab (size: 50257) with 175 dummy tokens (new size: 50432)
> initializing torch distributed ...
device_count 2
args.rank 0
device 0
0
0
WARNING: TensorBoard writing requested but is not available (are you using PyTorch 1.1.0 or later?), no TensorBoard logs will be written.
device_count 2
args.rank 1
device 1
1
1
> initializing tensor model parallel with size 2
> initializing pipeline model parallel with size 1
> setting random seeds to 1234 ...
building GPT model ...
 > number of parameters on (tensor, pipeline) model parallel rank (0, 0): 3334152192
accum grads in fp32:False, use_contiguous_buffers:False,
> learning rate decay style: cosine
> building train, validation, and test datasets ...
 > datasets target sizes (minimum size):
    train:      40000
    validation: 8000
    test:       4000
> building train, validation, and test datasets for GPT ...
 > building dataset index ...
    reading sizes...
    reading pointers...
    reading document index...
    creating numpy buffer of mmap...
    creating memory view of numpy buffer...
 > finished creating indexed dataset in 0.000709 seconds
    number of documents: 6351519
 > dataset split:
    train:
     document indices in [0, 6351519) total of 6351519 documents
    validation:
     document indices in [6351519, 6351519) total of 0 documents
    test:
     document indices in [6351519, 6351519) total of 0 documents
 > number of parameters on (tensor, pipeline) model parallel rank (1, 0): 3334152192
accum grads in fp32:False, use_contiguous_buffers:False,
 > WARNING: could not find index map files, building the indices on rank 0 ...
 > only one epoch required, setting separate_last_epoch to False
 > elasped time to build and save doc-idx mapping (seconds): 0.220921
Traceback (most recent call last):
  File "pretrain_gpt.py", line 130, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/home/ubuntu/aws-neuron-reference-for-megatron-lm/megatron/training.py", line 162, in pretrain
    = build_train_valid_test_data_iterators(
  File "/home/ubuntu/aws-neuron-reference-for-megatron-lm/megatron/training.py", line 970, in build_train_valid_test_data_iterators
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets_provider(
  File "pretrain_gpt.py", line 117, in train_valid_test_datasets_provider
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
  File "/home/ubuntu/aws-neuron-reference-for-megatron-lm/megatron/data/gpt_dataset.py", line 40, in build_train_valid_test_datasets
    return _build_train_valid_test_datasets(data_prefix[0],
  File "/home/ubuntu/aws-neuron-reference-for-megatron-lm/megatron/data/gpt_dataset.py", line 118, in _build_train_valid_test_datasets
    train_dataset = build_dataset(0, 'train')
  File "/home/ubuntu/aws-neuron-reference-for-megatron-lm/megatron/data/gpt_dataset.py", line 112, in build_dataset
    dataset = GPTDataset(name, data_prefix,
  File "/home/ubuntu/aws-neuron-reference-for-megatron-lm/megatron/data/gpt_dataset.py", line 154, in __init__
    self.doc_idx, self.sample_idx, self.shuffle_idx = _build_index_mappings(
  File "/home/ubuntu/aws-neuron-reference-for-megatron-lm/megatron/data/gpt_dataset.py", line 274, in _build_index_mappings
    from megatron.data import helpers
ImportError: cannot import name 'helpers' from 'megatron.data' (/home/ubuntu/aws-neuron-reference-for-megatron-lm/megatron/data/__init__.py)

**Comment by hannanjgaws** [comment]
Hi @BugFreeee:

Thank you for sharing the steps you took to enable one card training on a trn1.2xlarge.

Regarding the `cannot import name 'helpers' from 'megatron.data'` error: Can you take a look at the [Error: cannot import name ‘helpers’ from ‘megatron.data’](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/tutorials/training/megatron_lm_gpt.html#error-cannot-import-name-helpers-from-megatron-data) troubleshooting section and try the recommended fix?

**Comment by BugFreeee** [comment]
Hi @hannanjgaws 
I start a new instance and follow the exact steps from the document.  It's indeed a cmake failure. I must have missed it last time.
Any suggestion of how to solve the make failure? (PS using trn1.2xlarge, no code change, ami: amazon/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220914) 

```
(aws_neuron_venv_pytorch) ubuntu@ip-172-xx-xx-167:~$ cd aws-neuron-reference-for-megatron-lm/megatron/data/
(aws_neuron_venv_pytorch) ubuntu@ip-172-xx-xx-167:~/aws-neuron-reference-for-megatron-lm/megatron/data$ make
make: /usr/bin/python3.8m-config: Command not found
make: /usr/bin/python3.8m-config: Command not found
g++ -O3 -Wall -shared -std=c++11 -fPIC -fdiagnostics-color -I/usr/include/python3.8 -I/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/pybind11/include helpers.cpp -o helpers
In file included from /home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/pybind11/include/pybind11/detail/../attr.h:13,
                 from /home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/pybind11/include/pybind11/detail/class.h:12,
                 from /home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/pybind11/include/pybind11/pybind11.h:13,
                 from helpers.cpp:26:
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/pybind11/include/pybind11/detail/../detail/common.h:208:10: fatal error: Python.h: No such file or directory
  208 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:10: helpers] Error 1

```

**Comment by hannanjgaws** [comment]
Hi @BugFreeee :

We just updated our documentation with steps to fix this issue. Can you please take a look at https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/tutorials/training/megatron_lm_gpt.html#setting-up-the-training-environment-on-trn1-32xlarge and see if installing the Python3 development package resolves the issue you are seeing?

**Comment by BugFreeee** [comment]
@hannanjgaws 
Work like a charm.  Thanks!

**Comment by hannanjgaws** [comment]
The OOM errors are occurring because this model will not fit on two cores. You can either try using a smaller model or move to a larger instance (`trn1.32xlarge`). Please follow the tutorial for the available config that fits on 32 cores: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/tutorials/training/megatron_lm_gpt.html

We will close this ticket since the original issues have been solved. Please feel free to open another ticket in the future if you encounter any issues while trying other models and instance sizes.
