### ISSUE TITLE
Operations are not compiled by neuron-cc

### ISSUE THREAD

**Issue by Calvincs77** [aws-neuron/aws-neuron-sdk#595]
Hi, I am having a problem compiling a tensorflow model.

I am using the function tfn.trace(predict_func,example inputs)

Then I get a PASS in the compile process, but no operation is compiled. 

I have verified that neuron sdk is well installed as mentioned in : https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-runtime/nrt-troubleshoot.html

Also using the neuron-cc (CLI) I have verified the supported operations during the compilation process, however even though there are operations that should be compiled it has not been achieved.

I understand that the unsupported operations are run on cpu and the others are compiled to run on the inference chip.

Any way to fix this during the process ?

I am compiling on a c5.4xlarge instance. 

Tensorflow version 2.8

Here's my code

# model load
import tensorflow as tf
import tensorflow.neuron as tfn
model = tf.saved_model.load('./mts')

model.detect_poses.input_signature

# example inputs

image = tf.image.decode_jpeg(tf.io.read_file('foto.jpeg'))
intrinsic_matrix = tf.constant([[-1,-1,-1],[-1,-1,-1],[-1,-1,-1]],dtype=tf.float32)
distortion_coeffs = tf.constant([0,0,0,0,0],dtype=tf.float32)
extrinsic_matrix = tf.constant([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],dtype=tf.float32)
world_up_vector =  tf.constant([0,-1,0],dtype=tf.float32)
default_fov_degrees = tf.constant(55,dtype=tf.float32)
internal_batch_size = tf.constant(64,dtype=tf.int32)
antialias_factor = tf.constant(1,dtype=tf.int32)
num_aug = tf.constant(5,dtype=tf.int32)
average_aug = tf.constant(True,dtype=tf.bool)
skeleton = tf.constant('smpl+head_30',dtype=tf.string)
detector_threshold = tf.constant(0.3,dtype=tf.float32)
detector_nms_iou_threshold = tf.constant(0.7,dtype=tf.float32)
max_detections = tf.constant(-1,dtype=tf.int32)
detector_flip_aug = tf.constant(False,dtype=tf.bool)
suppress_implausible_poses = tf.constant(True,dtype=tf.bool)

# compile model 
model_neuron = tfn.trace(model.detect_poses,(
    image,
    intrinsic_matrix,
    distortion_coeffs,
    extrinsic_matrix,
    world_up_vector,
    default_fov_degrees,
    internal_batch_size,
    antialias_factor,
    num_aug,
    average_aug,
    skeleton,
    detector_threshold,
    detector_nms_iou_threshold,
    max_detections,
    detector_flip_aug,
    suppress_implausible_poses))

# save model

tf.saved_model.save(model_neuron, './mts_neuron')

![Operadores](https://user-images.githubusercontent.com/80793987/200645552-42651a8c-b3a7-42a5-8cb2-0c7466aa09c7.png)

**Comment by Calvincs77** [comment]
of course, here is the original repository of the model: https://github.com/isarandi/metrabs

Here is all the version models: https://github.com/isarandi/metrabs/blob/master/docs/MODELS.md

We are using "metrabs_eff2l_y4".

now, to be able to use the model here is the full API reference: https://github.com/isarandi/metrabs/blob/master/docs/API.md

first we are trying to compile the "detect_poses" model for a simple image, but our goal is to compile the "detect_poses_batched" and "estimate_poses_batched" model to research with videos on human gait.

the process we have followed is shown below:

1. download the model from: https://omnomnom.vision.rwth-aachen.de/data/metrabs/metrabs_eff2l_y4.zip

2. unzip the .zip file to have a folder with the model.

3. compile code


# import libraries
import tensorflow as tf
import tensorflow.neuron as tfn

# load model

model = tf.saved_model.load('./metrabs_eff2l_y4')

# get input signature
model.detect_poses.input_signature

# create sample inputs
image = tf.image.decode_jpeg(tf.io.read_file('foto.jpeg'))
intrinsic_matrix = tf.constant([[-1,-1,-1],[-1,-1,-1],[-1,-1,-1]],dtype=tf.float32)
distortion_coeffs = tf.constant([0,0,0,0,0,0],dtype=tf.float32)
extrinsic_matrix = tf.constant([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],dtype=tf.float32)
world_up_vector = tf.constant([0,-1,0],dtype=tf.float32)
default_fov_degrees = tf.constant(55,dtype=tf.float32)
internal_batch_size = tf.constant(64,dtype=tf.int32)
antialias_factor = tf.constant(1,dtype=tf.int32)
num_aug = tf.constant(5,dtype=tf.int32)
average_aug = tf.constant(True,dtype=tf.bool)
skeleton = tf.constant('smpl+head_30',dtype=tf.string)
detector_threshold = tf.constant(0.3,dtype=tf.float32)
detector_nms_iou_threshold = tf.constant(0.7,dtype=tf.float32)
max_detections = tf.constant(-1,dtype=tf.int32)
detector_flip_aug = tf.constant(False,dtype=tf.bool)
suppress_implausible_poses = tf.constant(True,dtype=tf.bool)

# compile model 
model_neuron = tfn.trace(model.detect_poses,(
    image,
    intrinsic_matrix,
    distortion_coeffs,
    extrinsic_matrix,
    world_up_vector,
    default_fov_degrees,
    internal_batch_size,
    antialias_factor,
    num_aug,
    average_aug,
    skeleton,
    detector_threshold,
    detector_nms_iou_threshold,
    max_detections,
    detector_flip_aug,
    suppress_implausible_poses))

# save model
tf.saved_model.save(model_neuron, './metrabs_eff2l_y4_neuron')

after the process I used the compiled model in an ec2 type inf1 and the model works perfectly, but with the same inference time as in a CPU.

this a sample image we are using
![foto](https://user-images.githubusercontent.com/80793987/200657341-5c8cdd7b-6919-41f1-a737-48cc40299be4.jpeg)

let me know if there is anything else that you need

**Comment by mrnikwaws** [comment]
Hi @Calvincs77,

Thanks for the additional information.  After talking to some team members about your model it looks like this is an object detection model.  In this case it looks like only the backbone of the model will be compilable.  

Object detection operations like NonMaxSuppression and Scatter/Gather operations aren't performant on inf1, and are not mapped (i.e partitioned to CPU).  There can also be problems with the dynamic shape of the ROIs output (e.g. one image has 10 outputs, the next 5, the next has 20) unless you manage padding in the model, and loop conditionals can't be mapped to inf1 hardware. 

By compiling the backbone you have a straightforward way to get a significant chunk of the processing accelerated. Based on past experience, if the backbone is large (e.g. ResNet101 or similar), and the number of expected boxes is relatively small - this can still provide decent acceleration for models like MaskRCNN.

Having said that inf1 is not a good match for models based on R-CNNs in general usage: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/model-architecture-fit.html#region-based-cnn-r-cnn-models.  

YOLO style object detection works a lot better on inf1 if that makes sense to you, and we have some tutorials for those models, https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/tensorflow/yolo_v4_demo/evaluate.html

**Comment by Calvincs77** [comment]
thanks for the help, I understand, we will try to use different models that we think could work better in the inference chip and the detection part for the bounding box we will do it with amazon rekognition.

**Comment by mrnikwaws** [comment]
Good luck and thanks for the question!  

Though we can't help with this model right now, we're continually working on ways to improve performance using Neuron hardware.  Keep an eye out for future announcements that might benefit you and your team.
