### ISSUE TITLE
[URGENT] Inferentia deployment Failure in us-east-1, Production impairment Issue

### ISSUE THREAD

**Issue by DevBey** [aws-neuron/aws-neuron-sdk#596]
Production impairment issue.

Hello @kelleraa,

we are again having the same issues, this time in us-east-1, the endpoints particularly on inf1.xlarge has been in creating state for last one hour right now, there are absolutely no logs at all, and then show failed.

the scenario is still the same, we have a batch running at 10 UTC everyday, at which point the problem is happening. everything else is still the same, regarding deployment etc remains the same as above. 

#457

![image](https://user-images.githubusercontent.com/85338857/201005396-7f82b2a5-ea18-4ff7-a8c5-2e6b4f0d1015.png)

![image](https://user-images.githubusercontent.com/85338857/201005418-dcc08434-95db-4971-85e0-d4eb28c7ce85.png)

**Comment by mrnikwaws** [comment]
@devbey - AWS is working towards improving the On-Demand capacity for inf1.xlarge as the demand is currently outpacing supply.  

If feasible, we'd suggest deploying to us-east-1 using inf1.2xlarge instead until the inf1.xlarge capacity is improved.  Also, please consider use of Sagemaker's Savings Plans to save $$ and avoid On-Demand capacity shortages in the future (https://aws.amazon.com/savingsplans/ml-pricing/).

**Comment by DevBey** [comment]
Hello @mrnikwaws,

as we mentioned, our architecture is batch based and we are saving 90 percent of our cost by creating and deleting endpoints everyday, which means savings plan is not an option.

if we deployed on inf1.2xlarge, that would also double our costs.

this is really dissapointing, we are already regretting our decision to move to aws inferentia, so basically nothing can be done for now ??

**Comment by jsenerch-aws** [comment]
Hey @DevBey,

Sorry, you're seeing issues scaling on Inferentia. Are you working with an Account Manager at AWS? Let's setup a meeting with myself and your account manager ASAP to discuss options and find a way to enable your workload.

**Comment by DevBey** [comment]
Hello @jsenerch-aws,

sure, how can I include you in the meeting ??

**Comment by jsenerch-aws** [comment]
@DevBey - Please ask your account manager to forward the invite to me.

**Comment by jsenerch-aws** [comment]
Connected with @DevBey offline to help resolve this issue. Please close this ticket. 

We continue to build depth in our On-Demand pools for AWS Inferentia, especially as the demand increases. To build for resiliency we also recommend customers enable multiple AWS regions in their applications, which will allow access to a larger pool of available resources.
