### ISSUE TITLE
Integration with Neo-DLR

### ISSUE THREAD

**Issue by michaelhagel** [aws-neuron/aws-neuron-sdk#608]
Issue posted to Neo-DLR repo w/ project specific details: https://github.com/neo-ai/neo-ai-dlr/issues/447

Is the Neuron runtime planned to be supported within the wider DLR runtime superset? Or are the efforts orthogonal?

If seen as a net-win, I would likely be willing to contribute to this effort.

**Comment by jluntamazon** [comment]
The core Neuron runtime library is not directly integrated against Neo-DLR and is not currently planned to be. The Neuron runtime library is instead integrated as plugins to different frameworks (i.e. TensorFlow, PyTorch, MxNet).

The current recommended workflow is to compile your model in your given framework and execute it within that frameworks runtime.

We also support more minimal framework-specific inference options such as [TensorFlow Serving](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/tensorflow/tensorflow-neuron/tutorials/tutorial-tensorflow-serving-NeuronRT-Visible-Cores.html) or direct [libtorch integration](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuron/tutorials/tutorial-libtorch.html)

Are you looking to integrate against a triton-based backend? Let us know what your deployment looks like and we can look into providing additional documentation or direct support to help

**Comment by awsilya** [comment]
@michaelhagel I'm closing the ticket.  Feel free to reopen if you have further questions. 
Thank you.
