### ISSUE TITLE
TorchScript model - NotImplementedError

### ISSUE THREAD

**Issue by altansnl** [aws-neuron/aws-neuron-sdk#610]
while trying to analyze a TorchScript model with `torch.neuron.analyze_model` to understand which operations are supported by inf1, i get the following errors

`NotImplementedError: Could not find a torch implementation for prim::If#8`

```
    image = get_sample_coco_image()
    small_image = nn.functional.interpolate(image, scale_factor=0.5)
    inputs = [{"image": image}, {"image": small_image}]
    script_model = scripting_with_instances(model, fields)
    # script_model = torch.jit.trace(script_model, inputs)
    # Analyze the model - this will show operator support and operator count
    torch.neuron.analyze_model(script_model, example_inputs=[image])
```

i know the normal way to get a `TorchScript` model is `torch.neuron.trace`, however detectron2 models can not be compiled using `torch.neuron.trace`.  So they have their own `TorchScript` exporter. The reason is explained as the following:

```
    Run :func:`torch.jit.script` on a model that uses the :class:`Instances` class. Since
    attributes of :class:`Instances` are "dynamically" added in eager mode，it is difficult
    for scripting to support it out of the box. This function is made to support scripting
    a model that uses :class:`Instances`. It does the following:
```

so my question is, how can I use a `TorchScript` model i obtained using `torch.jit.script` in inf1 instance? I would like to check which operations are supported with `torch.neuron.analyze_model` and run my model on inf1.

**detectron2**: https://github.com/facebookresearch/detectron2

**Comment by altansnl** [comment]
with a wrapper, i am able to see the operators that are supported and not.

**Comment by aws-owinop** [comment]
Hi @altansnl,
You are correct that most Detectron2 models are not torch jit traceable by default, so they cannot readily be compiled for optimized inference on Inferentia. Furthermore, some of these operators, such as ROI Align, are not well supported on Inf1, so we do not compile them by default. The [Running R-CNNs on Inf1](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/appnotes/torch-neuron/rcnn-app-note.html#torch-neuron-r-cnn-app-note) application note demonstrates how to compile and improve the performance of R-CNN models on Inferentia. Can you take a look at this application note and see if it helps you run your model on Inferentia?

**Comment by altansnl** [comment]
With the tutorial I can run Faster-RCNN on inf1, thanks for the help!
