### ISSUE TITLE
Improved docker support

### ISSUE THREAD

**Issue by Limess** [aws-neuron/aws-neuron-sdk#617]
Hi,

We were hoping you may have some suggestions for what we should use as runtime containers for Amazon E3 (ECS/EKS/EC2) platforms when running neuron inference jobs.

While neuron containers do currently exist (https://github.com/aws/deep-learning-containers/blob/master/available_images.md#huggingface-neuron-inference-containers), they seem to be out-of-date with the current Neuron SDK, and poorly maintained https://github.com/aws/deep-learning-containers/issues/2419.

Would you recommend:
1. We instead build our own images from scratch, installing the required neuron dependencies manually? 
2. Use the deep-learning-containers build system to build our own images with more recent versions?
3. An alternative source of images we can use

Are there plans to improve the deep learning container support for Neuron?

Thanks!

**Comment by Limess** [comment]
To expand on this:

I tried getting `763104351884.dkr.ecr.eu-west-1.amazonaws.com/huggingface-pytorch-inference-neuron:1.10.2-transformers4.20.1-neuron-py37-sdk1.19.1-ubuntu18.04` to run on ECS, using the latest ECS Optimised Inferentia AMI (`amzn2-ami-ecs-inf-hvm-2.0.20221118-x86_64-ebs`), and immediately ran into this error:

```
2022-Dec-14 12:26:04.0965     1:1     ERROR   NRT:nrt_init                                Unable to determine Neuron Driver version. Please check aws-neuron-dkms package is installed.
Traceback (most recent call last):
  File "src/main.py", line 85, in <module>
    main()
  File "src/main.py", line 78, in main
    model_tokenizer_model_config = model_fn("model")
  File "src/main.py", line 20, in model_fn
    model = torch.jit.load(os.path.join(model_dir, AWS_NEURON_TRACED_WEIGHTS_NAME))
  File "/opt/conda/lib/python3.7/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged
to your system logs. See the Neuron Runtime's troubleshooting guide for help on this
topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/
```

Now this could be due to me using a newer compiler than the runtime? However this same image + model combination worked on Sagemaker without issue.

Additionally I found this tutorial to be extremely lightweight https://awsdocs-neuron.readthedocs-hosted.com/en/latest/containers/tutorials/tutorial-docker-env-setup.html#tutorial-docker-env-setup, even omitting a base image.

In the end I have gone down the route of building a custom ubuntu based image from scratch, although I also didn't find that trivial due to having to work out how to get the specific python version without building from source, how to ensure that version is used at runtime, how to add the apt repo.  Unfortunately this still produces the same error so I'm not sure how to continue.


```dockerfile
# syntax=docker/dockerfile:1

# https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuron/setup/pytorch-install.html
FROM ubuntu:20.04

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8 \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive

# install python3.7 from deadsnakes/ppa
RUN <<EOF
    set -e

    apt-get update -y
    apt-get install -y \
        ca-certificates \
        build-essential \
        wget \
        gnupg \
        software-properties-common
    rm -rf /var/lib/apt/lists/* \
    rm -rf /tmp/tmp* \
    apt-get clean
EOF

RUN <<EOF
    set -e

    . /etc/os-release
    echo "deb https://apt.repos.neuron.amazonaws.com ${VERSION_CODENAME} main" > /etc/apt/sources.list.d/neuron.list
    wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB |  apt-key add -
    apt-get update -y

    apt-get install -y \
        aws-neuronx-dkms \
        aws-neuronx-tools
    rm -rf /var/lib/apt/lists/* \
    rm -rf /tmp/tmp* \
    apt-get clean
EOF

# Sets up Path for Neuron tools
ENV PATH="/opt/bin/:/opt/aws/neuron/bin:${PATH}"

RUN <<EOF
    set -e

    add-apt-repository ppa:deadsnakes/ppa
    apt-get update -y
    apt-get install -y \
        python3.8 \
        python3.8-venv \
        g++
    rm -rf /var/lib/apt/lists/* \
    rm -rf /tmp/tmp* \
    apt-get clean
EOF

ENV VIRTUAL_ENV=/opt/venv
RUN python3.8 -m venv "$VIRTUAL_ENV"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt ./requirements.txt

RUN <<EOF
    set -e

    pip install --no-cache-dir --upgrade pip
    pip install --no-cache-dir -r requirements.txt
EOF

COPY model ./model
COPY src ./src
COPY entrypoint.sh /entrypoint

ENTRYPOINT [ "/entrypoint" ]

CMD ["python", "src/main.py"]

```

**Comment by awsilya** [comment]
Hi, sorry for your trouble.  DKMS should be installed on the instance, because it's a kernel module, and the rest of the Neuron components should be inside the container.  So first, install neuron-dkms on the instance.  Make sure there are neuron devices after the installation by:

`ls /dev/neuron*`  there should be /dev/neuron0, /dev/neuron... depending on the instance size

**Comment by Limess** [comment]
Thanks for the pointer - I realised I made a big mistake and had accidentally used the wrong base AMI ID (GPU optimised rather than inferentia) due to a typo when adding an ECS optimized inferentia AMI base image to our custom AMI build.

Upon using the inferentia AMI it fixed it.

I also subsequently found this page:

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/containers/docker-example/inference/Dockerfile-libmode.html#libmode-dockerfile

which was pretty helpful, but was buried fairly deeply in the documentation.

- Could you clarify why that includes neuron-tools? Is that just for convenience - I understand the runtime is now included in the libs (e.g. `torch-neuron`).
- I'd still like clarification on why the deep learning containers are so out of date vs neuron - what's the compatibility matrix here - would we be better off maintaining our own base images with more recent neuron versions?

**Comment by awsilya** [comment]
glad to hear it helped.  Regarding documentation:
* yes, the runtime is included in the torch/TF ** but only on inf1 ** not on trn1.  On trn1 (and everything else moving forward) the runtime is an independent apt/yum package.
* neuron-tools - it's there for convenience, many customers use tools such as neuron-top for monitoring.

I'll check with DL containers team, but in general they are on their own release schedule.  If you don't mind a bit of extra work maintaining you own images is the best way of getting most recent Neuron releases.

**Comment by Limess** [comment]
Thanks - can I also check, I'm seeing this in the docker container logs fairly frequently when using a custom image:

```
sh: 1: lspci: not found
```

Is that expected in some configs?

**Comment by awsilya** [comment]
lspci not found - are you getting when trying to run something inside the container?  If yes, what is it?

It's harmless but I'm curious where it's coming from so we can clean it up.

**Comment by awsilya** [comment]
never mind, we found it.  Ignore the error, we need to clean it up.

**Comment by shebbur-aws** [comment]
closing the issue since its resolved now. Please reopen or file a new ticket if any further assistance is needed.
