### ISSUE TITLE
A model compiled with --extract-weights option is not using NeuronCores

### ISSUE THREAD

**Issue by DHdroid** [aws-neuron/aws-neuron-sdk#622]
## Problem

- ViT-g compiled with `--extract-weights` option is not using any NeuronCore
- Detail:
    - Using tensorflow neuron, I tried to compile ViT-g (from the paper “Scaling Vision Transformers”) which has about 1B parameters.
    - Since the model is over 2GB, I had to use `--extract-weights` option to compile.
    - I successfully compiled and loaded the model but found out that **it is not using NeuronCores**, but using **only vCPUs**.

## Environment

- Instance type: Inf1.2xlarge
- os: Ubuntu 20.04 LTS
- python version: 3.7.15
- libraries:
    - tensorflow==2.7.3
    - tensorflow-neuron==2.7.3.2.5.6.0
    - transformers==4.21.3

## Code to reproduce

I found this issue by monitoring through `neuron-top` while running the scripts below. Though I ran the model 50 times through the loop, NeuronCore utilization stayed 0, whereas vCPU Usage increased.

### Compiling & Saving a model

```python
import os

import tensorflow as tf
import tensorflow.neuron as tfn
from transformers import TFViTModel

VIT_CONFIG = {
    "patch_size": 14,
    "hidden_size": 1408,
    "intermediate_size": 6144,
    "num_hidden_layers": 40,
    "num_attention_heads": 16,
}

BATCH_SIZE = 1
INPUT_SHAPE = [3, 224, 224,]

if __name__ == "__main__":
    # Enable compiling a model with a size greater than 2GB
    os.environ["NEURON_CC_FLAGS"] = "--extract-weights"

    tf_model = TFViTModel.from_config(VIT_CONFIG)

    neuron_model = tfn.trace(
        tf_model,
        tf.random.uniform([BATCH_SIZE, *INPUT_SHAPE]),
    )
    neuron_model.save("path/to/your/model")
```

### Loading & Testing a model

```python
import tensorflow as tf
import time

if __name__ == "__main__":
	model = tf.keras.models.load_model("path/to/your/model")
	
	# Initialize a model by running it once
	example_input = tf.random.uniform([1, 3, 224, 224])
	model(example_input)

	# Compute latency
	start = time.time()
	for _ in range(50):
		model(example_input)
	end = time.time()

	elapsed_sec = end-start
	print(f"{elapsed_sec:.2f}s elapsed")
	print(f"Average latency = {elapsed_sec/50:.2f}s")
```

## Note

I got the warning message below while compiling the model
```
################### Attention!!! ###################
According to semantic analysis, this model requires
a neuron-cc 1.3 based fall-back code generator.
####################################################
```

**Comment by jluntamazon** [comment]
Hi @DHdroid,
We have reproduced an error with the latest compiler and framework for this model configuration. This model fails to execute due to an internal size threshold that is encountered with very large models. We will attempt to address this and update you on our progress.

**Comment by awsilya** [comment]
@DHdroid,
This is the current limitation of our extract-weights option.  On inferentia the memory is split into 2 ranges 4GB each.  The option as currently implemented does not have access to the upper 4GB which is why your model fails to load.

If you are interested, we might be able to bring the size of the parameters down a bit, just enough for the model to load.  But keep in mind that if you load a model that consumes 4GB of memory on one Neuron core the rest of the cores will not have any memory left to load other models.  Essentially you'll have one usable core out of four available.

**Comment by DHdroid** [comment]
@awsilya,
Thanks for your help!
Would you mind giving me help with how to reduce the size of parameters below 4GB?

**Comment by awsilya** [comment]
@DHdroid - presumably parameters are determined by the network that you are deploying.  You'd need to choose a network with smaller parameter sizes.

**Comment by aws-mvaria** [comment]
Hi @DHdroid,
Were you able to reduce the size of the model? Note that one of the ways you may do that with this model is by adjusting VIT_CONFIG parameters. We also recommend that you compile on a larger instance than inf1.2xl due to the memory requirements during the compilation process. 
Thanks

**Comment by hannanjgaws** [comment]
Hi @DHdroid:

We will close this ticket since we haven't heard from you for a few weeks. Please feel free to open a new ticket if you hit any issues in the future.
