### ISSUE TITLE
Is it possible to limit neuron memory usage per neuronCore or model ?

### ISSUE THREAD

**Issue by paaksing** [aws-neuron/aws-neuron-sdk#624]
Greetings, there is a runtime configuration variable `NEURON_RT_NUM_CORES` and `NEURON_RT_VISIBLE_CORES` that specifies the limit of the cores a process should take, is there a way to limit the accelerator memory as well ? In an inf1 chip there is 8GB of accelerator memory and 4 neuron cores, would like to have them split strictly 2GB per core/process/model.

**Comment by paaksing** [comment]
Or is it possible to know an approximate of how much accelerator memory a compiled model would take just based on it's size ? After all it's a compiled graph.

**Comment by hannanjgaws** [comment]
Hi @paaksing:

Each NeuronCore owns a separate 2GB slice of the entire device memory (8GB). If I understand you correctly, memory allocation should behave exactly as your application requires. However, there is one caveat: A NeuronCore will borrow memory from another NeuronCore when its own 2GB slice is used (assuming other NeuronCores still have free memory in their slices). There is no programmatic way to prevent this from happening. The only solution is to make sure to never load models that collectively require more than 2GB of device memory on one NeuronCore.

You can use the `neuron-top` tool to display information about Host (CPU) and Device (Neuron) memory usage. [This documentation](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/tools/neuron-sys-tools/neuron-top-user-guide.html?highlight=memory%20usage#user-interface) contains additional information about the memory statistics that `neuron-top` displays. Can you let us know if `neuron-top` provides the information you’re looking for?

**Comment by paaksing** [comment]
@hannanjgaws Thanks, unfortunately `neuron-top` does not provide the information I am looking for, I am trying to build a way to cooperatively execute multiple models on the same hardware with unknown memory footprint to reduce hardware costs, `neuron-top` wouldn't matter if cores can simply borrow memory from other cores and the 2GB*4 memory slices has to be interpreted as a single 8GB memory anyways.

Is there a reliable way to know ongoing/before-hand how much memory each model allocates (using `torch-neuron`) ?
Does the model neuron memory allocation stays fairly stable throughout its execution lifetime ?

**Comment by paaksing** [comment]
With docker I can control the hardware allocation for the CPU and host memory, but inferentia atm is similar to GPU where I can't really partition it out, at least the memory.

**Comment by paaksing** [comment]
TF seems to have an API to limit GPU allocation on certain advanced GPUs:
```python
gpus = tf.config.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only allocate 1GB of memory on the first GPU
  try:
    tf.config.set_logical_device_configuration(
        gpus[0],
        [tf.config.LogicalDeviceConfiguration(memory_limit=1024)])
    logical_gpus = tf.config.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e)
```

**Comment by awsilya** [comment]
@paaksing could you give us an example of what you are trying to accomplish?  Let's say you have one process that uses one core and it starts loading models on this core.  At some point the total models' footprint exceeds 2GB.  With the current design this core will start taking memory from other cores.

Is that last step (taking other NC's memory) that you'd like to prevent?  What behavior would you expect instead?

**Comment by paaksing** [comment]
@awsilya I am trying to accomplish a way to load and unload models on-demand, for example:
modelA is called, it's loaded and stays loaded for a short period of time to receive more inference calls, modelB is called later, and it does the same thing, uploaded models have unknown memory footprint, I want to limit the amount of memory a model can take on the neuron device based on what the source claims to be fit (e.g. source claims 200MB is good, I make sure it doesn't take more than 200MB in memory).

There are many options I am considering:
- Load models, switch to next instance if memoryError, this is fine if I have a low amount of instances, but gets super bad with larger instance count.
- Try to infer the memory requirement of a model before accepting it (e.g. loading it once on a dummy instance and read the metric), I am unsure if model's memory footprint is always stable (doesn't change), but so far all the models I have used, memory footprint has been stable.

**Comment by paaksing** [comment]
@awsilya I guess limiting memory usage per model won't be a feature in the near future, but having a configuration that prevents memory borrowing between cores will give me a better way to work around this solution.

**Comment by awsilya** [comment]
@paaksing, thank you.  

To clarify one thing - model vs models, most models that run on inferentia take less than 2GB of device memory.  So if you intend to keep just one model loaded at any time, in the first approximation, it should just work.  If you plan to load multiple models up to 2GB limit and then selectively unload some of them to make room for more models, there are some subtleties around this that we can discuss separately.

But, each model requires certain amount of device memory, mostly for parameters and instructions and if that amount of memory is not available the model will not load.  E.g. if we were to add the feature you asked above, loading a model the requires >2GB will always fail.

**Comment by paaksing** [comment]
@awsilya Thanks a lot, those clarifications helps me build a work around, closing.

**Comment by JigaoLuo** [comment]
Hi @hannanjgaws 

I found this issue during my search. I'd like to inquire if this **caveat** documented that one NC can borrow memory from another NC: 
> However, there is one caveat: A NeuronCore will borrow memory from another NeuronCore when its own 2GB slice is used (assuming other NeuronCores still have free memory in their slices). There is no programmatic way to prevent this from happening

I'm currently working with the Trn1 device, and I'm curious if there are any differences in this regard compared to Inf1 you mentioned. I can also open a new issue. Thanks
