### ISSUE TITLE
`neuron_parallel_compile` fails but the original command line works

### ISSUE THREAD

**Issue by michaelbenayoun** [aws-neuron/aws-neuron-sdk#635]
While trying to perform precompilation for T5, I faced what appears to be a bug.

Running:

```bash
neuron_parallel_compile torchrun --nproc_per_node=2 /home/ec2-user/optimum-neuron/examples/translation/run_translation.py --model_name_or_path t5-small --dataset_name wmt16 --do_train --output_dir test_t5_translation --overwrite_output_dir true --learning_rate 0.0001 --per_device_train_batch_size 1 --per_device_eval_
batch_size 1 --gradient_accumulation_steps 16 --save_strategy epoch --num_train_epochs 1 --max_steps 200 --dataloader_num_workers 4 --save_steps -1 --save_total_limit 1 --logging_steps 1 --r
eport_to none --dataset_config ro-en --source_lang ro --target_lang en --pad_to_max_length --max_source_length 512 --max_target_length 512 --prediction_loss_only --source_prefix "translate English to Romanian:"
```

Gives:
```Traceback (most recent call last):
  File "/home/ec2-user/transformers/src/transformers/hf_argparser.py", line 341, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['English', 'to', 'Romanian:']
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['English', 'to', 'Romanian:']
```

While running the same command without `neuron_parallel_compile` works:

```bash
torchrun --nproc_per_node=2 /home/ec2-user/optimum-neuron/examples/translation/run_translation.py --model_name_or_path t5-small --dataset_name wmt16 --do_train --output_dir test_t5_translation --overwrite_output_dir true --learning_rate 0.0001 --per_device_train_batch_size 1 --per_device_eval_
batch_size 1 --gradient_accumulation_steps 16 --save_strategy epoch --num_train_epochs 1 --max_steps 200 --dataloader_num_workers 4 --save_steps -1 --save_total_limit 1 --logging_steps 1 --r
eport_to none --dataset_config ro-en --source_lang ro --target_lang en --pad_to_max_length --max_source_length 512 --max_target_length 512 --prediction_loss_only --source_prefix "translate English to Romanian:"
```

Although I did not investigate further, it seems to be a bug on the `neuron_parallel_compile` side, where it cannot handle multiple words arguments.

**Comment by jeffhataws** [comment]
Thanks for filing the issue. We have reproduced the problem and is working on a fix. For now, please create a `run.sh` script that contains your `torchrun` command (without neuron_parallel_compile), then run "neuron_parallel_compile ./run.sh" . This will preserve the quotations. Another workaround is to escape the quotations. However, using a `run.sh` script will enable you to use the same script for both the precompilation step and the actual execution. Furthermore, please make sure to disable DDP by adding a few lines to the top of `run_translation.py` as shown in https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/tutorials/training/finetune_hftrainer.html#multi-worker-training .

**Comment by michaelbenayoun** [comment]
Alright thanks for the quick reply.

Yes, I work on `optimum-neuron`, and I disable DDP the way suggested in the docs. 

Also note this DDP fix seems to not work when using gradient accumulation.
There is a call to `model.no_sync` when doing gradient accumulation, but with the fix `no_sync` does not exist...

My current fix is to do:

```python
model.no_sync = lambda: contextlib.nullcontext()
```

**Comment by jeffhataws** [comment]
Thanks @michaelbenayoun , it is a good find with gradient accumulation. We will take a look.

**Comment by mrnikwaws** [comment]
Hi @michaelbenayoun,

We made some progress on this problem in the recent 2.9.0 release (which should fix the gradient accumulation issue reported).  We are still working on changes so that 'escaping the quotations' is not needed.

**Comment by aws-taylor** [comment]
Hello @michaelbenayoun,

 A candidate fix for the escaped quotation issue is under code review. We will update this ticket once it is deployed.
 
 -Taylor

**Comment by aws-taylor** [comment]
Hello @michaelbenayoun,

 We have fixed the escaped quotation issue in our latest release - https://github.com/aws-neuron/aws-neuron-sdk/releases/tag/v2.16.0. 
 
 Resolving this issue, but don't hesitate to reach out if you have further questions or issues.
