### ISSUE TITLE
Issue on page /frameworks/torch/torch-neuronx/tutorials/training/bert.html

### ISSUE THREAD

**Issue by rsindreu** [aws-neuron/aws-neuron-sdk#637]
Where is the code referred on that page?

I cannot find this file anywhere:
dp_bert_large_hf_pretrain_hdf5.py

**Comment by jeffhataws** [comment]
Hi @rsindreu ,

Please see the [setup section](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/tutorials/training/bert.html#setting-up-the-training-environment-on-trn1-32xlarge) where it shows:

> 

> Next, download the Python-based training script dp_bert_large_hf_pretrain_hdf5.py and requirements.txt and install the requirements:
> 
> ```
> mkdir -p ~/examples/dp_bert_hf_pretrain
> cd ~/examples/dp_bert_hf_pretrain
> wget https://raw.githubusercontent.com/rwightman/pytorch-image-models/main/timm/optim/lamb.py .
> wget https://raw.githubusercontent.com/aws-neuron/aws-neuron-samples/master/torch-neuronx/training/dp_bert_hf_pretrain/dp_bert_large_hf_pretrain_hdf5.py
> wget https://raw.githubusercontent.com/aws-neuron/aws-neuron-samples/master/torch-neuronx/training/dp_bert_hf_pretrain/requirements.txt
> python3 -m pip install -r requirements.txt
> ```
