### ISSUE TITLE
Inferentia outperforms GPU on ResNet while showing worse performance on MobileNet

### ISSUE THREAD

**Issue by pEAceATLast53** [aws-neuron/aws-neuron-sdk#638]
I compared the throughput of Inferentia(inf1.xlarge) and NVIDIA T4 GPU(g4dn.xlarge) with MobileNetV2, ResNet50, ResNet101 and here are the results.

- Inferentia throughput (inferences / sec)
  - MobileNetV2 : 557
  - ResNet50 : 555
  - ResNet101 : 481

- T4 GPU throughput (inferences /sec)
  - MobileNetV2 : 718
  - ResNet50 : 314
  - ResNet101 : 175

We tested GPU on TensorFlow 2.3 models, and compiled the same models with tensorflow-neuron 2.3.4 to run on Inferentia. We compiled the models with Neuron batch size 4 and fast-math=none. When running the tests, each model occupied the entire device - for Inferentia a single model occupied all 4 NeuronCores. We spawned a separate process for each NeuronCore, resulting in 4 processes.

We found that while Inferentia showed similar performance for ResNet and MobileNetV2, the performance of GPU varied greatly depending on the model, ranging from 175 inferences per second for ResNet101 to 718 inferences per second for MobileNetV2. 

What could have caused Inferentia to outperform GPU by a large margin on ResNet, while underperforming on MobileNetV2?

**Comment by aws-donkrets** [comment]
There are many factors that contribute to a model's performance, including framework (TensorFlow vs PyTorch), compiler optiizations, deployment model, etc . Our goal is to deliver best price/performance for all models and ensuring the most popular models perform well on Inferentia. ResNet is one such model.  Check out our [ResNet-50 tutorial](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/tensorflow/keras_resnet50/keras_resnet50.html) for even higher ResNet-50 results. You can find other models and expected performance at this [link](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/benchmarks/inf1/index.html?highlight=performance#inf1-inference-performance).

Also, see the [Inferentia Performance Tuning guide](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/appnotes/perf/neuron-cc/performance-tuning.html?highlight=performance) for recommendations on how to further improve execution performance.

**Comment by aws-donkrets** [comment]
Hi [pEAceATLast53](https://github.com/pEAceATLast53)
Hope the information provided above is sufficient to answer your questions regarding the performance deltas you are seeing and the models that Inferentia best supports. If you have any other questions, please submit a new ticket.
