### ISSUE TITLE
neuronx-cc compilation incredibly slow due to only using single-thread/core

### ISSUE THREAD

**Issue by DanielRWhite** [aws-neuron/aws-neuron-sdk#646]
The neuronx-cc compiler is incredibly slow and takes ages to compile even small models (In this case I'm using [huggingface/pytorch-image-models](https://github.com/huggingface/pytorch-image-models) `maxvit_rmlp_pico_rw_256.sw_in1k` stock standard, no pretrained weights loaded).

I'm running it on a stock standard trn1.2xlarge instance on AWS and using a simple & working training script ([gist here](https://gist.github.com/DanielRWhite/72a3bd1ea19697927fe92c7e126c09b3)) via pytorch-lightning. It's odd that it's only using a single thread/core for compilation. Here's the screenshot of the resource usage when starting up `NEURON_CC_FLAGS='--model-type transformer --framework XLA' XLA_USE_BF16=1 python train.py --accelerator tpu --devices 2 [... rest of my training args here]`:
![image](https://user-images.githubusercontent.com/32739484/227759101-6d36e4cc-11b5-4a64-94ab-9e39087c76ff.png)

Are there any ways to make compilation faster? or any `NEURON_CC_FLAGS` that I can pass in to enable multi-thread/core compilation? Since the actual training for this model is only taking ~10-15 minutes whereas compilation takes >45 mins each time I change the model (e.g number of output classes). I couldn't find any flags on the docs site, or in the help command of neuronx-cc itself inside the venv, both of which give me the following info:
```
# Check that I'm using the same neuronx-cc instance that is in the image above
(aws_neuron_venv_pytorch) ubuntu@ip-<instance ip>:~$ which neuronx-cc
/opt/aws_neuron_venv_pytorch/bin/neuronx-cc

# Listed options for neuronx-cc, with neuronx-cc compile subcommand not giving any help screen
(aws_neuron_venv_pytorch) ubuntu@ip-<instance ip>:~$ neuronx-cc --help
usage: neuronx-cc [args] <subcommand> [<subcommand args>]

Run the AWS Neuron compiler.

The following subcommands are supported:
   compile         Compile a neural network model
   list-operators  List supported operators

See 'neuronx-cc <subcommand> --help' for more information about a
specific subcommand.

Optional arguments:
  --version, -V         Print version information and exit
  --help, -h            Show this help message and exit
  --verbose {debug|info|warning|error|critical}
                        Set logging level (default: warning)

****************************************************************
neuronx-cc: error: the following arguments are required: subcommand
```

`neuron_cc_wrapper` gives me this help output too, which doesn't differ from the docs:
```
(aws_neuron_venv_pytorch) ubuntu@ip-<instance ip>:~$ neuron_cc_wrapper --help
usage: neuron_cc_wrapper [-h] --framework FRAMEWORK [--stripped_input_file STRIPPED_INPUT_FILE] --output OUTPUT [--no_cache] [--cache_dir CACHE_DIR]
                         [--FAL FAL] [--cache_size CACHE_SIZE] [--cache_ttl CACHE_TTL] --cache_key CACHE_KEY [--log_level {INFO,ERROR,WARNING}]
                         [--retry_failed_compilation]
                         command input_file

positional arguments:
  command
  input_file

optional arguments:
  -h, --help            show this help message and exit
  --framework FRAMEWORK
  --stripped_input_file STRIPPED_INPUT_FILE
  --output OUTPUT
  --no_cache
  --cache_dir CACHE_DIR
                        Root cache dir. The cache will be stored at <cache_dir>/neuron-compilation-cache
  --FAL FAL             Deprecated: has no effect
  --cache_size CACHE_SIZE
  --cache_ttl CACHE_TTL
  --cache_key CACHE_KEY
  --log_level {INFO,ERROR,WARNING}
  --retry_failed_compilation
  ```

**Comment by DanielRWhite** [comment]
> [awsrjh](https://github.com/awsrjh) said: yes - compilation is slow in some cases - and this is something we are very specifically working on. Some passes in the compiler are in fact multithreaded, but some are not. There is not currently an external control for this.
> However- for cases like this - where compile time is high compared to execution time - have you tried the caching mechanism?

Yes, I'm using the cache, but it's still extremely slow, and for something that takes less than 20-30 mins to train for simple R&D testing, having to wait almost double to triple that time just waiting for it to start training is a bummer, especially when other training solutions with comparable performance cost more than 3-4x what Trn1 spot instance pricing is :(

> [aws-donkrets](https://github.com/aws-donkrets) said: Adding to [awsrjh's](https://github.com/awsrjh) suggestion, there is an experimental compiler flag that attempts to improve compilation time by using multi-process/multi-threading. It is described here:
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/compiler/neuronx-cc/index.html#id1

This is exactly what I was looking for, thank you!

Not sure if you are wanting to keep this issue open while the multi-threading feature is experimental (I've head of others talk about the long compile times too). I'm more than happy to report any future issues I encounter with it here, but if you want to close it to clear up the repo, feel free to 👍.

Thanks for the help :)

**Comment by aws-donkrets** [comment]
Hi [DanielRWhite](https://github.com/DanielRWhite),
Since this option is still experimental, could you share any results you see using it to compile your model?

**Comment by DanielRWhite** [comment]
> [aws-donkrets](https://github.com/aws-donkrets): Hi [DanielRWhite](https://github.com/DanielRWhite), Since this option is still experimental, could you share any results you see using it to compile your model?

Sure, more than happy to provide log files for training sessions that are done in my own free time.

What do you want me to include, just the log files or artifacts and everything? And where do you want me to upload them to? Happy to post them in this issue, but I feel like it would be off-topic slightly.

**Comment by aws-mvaria** [comment]
Closing this ticket as it appears that the issue was resolved as per customer update above.
