### ISSUE TITLE
Issue installing aws-neuronx-dkms on Ubuntu 22.04

### ISSUE THREAD

**Issue by IsaacRodgzb** [aws-neuron/aws-neuron-sdk#647]
I'm trying to get torch-neuron (Inf1) to run for model inference with some HuggingFace models. I launched an EC2 instance with Ubuntu 22.04.2 LTS (jammy) and kernel version 5.19.0-1022-aws. I went through the steps as described [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/quick-start/torch-neuron.html). But when running:

`sudo apt-get install aws-neuronx-dkms=2.* -y`

I get this log:

> Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
aws-neuronx-dkms is already the newest version (2.8.4.0).
Selected version '2.8.4.0' (Neuron:apt.repos.neuron.amazonaws.com [amd64]) for 'aws-neuronx-dkms'
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up aws-neuronx-dkms (2.8.4.0) ...
Removing old aws-neuronx-2.8.4.0 DKMS files...
Deleting module aws-neuronx-2.8.4.0 completely from the DKMS tree.
Loading new aws-neuronx-2.8.4.0 DKMS files...
Building for 5.19.0-1022-aws
Building for architecture x86_64
Building initial module for 5.19.0-1022-aws
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/aws-neuronx-dkms.0.crash'
Error! Bad return status for module build on kernel: 5.19.0-1022-aws (x86_64)
Consult /var/lib/dkms/aws-neuronx/2.8.4.0/build/make.log for more information.
dpkg: error processing package aws-neuronx-dkms (--configure):
 installed aws-neuronx-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 aws-neuronx-dkms
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)

Looking at the `cat /var/crash/aws-neuronx-dkms.0.crash` file I see this:

> ProblemType: Package
DKMSBuildLog:
 DKMS make.log for aws-neuronx-2.8.4.0 for kernel 5.19.0-1022-aws (x86_64)
 Fri Mar 31 22:14:50 UTC 2023
 make: Entering directory '/usr/src/linux-headers-5.19.0-1022-aws'
 warning: the compiler differs from the one used to build the kernel
   The kernel was built by: x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
   You are using:           gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_module.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_pci.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_mempool.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_dma.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_ring.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_ds.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_core.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_crwl.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_cdev.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_topsp.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_pid.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_reset.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_cinit.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_mmap.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_p2p.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_nq.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_metrics.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/neuron_sysfs_metrics.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.o
   CC [M]  /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_m2m.o
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c: In function ‘udma_iofic_m2s_error_ints_unmask’:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:250:9: error: array subscript 0 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   250 |         reg_write32(&regs->ctrl[group].int_control_grp, flags);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:250:9: error: array subscript 3 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   250 |         reg_write32(&regs->ctrl[group].int_control_grp, flags);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:276:9: error: array subscript 0 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   276 |         reg_write32(&regs->ctrl[group].int_abort_msk_grp, ~mask);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:276:9: error: array subscript 2 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   276 |         reg_write32(&regs->ctrl[group].int_abort_msk_grp, ~mask);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:262:9: error: array subscript 0 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   262 |         reg_write32(&regs->ctrl[group].int_mask_clear_grp, ~mask);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:262:9: error: array subscript 2 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   262 |         reg_write32(&regs->ctrl[group].int_mask_clear_grp, ~mask);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:262:9: error: array subscript 3 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   262 |         reg_write32(&regs->ctrl[group].int_mask_clear_grp, ~mask);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c: In function ‘udma_iofic_s2m_error_ints_unmask’:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:250:9: error: array subscript 1 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   250 |         reg_write32(&regs->ctrl[group].int_control_grp, flags);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:250:9: error: array subscript 3 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   250 |         reg_write32(&regs->ctrl[group].int_control_grp, flags);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:276:9: error: array subscript 1 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   276 |         reg_write32(&regs->ctrl[group].int_abort_msk_grp, ~mask);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:276:9: error: array subscript 2 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   276 |         reg_write32(&regs->ctrl[group].int_abort_msk_grp, ~mask);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:262:9: error: array subscript 1 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   262 |         reg_write32(&regs->ctrl[group].int_mask_clear_grp, ~mask);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:262:9: error: array subscript 2 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   262 |         reg_write32(&regs->ctrl[group].int_mask_clear_grp, ~mask);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:262:9: error: array subscript 3 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]
   262 |         reg_write32(&regs->ctrl[group].int_mask_clear_grp, ~mask);
       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma.h:10,
                  from /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:11:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_regs.h:449:31: note: while referencing ‘ctrl’
   449 |         struct iofic_grp_ctrl ctrl[0];
       |                               ^~~~
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c: In function ‘udma_iofic_error_ints_unmask_one’:
 /var/lib/dkms/aws-neuronx/2.8.4.0/build/udma/udma_iofic.c:250:9: error: array subscript 0 is outside the bounds of an interior zero-length array ‘struct iofic_grp_ctrl[0]’ [-Werror=zero-length-bounds]

Which specifies there's a missmatch on the gcc version. Is this issue caused by the newer kernel version? I was able to install aws-neuron-dkms and successfully deploy models for inference on a previous kernel version (5.15.0-1031-aws, also Ubuntu 22.04). So I'm guessing it's related to kernel version.

Btw I'm using python3.7.

Do you have any thoughts on this?

I appreciate any help, thanks.

**Comment by aws-taylor** [comment]
Hello @IsaacRodgzb,

 Can you let me know the exact AMI ID, instance type, and region that you were using? This will help me reproduce the issue.

**Comment by micwade-aws** [comment]
Neuron SDK does not support Ubuntu 22 yet. We'll release support soon.

**Comment by jyang-aws** [comment]
Closing as it's a duplicate issue as https://github.com/aws-neuron/aws-neuron-sdk/issues/649.
Will track the release support for Ubuntu 22 in that thread.
