### ISSUE TITLE
Unused memory on Inf1

### ISSUE THREAD

**Issue by RobinFrcd** [aws-neuron/aws-neuron-sdk#648]
Hi,
I had some models compiled with `neuron-cc==1.13.5.0+7dcf000a6`  and I recently updated to `neuron-cc==1.14.3.0+adaa2ac56`.
The models (YOLOv5) are running well and using neuron's compute power, but I realized they don't use their memory anymore.

Here's the usage with neuron-cc 1.13:
![image](https://user-images.githubusercontent.com/29704178/230496042-8b40a50a-f998-438e-ae30-43c40786f436.png)

And with neuron-cc 1.14:
![image](https://user-images.githubusercontent.com/29704178/230495611-86d176ae-470f-4727-b5f4-0e06eddd9db3.png)

Only a few KBs in the second case seems really low. Processes use ~1GB of CPU RAM  though.

Is it normal that neuron's memory is not used or I missed something during the update ?

Thanks

**Comment by aws-taylor** [comment]
Hello @RobinFrcd,

 There were several memory related improvements between our 1.13 and 1.14 releases - https://awsdocs-neuron.readthedocs-hosted.com/en/v1.16.1/release-notes/README.html#id2. 
 
 Are you seeing adverse impacts to latency/performance?

**Comment by aws-taylor** [comment]
Hello @RobinFrcd,

  This behavior is expected - as part of the aforementioned changes, we adjusted how we allocate memory on the device and host, with the net result that host memory usage is much lower.
  
  -T

**Comment by RobinFrcd** [comment]
Indeed, the device memory usage is much lower with this version !
I'll investigate further performances on my end, and I'll re-open an issue if I identify something.

Thanks again,
