### ISSUE TITLE
Unable to Add Neuron Apt Repo on Ubuntu 22.04

### ISSUE THREAD

**Issue by xanderdunn** [aws-neuron/aws-neuron-sdk#649]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
$ uname -r
5.15.0-1031-aws
```
This is a fresh, unused base Ubuntu 22.04 image on a `trn1.2xlarge` instance.

Running this script from [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/quick-start/torch-neuron.html):
```bash
#!/bin/bash

set -e

# Configure Linux for Neuron repository updates
. /etc/os-release
sudo tee /etc/apt/sources.list.d/neuron.list > /dev/null <<EOF
deb https://apt.repos.neuron.amazonaws.com ${VERSION_CODENAME} main
EOF
cat /etc/apt/sources.list.d/neuron.list
wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB | sudo apt-key add -

# Update OS packages
sudo apt-get update -y

# Install OS headers
sudo apt-get install linux-headers-$(uname -r) -y
```

Fails here:
```
$ ./install_neuron.sh
deb https://apt.repos.neuron.amazonaws.com jammy main
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:5 https://apt.repos.neuron.amazonaws.com jammy InRelease
Err:6 https://apt.repos.neuron.amazonaws.com jammy Release
  404  Not Found [IP: 18.161.6.62 443]
Reading package lists... Done
E: The repository 'https://apt.repos.neuron.amazonaws.com jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
It seems that the repo `https://apt.repos.neuron.amazonaws.com` at IP `18.161.6.106` is returning `404` not found.

When I go to https://apt.repos.neuron.amazonaws.com in my browser I see only an error:
<img width="1484" alt="Screenshot 2023-04-06 at 17 25 04" src="https://user-images.githubusercontent.com/1313618/230496858-193f0123-e65f-4fe9-87f1-178d01fac51a.png">
Is this expected? Other apt repos like http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ display a file explorer.

**Comment by xanderdunn** [comment]
I wasn't able to get the Ubuntu 22.04 image working with a Neuron install, but switching to the `Deep Learning Base Neuron AMI (Ubuntu 20.04)` AMI worked.

**Comment by jsleight** [comment]
I also experienced this and was able to resolve this specific error by doing
```
deb [trusted=yes] https://apt.repos.neuron.amazonaws.com ${VERSION_CODENAME} main
```
while setting up the `/etc/apt/sources.list.d/neuron.list` file.

However this just led to another issue where the apt repo returned a 404 for jammy.  So I think the apt repo needs to be updated to support jammy still.

**Comment by micwade-aws** [comment]
Neuron SDK does not support Ubuntu 22 yet. We'll release support for it in the near future.

**Comment by xanderdunn** [comment]
It looks like the [Neuron 2.11 release notes](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#latest-neuron-release) indicate Ubuntu 22 is supported now. In addition, we're using the AWS provided Neuron AMIs rather than attempting to install this ourselves. We'll upgrade to Ubuntu 22 when the AWS Neuron AMI is on Ubuntu 22 in the future.

**Comment by ZohaibDurrani** [comment]
Try this:

`wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB | sudo apt-key add - `
`sudo apt-get update -y`
