### ISSUE TITLE
Inconsistent output with EfficientNet in TF 2.x (inf1)

### ISSUE THREAD

**Issue by Askannz** [aws-neuron/aws-neuron-sdk#651]
We have a Tensorflow model based on the EfficientNet architecture which is deployed on an Inferentia instance (inf1). While investigating strange prediction errors, we found that the model can produce inconsistent values across multiple invocations, even with the same input tensor.

Here's an example that sends the same zero tensor over and over and compares the outputs to the first invocation:

```python
from pathlib import Path
import numpy as np
import tensorflow as tf
import tensorflow.neuron as tfn
import tensorflow.keras.layers as layers
from tensorflow.keras.models import Model
from tensorflow.keras import Input
from tensorflow.keras.applications import EfficientNetV2B3

_SHAPE = (224, 224, 3)

def main():

    out_model_path = _compile()

    model = tf.keras.models.load_model(str(out_model_path))

    inp_arr = np.zeros((1, *_SHAPE), dtype=np.float32)
    ref_output = model({"input_1": inp_arr})
    ref_output = np.array(ref_output)

    counter_total = 0
    counter_disc = 0
    while True:
        new_output = model({"input_1": inp_arr})
        new_output = np.array(new_output)
        if not (new_output == ref_output).all():
            print("\nDiscrepancy!")
            print(f"output={new_output}")
            print(f"reference={ref_output}")
            print(f"{counter_disc} discrepancies out of {counter_total} invocations")
            counter_disc += 1
        counter_total += 1


def _compile():

    model = _build_model(n_classes=3, inp_shape=_SHAPE, weights='imagenet')

    example_inputs = {
        "input_1": np.zeros((1, *_SHAPE), np.float32)
    }

    model_neuron = tfn.trace(model, example_inputs)

    out_model_path = Path("compiled")
    model_neuron.save(str(out_model_path))

    return out_model_path



def _build_model(n_classes, inp_shape, weights):

    inp = Input(shape=inp_shape)

    base_model = EfficientNetV2B3(
        weights=weights,
        include_top=False,
        input_shape=inp_shape,
        include_preprocessing=False
    )

    x = base_model(inp)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Activation('relu')(x)
    predictions = layers.Dense(n_classes)(x)
    model = Model(inp, predictions)

    return model


if __name__ == "__main__":
    main()
```

```
Output:
...
Discrepancy!
output=[[ 0.6069465   0.07179423 -0.9515301 ]]
reference=[[-0.02997065  0.02261192  0.05591967]]
12 discrepancies out of 188 invocations

Discrepancy!
output=[[ 0.60498667  0.06978561 -0.95127857]]
reference=[[-0.02997065  0.02261192  0.05591967]]
13 discrepancies out of 194 invocations
...
```
I's worth pointing out again that even though this toy example uses a model with random weights, we've observed a similar issue with a production model trained on real data. That model sometimes produces spurious classifications and confidence values, which disappear when running the prediction again with the same inputs.

Also, the inconsistency disappears when swapping EfficientNet for another backbone, such as ResNet50.

This is reproducible on a `inf1.xlarge` instance running Ubuntu 20.04, with the following environment. We've tried several version of `tensorflow-neuron` and the kernel module and all of them had the issue, though the frequency of discrepancies seemed to vary.

* APT package `aws-neuronx-dkms=2.8.4.0` 
* `tensorflow==2.8.4`
* `tensorflow-neuron==2.8.4.2.7.3.0`
* `neuron-cc==1.14.3.0+adaa2ac56`

**Comment by aws-mvaria** [comment]
Thanks, we are trying to reproduce the issue and will let you know when we have more information.

**Comment by awsilya** [comment]
The Neuron compiler contains multiple tensor allocation strategies which result in different performance characteristics for different model types. By default, the compiler uses a graph coloring algorithm which, in most cases, results in the best performance across multiple model types. This EfficientNet model seems to have tweaked a bug in this allocation algorithm. The suggested flag tells the compiler to use one of its alternate algorithms.

**Comment by Askannz** [comment]
@awsilya thanks for the explanation.

Just to mention it here, the flag that fixed the issue is `--allocator lsa`, applied to the Neuron compiler (`NEURON_CC_FLAGS="--allocator lsa"`).
