### ISSUE TITLE
How to run neuron model in ECS using Inf1 EC2 instances

### ISSUE THREAD

**Issue by YuryShchanouskiTR** [aws-neuron/aws-neuron-sdk#652]
Hi Team,

Writing here since tried a bunch of options, but still no success with the running of our BERT model on Inf1 instances.
Documentation is too misleading f.i. here: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/guide-torch-neuron-vs-torch-neuronx-inference.html

What do we need to install on Inf1.xlarge EC2 instance and inside of a docker container?

We installed neuronX on a dev Inf1.xlarge EC2 instance, compiled model and run it there - neuron-top shows it on Inferentia chips, but from the inside of a Docker container it shows nothing.

But as for ECS - still no results:
device /dev/neuron0 option is specified
IPC_LOCK capability is provided
env vars are present for each containers:
NEURON_RT_VISIBLE_CORES=0-1 and NEURON_RT_VISIBLE_CORES=2-3

### Current EC2 configuration:
Inf1.xlarge EC2 instance  with Amazon Linux 2 AMI for ECS with updated kernel to version 5.10, installed:
kernel-headers-5.10.176-157.645.amzn2.x86_64
kernel-5.10.176-157.645.amzn2.x86_64
kernel-devel-5.10.176-157.645.amzn2.x86_64
aws-neuronx-runtime-lib-2.12.16.0_8e42c5019-1.x86_64
aws-neuronx-dkms-2.8.4.0
pciutils

### Container contents:
`FROM public.ecr.aws/amazonlinux/amazonlinux:2   #Used such base image, tried Python-3.7.16, ubuntu18, amazonlinux2023

ENV PATH="$PATH:/opt/aws/neuron/bin"

RUN echo $'[neuron] \n\
name=Neuron YUM Repository \n\
baseurl=https://yum.repos.neuron.amazonaws.com \n\
enabled=1 \n\
metadata_expire=0 \n'\
>> /etc/yum.repos.d/neuron.repo

RUN    rpm --import https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB \
    && yum install gcc-c++ openssl-devel bzip2-devel libffi-devel wget tar gzip zlib-devel xz-devel **aws-neuronx-tools aws-neuronx-runtime-lib** -y

RUN    wget -q https://www.python.org/ftp/python/3.7.16/Python-3.7.16.tgz \
    && tar xzf Python-3.7.16.tgz -C /opt/ \
    && rm -rf Python-3.7.16.tgz \
    && cd /opt/Python-3.7.16/ \
    && ./configure --enable-optimizations \
    && make altinstall \
    && cd .. && rm -rf /opt/Python-3.7.16 \
    && update-alternatives --install /usr/bin/python python /usr/local/bin/python3.7 1 \
    && update-alternatives --install /usr/bin/pip pip /usr/local/bin/pip3.7 1 \
    && python -m pip install --upgrade pip --no-cache-dir \
    && pip install torch-neuron transformers --extra-index-url=https://pip.repos.neuron.amazonaws.com --no-cache-dir \
    && pip uninstall -y nvidia-cublas-cu11 nvidia-cuda-nvrtc-cu11 nvidia-cuda-runtime-cu11 nvidia-cudnn-cu11`

**Comment by awsrjh** [comment]
Hi. 

On Inf1 currently only torch-neuron is supported. Not torch-neuronx

Apologies if the docs are not clear.

**Comment by YuryShchanouskiTR** [comment]
> Hi.
> 
> On Inf1 currently only torch-neuron is supported. Not torch-neuronx
> 
> Apologies if the docs are not clear.

1. Okay, we will use neuron for drivers, is kernel update to v5.10 required?

2. What is required inside of container:
 aws-neuron-runtime-base aws-neuron-runtime aws-neuron-tools ?

3. What has to be installed on Inf1 EC2: only aws-neuron-dkms?

4. But in your release notes for Inf1 almost everywhere neuronX: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/releasecontent.html#inf1-packages - how is it possible?

**Comment by YuryShchanouskiTR** [comment]
> Hi @YuryShchanouskiTR ,
> 
> 1. Okay, we will use neuron for drivers, is kernel update to v5.10 required?
>    Updating to the latest kernel version for your OS of choice is always recommended, but it is not required for Neuron workloads.
> 2. What is required inside of container: aws-neuron-runtime-base aws-neuron-runtime aws-neuron-tools ?
>    Inside the container you'd need torch-neuron-1.13.1.2.6.5.0, aws-neuronx-tools-2.9.5.0
> 3. What has to be installed on Inf1 EC2: only aws-neuron-dkms?
>    Yes, aws-neuronx-dkms-2.8.4.0
> 4. Can I remove nvidia pypi packages or they are also required for the Inf1 run?
>    Yes, they are not needed
> 5. But in your release notes for Inf1 almost everywhere neuronX: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/releasecontent.html#inf1-packages - how is it possible?
>    aws-neuronx-tools, aws-neuronx-runtime-lib and aws-neuronx-dkms are compatible with inf1, the frameworks (torch-neuronx, for example) are not, and are separate packages
> 
> Let us know if this answers your questions - and whether any assistance is needed on your original issue. If further assistance is needed on your original issue, would you be able to clarify the problem? i.e. Were you able to run everything outside of a container and it worked as expected, but when moving everything inside the container, it did not?
> 
> Thank you!

Thanks a lot for your answers, so the documentation for neuron on Inf1 has to be improved from my point of view :)

1. As for the previous solution:
We used dummy container with Linux capabilities as IPC_LOCK and others. That was for torch-neuron 1.7 and everything works fine. Base image of a container with Bert model was built on CentOS7

2. The current solution uses torch-neuron 1.13 and neuron-top shows no models are running on inf cores :(
And as I could understand from documentation there is no necessity to use dummy container to access neuron device from container.
For base image of our container I tried to use base images from public.ecr.aws:
python3.7.16
ubuntu18.04
amazonlinux:2
amazonlinux:2023

3. but still no success... Any suggestions regarding base image?

4. Do I need to install yum install -y kernel-devel-$(uname -r) kernel-headers-$(uname -r)" inside of a container?

**Comment by YuryShchanouskiTR** [comment]
Hi @aws-mvaria , @awsrjh ! Any updates?

**Comment by jsleight** [comment]
I've also been trying to decipher all the dependencies and have to +1 that the docs could be clearer about which packages you need for which instance types.

> aws-neuronx-tools, aws-neuronx-runtime-lib and aws-neuronx-dkms are compatible with inf1, the frameworks (torch-neuronx, for example) are not, and are separate packages
Thanks for this point, clears up a lot of my confusion about why torch-neuronx wasn't working.

**Comment by jsleight** [comment]
I have learned that my errors were self-inflicted and centered around cxx11 ABI incompatibilities.  Filed #654 for better linking the relevant docs to the troubleshooting guide

**Comment by awsrjh** [comment]
thanks @jsleight ... very much appreciate the update. 

We will add the info you suggested to our troubleshooting guide.

I think we also need to help our other container docs to be more clear as you say .

Can we close this issue here and leave #654 open to track when we add the troubleshooting info?

**Comment by jsleight** [comment]
I think @YuryShchanouskiTR might be having different problems from what I experienced.  So I defer to them.

**Comment by shebbur-aws** [comment]
@YuryShchanouskiTR : Responding to your earlier questions : 

1. Do I need to install yum install -y kernel-devel-$(uname -r) kernel-headers-$(uname -r)" inside of a container?
----> Not needed in container, this should be done on host along with aws-neuronx-dkms, the driver package

2.  And as I could understand from documentation there is no necessity to use dummy container to access neuron device from container.
For base image of our container I tried to use base images from public.ecr.aws:
python3.7.16
ubuntu18.04
amazonlinux:2
amazonlinux:2023
---> this looks fine. Please make sure you install the Neuron packages in the dockerfile.  We also have DLC images that are mentioned in [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/containers/index.html). You might also find [this reference](https://github.com/aws/deep-learning-containers/blob/master/pytorch/inference/docker/1.12/py3/sdk2.5.0/Dockerfile.neuron) for torch-neuron 1.12 helpful.

Thanks.

**Comment by YuryShchanouskiTR** [comment]
Thanks a lot for the answers. Finally we managed to run our model on Inf chips properly - issue was with proper BERT configuration file.

However, it is impossible to avoid of Nvidia packages, because of spacy usage :( couple of unnecessary GBs to a docker image :(

Closing this thread.
