### ISSUE TITLE
Error while installing aws-neuron-dkms 2.x

### ISSUE THREAD

**Issue by Mihir-Gajera1** [aws-neuron/aws-neuron-sdk#661]
neuron:
Running module version sanity check.

Running the pre_install script:
Error! pre_install failed, aborting install.
You may override by specifying --force.
dpkg: error processing package aws-neuron-dkms (--configure):
 installed aws-neuron-dkms package post-installation script subprocess returned error exit status 101
Setting up build-essential (12.4ubuntu1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.6) ...
Errors were encountered while processing:
 aws-neuron-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get install aws-neuron-dkms=2.2.14.0 -y' returned a non-zero code: 100

**Comment by micwade-aws** [comment]
Please use the aws-neuronx-dkms package instead of the aws-neuron-dkms package.  We stopped producing the sans 'x' package -- the neuron**x** version supports all instance types.

Don't forget to remove the old one if it's installed before attempting install of the new one.

If you still are hitting an error, let me know which version of the OS you're using and the specific install command you're running.  I'll try to reproduce it or suggest a fix.

**Comment by Mihir-Gajera1** [comment]
Thanks a lot for the help.  Pre install and post install is still failing but package installed successfully. I will load the model using image that I have built and update here if it works.

I am following this https://awsdocs-neuron.readthedocs-hosted.com/en/v1.19.2/neuron-intro/pytorch-setup/pytorch-install.html


Os version : Ubuntu 18.04

```Setting up aws-neuronx-dkms (2.8.4.0) ...
Loading new aws-neuronx-2.8.4.0 DKMS files...
It is likely that 5.4.0-126-generic belongs to a chroot's host
Building for 5.4.0-126-generic
Building for architecture x86_64
Building initial module for 5.4.0-126-generic
Done.

neuron:
Running module version sanity check.

Running the pre_install script:
/var/lib/dkms/aws-neuronx/2.8.4.0/source/./preinstall: line 3: update-pciids: command not found
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.0-126-generic/updates/dkms/

Running the post_install script:
tee: /etc/modules-load.d/neuron.conf: No such file or directory
neuron

depmod...

DKMS: install completed.```

**Comment by micwade-aws** [comment]
Double check the kernel module is loaded by running the modinfo command I posted earlier. As long as that's giving the expected output, the driver should be running and compatible with all versions of Neuron Runtime.

**Comment by Mihir-Gajera1** [comment]
# lsmod | grep neuron
neuron                212992  4
Thanks, everything seems to be working fine. except neuron-cli command is not working. getting context deadline exceeded. neuron-top, neuron-monitor all are working fine and model are loaded on neuron device.

**Comment by micwade-aws** [comment]
Sounds like you're running very old Neuron Tools software. Similar advice to earlier though, remove aws-neuron-tools and install aws-neuronx-tools. 

More detailed installation and update instructions are documented here: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/index.html#setup-guide-index

**Comment by Mihir-Gajera1** [comment]
Thanks for the help. Closing the issue.
