### ISSUE TITLE
neuronx-cc Compilation Time is a Function of Input Size / (16000, 16000) Square Matrices Fail Compilation

### ISSUE THREAD

**Issue by xanderdunn** [aws-neuron/aws-neuron-sdk#663]
I am testing the compilation and run of a simple XLA graph that does a matmul on two matrices and then computes their gradient (two additional matmuls with an additional gradient matrix):
```
rust debug_ir: HloModule xla_computation_ordered_wrapper, entry_computation_layout={(f32[16000,16000]{1,0},f32[16000,16000]{1,0},f32[16000,16000]{1,0})->(f32[16000,16000]{0,1}, f32[16000,16000]{0,1}, f32[16000,16000]{0,1})}

ENTRY main.11 {
  Arg_0.1 = f32[16000,16000]{1,0} parameter(0)
  Arg_1.2 = f32[16000,16000]{1,0} parameter(1)
  dot.4 = f32[16000,16000]{0,1} dot(Arg_0.1, Arg_1.2), lhs_contracting_dims={1}, rhs_contracting_dims={0}
  Arg_2.3 = f32[16000,16000]{1,0} parameter(2)
  transpose.5 = f32[16000,16000]{0,1} transpose(Arg_1.2), dimensions={1,0}
  dot.6 = f32[16000,16000]{0,1} dot(Arg_2.3, transpose.5), lhs_contracting_dims={1}, rhs_contracting_dims={0}
  transpose.7 = f32[16000,16000]{0,1} transpose(Arg_0.1), dimensions={1,0}
  dot.8 = f32[16000,16000]{0,1} dot(transpose.7, Arg_2.3), lhs_contracting_dims={1}, rhs_contracting_dims={0}
  ROOT tuple.9 = (f32[16000,16000]{0,1}, f32[16000,16000]{0,1}, f32[16000,16000]{0,1}) tuple(dot.4, dot.6, dot.8)
}
```

This is:
```python
out = torch.matmul(x, y)
out.backward(gradient)
```
Where `x`, `y`, and `gradient` are randomly generated values. Here is an example .pb XLA HLO graph: 
[rust_hlo_large_mm.pb.zip](https://github.com/aws-neuron/aws-neuron-sdk/files/11360059/rust_hlo_large_mm.pb.zip)

When the inputs are shape (4608, 4608) x (4608, 4608) == 21M output elements, I find that it takes 42 seconds to compile the NEFF and it runs successfully. 
When the inputs are shape (512, 4608) x (4608, 50255) == 26M output elements, I find that it takes 166 seconds to compile the NEFF and it runs successfully.
When the inputs are shape (16000, 16000) x (16000, 16000) == 256M output elements,  I find that after 11.3 hours of execution neuronx-cc fails with no output other than this warning:
```
thread 'tensor::ops::tests::large_matmul' panicked at 'Script failed:
2023-04-29T01:54:51Z WARNING 1503585 [SB_Allocator]: accumulation group is too large for SB
```

For our immediate future we will be training models with `(d_model, d_model)` where `d_model < 16000`, but we will eventually require `d_model` to be `16,000` to train sufficiently large Transformers.

```
$ neuronx-cc --version
NeuronX Compiler version 2.5.0.28+1be23f232

HWM version 2.5.0.0-dad732dd6
NEFF version Dynamic
TVM not available
NumPy version 1.21.6
MXNet not available
```

I am running `neuronx-cc compile /tmp/rust_hlo_large_mm.pb --framework XLA --target trn1 --model-type transformer --auto-cast none --output /tmp/large_mm.neff`

I'm running this on a trn1.2xlarge machine.

**Comment by aws-diamant** [comment]
hey @xanderdunn !

thanks for reporting this.
we're aware of this issue, and have a local fix for it.

we'll test with your configuration above as well, to make sure our fix indeed solves this issue, and release soon.
if useful, we can coordinate a private build, for you to experiment with our fix asap.

we'll keep you posted.
/Ron

**Comment by xanderdunn** [comment]
That's great to hear, thanks! 

Here's a sample XLA HLO graph doing the (16000, 16000) square matrices matmuls. If this compiles to NEFF in your testing, then this problem should be solved: [rust_hlo_large_mm.pb.zip](https://github.com/aws-neuron/aws-neuron-sdk/files/11360062/rust_hlo_large_mm.pb.zip)

If you need any additional testing, I'm happy to try either before or after release.

**Comment by aws-diamant** [comment]
Perfect, thanks!
We’ll run it.

**Comment by aws-diamant** [comment]
tested this one locally.
it is fixed for fp16/bf16, but not for float32 yet.  we'll work to fix float32 as well, and update you as soon as we have it ready.

**Comment by xanderdunn** [comment]
I updated to Neuron SDK 2.11 and I can confirm that the above matmul graph successfully compiles with auto casting of the matmuls:
```
neuronx-cc compile /tmp/rust_hlo_large_mm.pb --framework XLA --target trn1 --model-type transformer --auto-cast matmult --output /tmp/large_mm_17578805963965427482.neff
```
in 43minutes. 

It also successfully compiled with no matmul casting, but took considerably longer.

These were run on a trn1.32xlarge instance. 

In practice we'll perform these matmuls below f32 precision. 43min is still quite long for a graph with two matmuls, but it's tractable for now.

**Comment by xanderdunn** [comment]
@aws-donkrets Thanks very much for the info, I will give it a try!
