### ISSUE TITLE
Clarification on neuron tracing support on seq-to-seq model

### ISSUE THREAD

**Issue by ndenStanford** [aws-neuron/aws-neuron-sdk#671]
Hello, 

I have a question on the seq-to-seq model tracing in this [tutorial](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/transformers-marianmt.html). The example shows how to trace the model using torch_neuron, which is AWS Inferentia (NeuronCore v1) I believe. However, the [guideline](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/model-architecture-fit.html) states that AWS Inferentia (NeuronCore v1) does not support Transformer Decoders tracing. However, the AWS Trainium and AWS Inferentia2 (NeuronCore-v2) support the tracing. Should the tutorial have used torch_neuronx instead? 

Would appreciate any clarification on this matter. Thank you!

**Comment by awsilya** [comment]
Hi @ndenStanford,

The MarianMT Tutorial is for torch-neuron on inf1 to enable functionality.  As you mentioned seq2seq models are not a good fit for Inf1 which means it will not be performant.
For torch-neuronx, we are intending to add the support for seq2seq trace  in the coming releases.
