### ISSUE TITLE
Inferentia pod with sidecar can't start with 'UnexpectedAdmissionError' error.

### ISSUE THREAD

**Issue by everpeace** [aws-neuron/aws-neuron-sdk#675]
Hi, I have an EKS cluster (kubernetes version 1.22) with Inferentia(inf1.2xlarge) node.

When I created a pod with single container which requests `aws.amazon.com/neuron` device, it looks good, works as expected. However, when creating a pod with multiple coatainers (one is neuron container, the other is not), the pod can't start up with `UnexpectedAdmissionError`.

Could anybody give some insight what's going on here and how to dig more?? Thanks,

## Good for pod with single neuron container

When I created a pod with single container which requests `aws.amazon.com/neuron` device, it looks good, works as expected.

```shell
$ cat << EOT | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: neuron-test-single
spec:
  tolerations:
  - key: aws.amazon.com/neuron
    operator: Exists
  containers:
  - image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    name: neuron-test
    command: ["ls", "-al", "/dev/neuron0"]
    resources:
      limits:
        aws.amazon.com/neuron: "1"
EOT

pod/neuron-test-single created

#
# Yay! pod can have neuron device!!
#
$ kubectl logs neuron-test-single          
crw-rw-rw- 1 root root 248, 0 May 10 07:23 /dev/neuron0
```

## 'UnexpectedAdmissionError' in pod with multi containers

However, when creating a pod with multiple container(one is neuron container, the other is not), the pod can't start with `UnexpectedAdmissionError` as below.

```shell
cat << EOT | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: neuron-test-multi
spec:
  tolerations:
  - key: aws.amazon.com/neuron
    operator: Exists
  containers:
  - image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    name: neuron-test
    command: ["ls", "-al", "/dev/neuron0"]
    resources:
      limits:
        aws.amazon.com/neuron: "1"
  #
  # sidecar container requests No neuron devices
  #
  - image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    name: sidecar
    command: ["sleep", "65535"]
EOT

pod/neuron-test-multi created

$ kubectl describe pod neuron-test-multi
Name:         neuron-test-multi
Namespace:    default
...
Status:       Failed
Reason:       UnexpectedAdmissionError
Message:      Pod Allocate failed due to rpc error: code = Unknown desc = failed to find a Pod that matches the req core/device cnt: 1, which is unexpected
...
Events:
  Type     Reason                    Age   From               Message
  ----     ------                    ----  ----               -------
  Normal   Scheduled                 71s   default-scheduler  Successfully assigned default/neuron-test-multi to ip-10-30-13-38.ec2.internal
  Warning  UnexpectedAdmissionError  71s   kubelet            Allocate failed due to rpc error: code = Unknown desc = failed to find a Pod that matches the req core/device cnt: 1, which is unexpected
```

### Logs of neuron-device-plugin-daemonset

neuron device plugin log says `Pod neuron-test-multi in namespace default does not have resource aws.amazon.com/neuroncore or aws.amazon.com/neurondevice or aws.amazon.com/neuron.`.... It looks a kind of bug because Pod `neuron-test-multi` apparently have the neuron resource.

```shell
$ stern -n kube-system neuron-device-plugin-daemonset
...
neuron-device-plugin-daemonset-z8z9p k8s-neuron-device-plugin-ctr neuron-device-plugin: 2023/05/10 07:26:00 Pod neuron-test-multi in namespace default does not have resource aws.amazon.com/neuroncore or aws.amazon.com/neurondevice or aws.amazon.com/neuron.
neuron-device-plugin-daemonset-z8z9p k8s-neuron-device-plugin-ctr neuron-device-plugin: 2023/05/10 07:26:00 list pod neuron-test-multi in ns default in node ____MASKED____ and status is Pending
neuron-device-plugin-daemonset-z8z9p k8s-neuron-device-plugin-ctr neuron-device-plugin: 2023/05/10 07:26:00 Pod neuron-test-multi in namespace default does not have resource aws.amazon.com/neuroncore or aws.amazon.com/neurondevice or aws.amazon.com/neuron.
```

**Comment by jluntamazon** [comment]
Hi @everpeace, 
We are looking to reproduce this issue now. We will look for a solution and let you know what we find

**Comment by james-aws** [comment]
Hi @everpeace
The solution is to specify the neuron resource limits for every container in the pod, even if the container doesn't use neuron resources. Here is an example yaml that should work
```
apiVersion: v1
kind: Pod
metadata:
  name: neuron-test-multi
spec:
  tolerations:
  - key: aws.amazon.com/neuron
    operator: Exists
  containers:
  - image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    name: neuron-test
    command: ["ls", "-al", "/dev/neuron0"]
    resources:
      limits:
        aws.amazon.com/neuron: "1"
  #
  # sidecar container requests No neuron devices
  #
  - image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    name: sidecar
    command: ["sleep", "65535"]
    resources:
      limits:
        aws.amazon.com/neuron: "0"

**Comment by everpeace** [comment]
@jluntamazon @james-aws Thanks for the workaround. It worked!

By the way, would you have any plan to fix this in the device plugin??

Actually, we tried to run Kubeflow Notebooks with Inferentia. As you might know, [Kubeflow depends on Istio](https://www.kubeflow.org/docs/external-add-ons/istio/istio-in-kubeflow/#istio-in-kubeflow). The problem sidecar was actually injected by istio. So, normal users can not specify such empty resource limits(`aws.amazon.com/neuron: "0"`) in Kubeflow Notebooks(both in central dashboard(webui) and `Notebook` CRD).

Thus, injecting empty resource limits would be ok for a workaround(we will use admission webhook for this). But, I believe that the problem should be fixed in the upstream. So, I would be happy if the upstream have a plan to fix this.

**Comment by jluntamazon** [comment]
> By the way, would you have any plan to fix this in the device plugin??

Yes, in the longer term we are looking into a way to fix the device plugin so this is permanently resolved. However, _for now_ the workaround provided above is the recommended solution until that has been worked out.

I will keep this issue open to provide updates on the long term fix.

**Comment by james-aws** [comment]
Please update to the latest neuron device plugin. In the Neuron 2.13.2 release we fixed the bug where a single pod with multiple containers failed to launch. Marking this issue as resolved.
