### ISSUE TITLE
Issue on page /src/examples/pytorch/byoc_sm_bert_tutorial/sagemaker_container_neuron.html

### ISSUE THREAD

**Issue by IamExperimenting** [aws-neuron/aws-neuron-sdk#677]
I tried to follow and replicate the experiment which is available in aws neuron sdk official page. Unfortunately, it's throwing error while compilation, could you please help me 

```
RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

Note: I'm performing this in AWS SageMaker Notebook c5.4xlarge instance 
I ran the below steps to create a new kernel for aws neuron.
```
# Install Python venv 
sudo yum install -y python3.7-venv gcc-c++ 

# Create Python venv
python3.7 -m venv aws_neuron_venv_pytorch 

# Activate Python venv 
source aws_neuron_venv_pytorch/bin/activate 
python -m pip install -U pip 

# Install Jupyter notebook kernel
pip install ipykernel 
python3.7 -m ipykernel install --user --name aws_neuron_venv_pytorch --display-name "Python (torch-neuron)"
pip install jupyter notebook
pip install environment_kernels

# Set pip repository pointing to the Neuron repository 
python -m pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com

# Install PyTorch Neuron
python -m pip install torch-neuron neuron-cc[tensorflow] "protobuf" torchvision
````

please correct me if i'm doing a mistake

**Comment by jyang-aws** [comment]
Hi IamExperimenting,
Thanks for reporting the issue. The setup steps seem correct.
Could you check the transformers version you used as well? Please give it a try with 4.6.0 as mentioned in the tutorial if possible. That would give us more info.

**Comment by IamExperimenting** [comment]
@jyang-aws could you please help me here?

**Comment by jyang-aws** [comment]
09/05/2023 08:51:57 PM INFO 53658 [root]: Compiler status PASS                                                                                        INFO:Neuron:Number of arithmetic operators (post-compilation) before = 565, compiled = 548, percent compiled = 96.99%                                 
INFO:Neuron:The neuron partitioner created 1 sub-graphs                                                                                               
INFO:Neuron:Neuron successfully compiled 1 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 100.0%          
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:                                                                                 
INFO:Neuron: => aten::Int: 96                                                                                                                         
INFO:Neuron: => aten::add: 36                                                                                                                         
INFO:Neuron: => aten::contiguous: 12                                                                                                                  
INFO:Neuron: => aten::div: 12                                                                                                                         
INFO:Neuron: => aten::dropout: 38                                                                                                                     
INFO:Neuron: => aten::gelu: 12                                                                                                                        
INFO:Neuron: => aten::layer_norm: 25                                                                                                                  
INFO:Neuron: => aten::linear: 74                                                                                                                      
INFO:Neuron: => aten::matmul: 24                                                                                                                      
INFO:Neuron: => aten::permute: 48                                                                                                                     
INFO:Neuron: => aten::select: 1                                                                                                                       
INFO:Neuron: => aten::size: 96                                                                                                                        
INFO:Neuron: => aten::slice: 1                                                                                                                        
INFO:Neuron: => aten::softmax: 12                                          
INFO:Neuron: => aten::tanh: 1                                                                                                                         
INFO:Neuron: => aten::transpose: 12                                                                                                                   
INFO:Neuron: => aten::view: 48                                                                                                                        
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:                                                                                   
INFO:Neuron: => aten::Int: 1 [supported]                                                                                                              
INFO:Neuron: => aten::add: 2 [supported]                                                                                                              
INFO:Neuron: => aten::add_: 1 [supported]                                  
INFO:Neuron: => aten::embedding: 3 [not supported]
INFO:Neuron: => aten::mul: 1 [supported]
INFO:Neuron: => aten::rsub: 1 [supported]
INFO:Neuron: => aten::size: 1 [supported]
INFO:Neuron: => aten::slice: 4 [supported]
INFO:Neuron: => aten::to: 1 [supported]
INFO:Neuron: => aten::unsqueeze: 2 [supported]             
This version should work.

neuron-cc 1.18.0.0+ba9e7fa5a
torch-neuron 1.13.1.2.9.1.0
torch 1.13.1
torch-neuron 1.13.1.2.9.1.0
Please let us know if there’s further issues.
