### ISSUE TITLE
Add support for example_kwarg_inputs for torch_neuronx.trace!

### ISSUE THREAD

**Issue by raunit-x** [aws-neuron/aws-neuron-sdk#682]
From [torch.jit.trace](https://pytorch.org/docs/stable/generated/torch.jit.trace.html) API documentation
> **example_inputs ([tuple](https://docs.python.org/3/library/stdtypes.html#tuple) or [torch.Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor) or [None](https://docs.python.org/3/library/constants.html#None), optional)** – A tuple of example inputs that will be passed to the function while tracing. Default: None. Either this argument or example_kwarg_inputs should be specified. The resulting trace can be run with inputs of different types and shapes assuming the traced operations support those types and shapes. example_inputs may also be a single Tensor in which case it is automatically wrapped in a tuple. When the value is None, example_kwarg_inputs should be specified.

> **example_kwarg_inputs ([dict](https://docs.python.org/3/library/stdtypes.html#dict), optional)** – This parameter is a pack of keyword arguments of example inputs that will be passed to the function while tracing. Default: None. Either this argument or example_inputs should be specified. The dict will be unpacking by the arguments name of the traced function. If the keys of the dict don’t not match with the traced function’s arguments name, a runtime exception will be raised.

Can we please add support for `example_kwarg_inputs` in `torch_neuronx.trace`. Otherwise what would be the workaround something like that?

More context:
I am trying to compile an `encoder-decoder model (Whisper)` for `inf2` and I am running into issues while compiling the decoder model. It would be resolved if the support for example_kwarg_inputs is given then I can have static input shapes

**Comment by aws-mvaria** [comment]
Hi @raunit-x, 
We do not have plans to do this at the moment. We recommend using a wrapper at the moment (see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuron/troubleshooting-guide.html#torch-jit-trace-issues). Let us know if you have any other questions.
Thanks.
