### ISSUE TITLE
NRT Input and Output Tensors are Sorted Lexically Rather than Numerically

### ISSUE THREAD

**Issue by xanderdunn** [aws-neuron/aws-neuron-sdk#684]
Using the code [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-runtime/nrt-api-guide.html#the-code), when we iterate through input and output tensors we're seeing that they're sorted lexically rather than numerically on the name of the tensor, so they aren't in the expected order.

In `iterate_tensors` we find that it's iterating the inputs and outputs in the following order:

What we're seeing (lexical): input0, input1, input10, input100, input101, input102, ...
What we expect (numerical): input0, input1, input2, ..., input10, input11, ..., input99, input100, input101, input102, ...

What we're seeing (lexical): output0, output1, output10, ...
What we expect (numerical): output0, output1, output2, ..., output9, output10, ...

Here is an example graph where this can be seen on the inputs: 
[pb_and_neff.zip](https://github.com/aws-neuron/aws-neuron-sdk/files/11712736/pb_and_neff.zip)

This is inconvenient and probably unintentional? Numerical order would put them in the same order as the XLA HLO input/output order. 

Currently we're working around this by sorting our inputs lexically before we pass them to `iterate_tensors` and then sorting the outputs numerically once we get them from `iterate_tensors`.

**Comment by micwade-aws** [comment]
Thanks, we're taking a closer look.

**Comment by xanderdunn** [comment]
I spoke with Ilya who described that there is no explicit contract between the compiler and the runtime about the ordering of tensors in the NEFF. So, the above is not unexpected.

What we can do:
- `nrt_load` or `nrt_load_collectives` returns a model pointer. 
- `nrt_get_model_tensor_info(model pointer)` returns a `nrt_tensor_info_array_t`
- Iterating the `tensor_array`, each `nrt_tensor_info` has a `name` that looks like `InputN` or `OutputN` where `N` is 0, 1, 2, ...
- We should match `N` to the `HloInstructionProto`'s `.id` field, so we could feed in a hashmap of `HloInstructionProto.id` -> Tensor. So we're doing `[0] => Input0`

The framework integration layer is doing the same thing, so this is a safe approach.
