### ISSUE TITLE
Support for Pytorch 2.0

### ISSUE THREAD

**Issue by AhmedKamal** [aws-neuron/aws-neuron-sdk#686]
Given that it is [backward compatible](https://pytorch.org/get-started/pytorch-2.0/#:~:text=Why%202.0%20instead%20of%201.14%3F%0APyTorch%202.0%20is%20what%201.14%20would%20have%20been.%20We%20were%20releasing%20substantial%20new%20features%20that%20we%20believe%20change%20how%20you%20meaningfully%20use%20PyTorch%2C%20so%20we%20are%20calling%20it%202.0%20instead.), why isn't torch 2 supported as well?

when we tried to we got this error from aws neuron sdk.

ImportError Invalid dependency version torch==2.0.1+cu117. Expected torch==1.13.1

```
 # Extract the version prefix from the torch-neuron package
    version_parts = __version__.split('.')
    version = '.'.join(version_parts[:3])
    if not __version__.startswith(torch.__version__):
        raise ImportError(  f'Invalid dependency version torch=={torch.__version__}. '
            f'Expected torch=={version}'
        ) from e
```

**Comment by aws-rhsoln** [comment]
We built our library against a specific torch version and some of the c++ symbols maybe missing when we upgrade to a newer torch version. Hence, it is not recommended to use torch-neuron=1.13 with pytorch=2.0. On another note, we are working on adding support for PyTorch=2.0 for inf2 and trn1 in our future releases.
