### ISSUE TITLE
Incorrect Output Shapes

### ISSUE THREAD

**Issue by xanderdunn** [aws-neuron/aws-neuron-sdk#693]
We're getting an incorrect output shape when loading some of our models. 

We have this happening on various different graphs. Here is one example:
[rust_hlo_run_rank_5.pb.zip](https://github.com/aws-neuron/aws-neuron-sdk/files/11780416/rust_hlo_run_rank_5.pb.zip)

Compile with
```
neuronx-cc compile /tmp/rust_hlo_run_rank_5.pb --framework XLA --target trn1 --auto-cast none --model-type transformer --output /tmp/run_rank_5.neff
```

Looking at the XLA HLO we see:
```
compiled debug_ir: HloModule xla_computation_ordered_wrapper, entry_computation_layout={(f32[1,480]{1,0}, f32[240,480]{1,0}, f32[240,480]{1,0}, f32[240,480]{1,0}, f32[1,480]{1,0}, /*index=5*/f32[480,480]{1,0}, f32[240,480]{1,0}, f32[1,480]{1,0}, f32[240,480]{1,0}, f32[240,480]{1,0}, /*index=10*/f32[240,480]{1,0}, f32[1,480]{1,0}, f32[480,480]{1,0}, f32[240,480]{1,0})->(f32[512,480]{1,0}, f32[256,480]{1,0})}

...

  ROOT tuple.301 = (f32[512,480]{1,0}, f32[256,480]{1,0}) tuple(add.292, slice.18)
}
```

So, we're expecting the outputs to have shapes `[512,480]` and `[256,480]`. However, without even running the model, after compiling the .neff and loading it with `nrt_load` and getting the model info with `nrt_get_model_tensor_info`, we find that the `shape` of one of the outputs is incorrect.

The second output should have shape `[256,480]`, but the `nrt_tensor_info.shape` has `[2, 128, 480]`. It's the correct number of elements, but not the correct shape.  

```
$ dpkg -l | grep -i neuron
ii  aws-neuronx-collectives                2.14.9.0-f3942f597                amd64        neuron_ccom built using CMake
ii  aws-neuronx-dkms                       2.10.11.0                         amd64        aws-neuronx driver in DKMS format.
ii  aws-neuronx-oci-hook                   2.2.9.0                           amd64        neuron_oci_hook built using CMake
ii  aws-neuronx-runtime-lib                2.14.8.0-edaf1b171                amd64        neuron_runtime built using CMake
ii  aws-neuronx-tools                      2.11.10.0                         amd64        Neuron profile and debug tools
$ neuronx-cc --version
NeuronX Compiler version 2.7.0.40+f7c6cf2a3

Running on AMI ami-01257e71ecb2f431c
Running in region usw2-az4
Running on python 3.8.10

HWM version 2.7.0.3-0092b9d34
NumPy version 1.21.6
```

**Comment by xanderdunn** [comment]
I can confirm that all of the values are correct and they are ordered correctly, despite differing in the shape. 

It's possible that the neff / NRT runtime is returning shapes as represented internally to NRT, and these are not expected to be the same as the shapes as seen in the XLA HLO. If that's the case, then we can ignore this by not using the NRT runtime's `nrt_tensor_info_array` shapes and just apply our own shapes to the outputs.

**Comment by arktoswb** [comment]
This is still occurring:
```
Output shape mismatch: nrt [384, 160] vs xla [3, 128, 160]
```

**Comment by aws-donkrets** [comment]
Hi [arktoswb](https://github.com/arktoswb) - we have not issued a fix for this ticket yet. Once it has been resolved we will post an update here.

**Comment by xanderdunn** [comment]
This was solved a while ago, closing.
