### ISSUE TITLE
Does Inferentia 2 support autoregressive models specifically Meta's LLaMa? 

### ISSUE THREAD

**Issue by dhcracchiolo** [aws-neuron/aws-neuron-sdk#696]
I see a similar roadmap card for GPT-2 on INF1 https://github.com/aws-neuron/aws-neuron-sdk/projects/2#card-50020563.|
From this issue it looks like they got a T5 to compile: https://github.com/aws-neuron/aws-neuron-sdk/issues/688

Doing a quick monkey see monkey do approach leads me to a script like this:
```
from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig
import torch
import torch_neuronx

tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-7b-hf")

model = LlamaForCausalLM.from_pretrained(
    "decapoda-research/llama-7b-hf",
)

if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({'pad_token': '[PAD]'})
    model.resize_token_embeddings(len(tokenizer))

def encode(tokenizer, *inputs, max_length=128, batch_size=1):
    tokens = tokenizer.encode_plus(
        *inputs,
        max_length=max_length,
        padding='max_length',
        truncation=True,
        return_tensors="pt"
    )
    input_ids = torch.repeat_interleave(tokens['input_ids'], batch_size, 0)
    attention_mask = torch.repeat_interleave(tokens['attention_mask'], batch_size, 0)
    return [input_ids, attention_mask]

PROMPT = f"""### Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
### Input: "What is the difference between a llama and a vicuna?"
### Response:"""

inputs = tokenizer(
    PROMPT,
    return_tensors="pt",
)
input_ids = inputs["input_ids"]

# and trace using the wrapped model
model_neuron = torch_neuronx.trace(wrapped_model, encode(tokenizer, PROMPT), compiler_args=["--auto-cast-type", "fp8_e4m3", "--auto-cast", "all"])


# Save the TorchScript for inference deployment
filename = 'neuron-model.pt'
torch.jit.save(model_neuron, filename)
```

This throws this error:
```
I'm getting this error:
:Dictionary inputs to traced functions must have consistent type. Found Tensor and Tuple[Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor]]
```

I'm going to start digging deeper and find the issues at hand but before I do that I just want to make sure this type of model is supported.  Just curious any more information I can get on this?  Thanks!

**Comment by hannanjgaws** [comment]
Hi @dhcracchiolo:

In general, generative decoding requires LLM-specific support to be performant. We are currently working on adding optimized support for LLaMa decoder inference in the [transformers-neuronx](https://github.com/aws-neuron/transformers-neuronx) library, and expect it to come out in a future release.

We will leave this ticket open, and will provide an update when transformers-neuronx supports LLaMa.

**Comment by dhcracchiolo** [comment]
> LLM-specific support to be performant.

Excellent!  Thanks for the reply!  I'm sure the community will be excited for LLaMa support.  👍

**Comment by amin2718** [comment]
@hannanjgaws any updates or ETA?

**Comment by harshhpareek-prodigaltech** [comment]
Any further updates regarding LLAMA 2 support for inf2 machines?

**Comment by AWSNB** [comment]
Any day now,  just finishing the large scale regression test before formal release

From: harshhpareek-prodigaltech ***@***.***>
Reply-To: aws-neuron/aws-neuron-sdk ***@***.***>
Date: Monday, August 14, 2023 at 12:59 PM
To: aws-neuron/aws-neuron-sdk ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [aws-neuron/aws-neuron-sdk] Does Inferentia 2 support autoregressive models specifically Meta's LLaMa? (Issue #696)


Any further updates regarding LLAMA 2 support for inf2 machines?

**Comment by jluntamazon** [comment]
Inference support for LLaMa (v1/v2) will be available with [transformers-neuronx](https://github.com/aws-neuron/transformers-neuronx) in the coming release. This will include support for regular multi-head variants of the model but not grouped/multi-query versions (i.e. LLaMa v2 70b).

Training support and grouped/multi-query variants will be available in future releases.

**Comment by jyang-aws** [comment]
Hi @dhcracchiolo:
On the inf2, please checkout our example
https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuronx/transformers-neuronx/inference/meta-llama-2-13b-sampling.ipynb
Training support is also available, a tutorial is at https://github.com/aws-neuron/aws-neuron-parallelcluster-samples/blob/master/examples/jobs/neuronx-nemo-megatron-llamav2-job.md
Please give a try and keep us posted:)

**Comment by echatzikyriakidis** [comment]
Hi everyone,

Does anyone knows if AWS Neuron supports GPT2LMHeadModel from Hugging Face (pytorch). 

I am wondering if I can use it to train an LLM and use to for generation on Inferentia1/2 and Trainium1/2 instances?

Thanks!
