### ISSUE TITLE
Relationship between vCPU and neuron device/core

### ISSUE THREAD

**Issue by ndenStanford** [aws-neuron/aws-neuron-sdk#701]
Is there a relationship between VCPU and neuron device/core? From my understanding, 1 inf2 has 1 neuron device (neuron accelerator), which consists of 2 neuron cores. However, not sure how that's related to vCPU. Any clarification is appreciated. 

https://aws.amazon.com/ec2/instance-types/inf2/

**Comment by aws-ennst** [comment]
There’s a varied number of vCPUs and NeuronDevices depending on the size and family of the instance.  More details about how many vCPUs and NeuronDevices are in each instance size can be found on our Inf2 Architecture page here: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/neuron-hardware/inf2-arch.html#aws-inf2-arch. 

Similar pages exist on the docs site describing the other instance types and NeuronCore technologies in more detail if you are interested.

**Comment by ndenStanford** [comment]
I'm a bit unclear on how the number of the vCPU and neuroncore translates to how the parallelization should be performed. For example, how many workers should I set if I deploy an NLP model on inf2.xlarge? Should it be 4 because this machine has 4 vCPU, or 1 because it has 1 inferentia2 device, or 2 because it has 1 x 2 = 2 neuroncore?

**Comment by mrnikwaws** [comment]
Hi @ndenStanford,

If you are tracing your model (torch.neuronx.trace) and running on an inf2.xlarge then your worker processes should scale with number of Neuron cores per instance / the number of  Neuron cores used per model".  Assuming that your model uses one core - then typically the inf2.xlarge would have two worker processes, one bound to each Neuron core.

A sample setup for torchserve is shown in the docs here: https://amzn-aws.slack.com/archives/G01FZV8KXGC/p1688584733717799?thread_ts=1688154156.637189&cid=G01FZV8KXGC

**Comment by mrnikwaws** [comment]
Closing this issue since I think we have answered the question

**Comment by ndenStanford** [comment]
Thanks for the comment! I cannot access the link you attached though. Would it be possible to share it in a different way?

**Comment by micwade-aws** [comment]
This was the link @ndenStanford - https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuron/tutorials/tutorial-torchserve.html#run-torchserve. Sorry about that.
