### ISSUE TITLE
neuronx-cc segfault when building Stable Diffusion 2.1 on Ubuntu 22

### ISSUE THREAD

**Issue by supersat** [aws-neuron/aws-neuron-sdk#711]
We have a containerized version of the Stable Diffusion 2.1 example in our CI, running on Ubuntu 22.04 with Python 3.10 (currently dependencies in our serving layer, but we might be able to relax that). We noticed that after yesterday's SDK release, it no longer builds with the latest version of `neuronx-cc`, but instead segfaults with this message:

`Neuron: The neuronx-cc (neuron compiler) crashed (SEGFAULT). This is likely due to a bug in the compiler. Please lodge an issue at 'https://github.com/aws/aws-neuron-sdk/issues'`

We have not updated the SD 2.1 code with the latest changes in the example, but the compiler shouldn't crash regardless.

Our apt dependencies:

`aws-neuronx-tools=2.12.* aws-neuronx-collectives=2.15.* aws-neuronx-runtime-lib=2.15.*`

Our `pip` dependencies: `accelerate==0.16.0 diffusers==0.14.0 transformers==4.30.2 safetensors==0.3.1 neuronx-cc==2.8.0.25+a3ad0f342 torch-neuronx==1.13.1.1.9.0`

**Comment by supersat** [comment]
Tried a few different variants on our build, and it seems to be an issue with running on Ubuntu 22.04. Ubuntu 20.04 with Python 3.8 and Python 3.10 works.

**Comment by aws-donkrets** [comment]
Hi [supersat](https://github.com/supersat) - thx for confirming that it may be an issue only on U22.  We will test our U22 support configs a bit more to isolate the problem.

**Comment by aws-donkrets** [comment]
Hi [supersat](https://github.com/supersat) - just providing an update. We have further tested on U22 and should have a fix for this in our next release.

**Comment by aws-bowencc** [comment]
Hi @supersat - the neuron 2.13.0 is out, free feel to try it out and repo the issue if it doesn't work.
