### ISSUE TITLE
Issue on k8s-neuron-device-plugin.yml - spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+;

### ISSUE THREAD

**Issue by yahavb** [aws-neuron/aws-neuron-sdk#719]
Warning: spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead

Need to remove 
```
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
```
and add under the pod spec:
```
spec:
      priorityClassName: high-priority
```

**Comment by jeffhataws** [comment]
Thanks @yahavb for submitting the PR to fix the issue. We will review it.

**Comment by micwade-aws** [comment]
Merge of #759 was expected to fix this.  Closing.
