### ISSUE TITLE
Error during the compilation of pytorch model for inf1

### ISSUE THREAD

**Issue by josephwong14wkh** [aws-neuron/aws-neuron-sdk#721]
Hi team, 
i am trying to trace a pytorch model for inference on inf1.xlarge instance and i get the following error:

> INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)
> INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)
> INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 216, fused = 216, percent fused = 100.0%
> INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 216, fused = 216, percent fused = 100.0%
> INFO:Neuron:Compiling function _NeuronGraph$743 with neuron-cc
> INFO:Neuron:Compiling function _NeuronGraph$743 with neuron-cc
> INFO:Neuron:Compiling with command line: '/opt/aws_neuron_venv_pytorch_inf1/bin/neuron-cc compile /tmp/tmpokj9sd0c/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpokj9sd0c/graph_def.neff --io-config {"inputs": {"0:0": [[150, 80], "float32"]}, "outputs": ["aten_transpose_1/transpose:0"]} --verbose 35'
> INFO:Neuron:Compiling with command line: '/opt/aws_neuron_venv_pytorch_inf1/bin/neuron-cc compile /tmp/tmpokj9sd0c/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpokj9sd0c/graph_def.neff --io-config {"inputs": {"0:0": [[150, 80], "float32"]}, "outputs": ["aten_transpose_1/transpose:0"]} --verbose 35'
> ........python3.8: /local/p4clients/pkgbuild-WHO9X/workspace/src/KaenaCompiler/neuroncc/walrus/dep_based_optims/sched_common.cpp:993: void get_ap_range_union(std::vector<bir::AccessPattern*>&, mem_loc_p, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int): Assertion `end_addr < loc->getBytesPerPartition()' failed.
> WARNING:Neuron:The neuron-cc (neuron compiler) process aborted (SIG_ABORT).  This is likely due to an unexpected condition internally (a bug).  Please lodge an issue at 'https://github.com/aws/aws-neuron-sdk/issues'
> WARNING:Neuron:The neuron-cc (neuron compiler) process aborted (SIG_ABORT).  This is likely due to an unexpected condition internally (a bug).  Please lodge an issue at 'https://github.com/aws/aws-neuron-sdk/issues'
> WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$743; falling back to native python function call
> WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$743; falling back to native python function call
> ERROR:Neuron:neuron-cc failed with the following command line call:
> /opt/aws_neuron_venv_pytorch_inf1/bin/neuron-cc compile /tmp/tmpokj9sd0c/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpokj9sd0c/graph_def.neff --io-config '{"inputs": {"0:0": [[150, 80], "float32"]}, "outputs": ["aten_transpose_1/transpose:0"]}' --verbose 35
> Traceback (most recent call last):
>   File "/opt/aws_neuron_venv_pytorch_inf1/lib/python3.8/site-packages/torch_neuron/convert.py", line 413, in op_converter
>     neuron_function = self.subgraph_compiler(
>   File "/opt/aws_neuron_venv_pytorch_inf1/lib/python3.8/site-packages/torch_neuron/decorators.py", line 263, in trace
>     raise subprocess.SubprocessError(
> subprocess.SubprocessError: neuron-cc failed with the following command line call:
> /opt/aws_neuron_venv_pytorch_inf1/bin/neuron-cc compile /tmp/tmpokj9sd0c/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpokj9sd0c/graph_def.neff --io-config '{"inputs": {"0:0": [[150, 80], "float32"]}, "outputs": ["aten_transpose_1/transpose:0"]}' --verbose 35
> ERROR:Neuron:neuron-cc failed with the following command line call:
> /opt/aws_neuron_venv_pytorch_inf1/bin/neuron-cc compile /tmp/tmpokj9sd0c/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpokj9sd0c/graph_def.neff --io-config '{"inputs": {"0:0": [[150, 80], "float32"]}, "outputs": ["aten_transpose_1/transpose:0"]}' --verbose 35
> Traceback (most recent call last):
>   File "/opt/aws_neuron_venv_pytorch_inf1/lib/python3.8/site-packages/torch_neuron/convert.py", line 413, in op_converter
>     neuron_function = self.subgraph_compiler(
>   File "/opt/aws_neuron_venv_pytorch_inf1/lib/python3.8/site-packages/torch_neuron/decorators.py", line 263, in trace
>     raise subprocess.SubprocessError(
> subprocess.SubprocessError: neuron-cc failed with the following command line call:
> /opt/aws_neuron_venv_pytorch_inf1/bin/neuron-cc compile /tmp/tmpokj9sd0c/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpokj9sd0c/graph_def.neff --io-config '{"inputs": {"0:0": [[150, 80], "float32"]}, "outputs": ["aten_transpose_1/transpose:0"]}' --verbose 35
> INFO:Neuron:Number of arithmetic operators (post-compilation) before = 216, compiled = 0, percent compiled = 0.0%
> INFO:Neuron:Number of arithmetic operators (post-compilation) before = 216, compiled = 0, percent compiled = 0.0%
> INFO:Neuron:The neuron partitioner created 1 sub-graphs
> INFO:Neuron:The neuron partitioner created 1 sub-graphs
> INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
> INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
> INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
> INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
> INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
> INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
> INFO:Neuron: => aten::_convolution: 78 [supported]
> INFO:Neuron: => aten::_convolution: 78 [supported]
> INFO:Neuron: => aten::add: 36 [supported]
> INFO:Neuron: => aten::add: 36 [supported]
> INFO:Neuron: => aten::add_: 12 [supported]
> INFO:Neuron: => aten::add_: 12 [supported]
> INFO:Neuron: => aten::div: 4 [supported]
> INFO:Neuron: => aten::div: 4 [supported]
> INFO:Neuron: => aten::leaky_relu: 77 [supported]
> INFO:Neuron: => aten::leaky_relu: 77 [supported]
> INFO:Neuron: => aten::squeeze: 1 [supported]
> INFO:Neuron: => aten::squeeze: 1 [supported]
> INFO:Neuron: => aten::tanh: 1 [supported]
> INFO:Neuron: => aten::tanh: 1 [supported]
> INFO:Neuron: => aten::transpose: 2 [supported]
> INFO:Neuron: => aten::transpose: 2 [supported]
> INFO:Neuron: => aten::unsqueeze: 1 [supported]
> INFO:Neuron: => aten::unsqueeze: 1 [supported]
> INFO:Neuron: => aten::zeros_like: 4 [supported]
> INFO:Neuron: => aten::zeros_like: 4 [supported]
> Traceback (most recent call last):
>   File "inf1_Inf.py", line 54, in <module>
>     model_neuron = torch.neuron.trace(wrapper, example_inputs=random_example_input)
>   File "/opt/aws_neuron_venv_pytorch_inf1/lib/python3.8/site-packages/torch_neuron/convert.py", line 217, in trace
>     cu.stats_post_compiler(neuron_graph)
>   File "/opt/aws_neuron_venv_pytorch_inf1/lib/python3.8/site-packages/torch_neuron/convert.py", line 530, in stats_post_compiler
>     raise RuntimeError(
> RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!

and i have seen many similar error with only the following sentence different. Therefore, i believe that the main reason of the error is following sentence of the above error:

> WHO9X/workspace/src/KaenaCompiler/neuroncc/walrus/dep_based_optims/sched_common.cpp:993: void get_ap_range_union(std::vector<bir::AccessPattern*>&, mem_loc_p, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int): Assertion `end_addr < loc->getBytesPerPartition()' failed.

May i know the reason of the issue? Thank you!

**Comment by josephwong14wkh** [comment]
I don't encounter this error when the example input size is small enough while i did encounter when the example input size is large

**Comment by jeffhataws** [comment]
Thanks @jestiny0 for filing the issue. We will take a look.

**Comment by aws-mvaria** [comment]
Hi @josephwong14wkh, The assertion you are running into is an internal compiler error and can certainly be affected by the input shape. Are you able to share your script / model so that we can reproduce? Thanks

**Comment by josephwong14wkh** [comment]
Hi, thank you for the reply. I have checked my code and found that there is some operation that probably not supported by torch neuron. I have commented it out and the problem solved. Thanks!
