### ISSUE TITLE
Issue on page /general/setup/neuron-setup/pytorch/neuronx/ubuntu/torch-neuronx-ubuntu20-pytorch-dlami.html

### ISSUE THREAD

**Issue by mikwin2** [aws-neuron/aws-neuron-sdk#722]
Please update the document instruction as follow:

**Existing**
# Activate Python venv 
source aws_neuron_venv_pytorch/bin/activate 

**Propose change update:**
# Activate Python venv 
source /opt/aws_neuron_venv_pytorch/bin/activate

**Comment by jeffhataws** [comment]
Thanks @mikwin2 for bringing the problem to our attention. We will fix this.

**Comment by mrnikwaws** [comment]
Docs updated
