### ISSUE TITLE
Issue Report: Internal Compiler Error during Compilation of Stable Diffusion Model VAE Encoder

### ISSUE THREAD

**Issue by Cho-Geonwoo** [aws-neuron/aws-neuron-sdk#723]
## Description:
I encountered an internal compiler error while attempting to compile the stable diffusion model VAE encoder using the torch-neuronx library. I used the "jzli/CyberRealistic-3.2" stable diffusion base image on an AWS Inf2.8xlarge instance, with the AMI "Deep Learning AMI Neuron PyTorch 1.13 (Ubuntu 20.04) 20230720". The error message I received during compilation is as follows:

```
ERROR ***************************************************************
ERROR  An Internal Compiler Error has occurred
ERROR ***************************************************************
ERROR 
ERROR Error message:  [Errno 2] No such file or directory: 'sg00/def.json'
ERROR 
ERROR Error class:    FileNotFoundError
ERROR Error location: Unknown
```
## Environment:
Base Image: "jzli/CyberRealistic-3.2"
Instance Type: AWS Inf2.8xlarge
AMI: Deep Learning AMI Neuron PyTorch 1.13 (Ubuntu 20.04) 20230720

## Steps to Reproduce:
Launch AWS Inf2.8xlarge instance with the specified AMI.
Use the "jzli/CyberRealistic-3.2" base image with diffusers `StableDiffusionImg2ImgPipeline`.
Attempt to compile the stable diffusion model VAE encoder using the torch-neuronx library.
Encounter the internal compiler error with the provided error message.

## Expected Behavior:
The compilation process should complete without encountering any internal compiler errors.

## Additional Information:
I suspect that the error might be related to a missing file or directory named 'sg00/def.json', but I couldn't locate this file in the specified environment. Any insights into resolving this issue would be greatly appreciated.

Thank you for your assistance in addressing this problem.

Feel free to modify the details as needed to accurately reflect your situation.

**Comment by aws-mvaria** [comment]
Thanks @Cho-Geonwoo for the description of the issue. We are taking a look and will get back to you shortly.

**Comment by aws-mvaria** [comment]
Hi @Cho-Geonwoo, we are using the base image, instance, and AMI that you specified, but are unable to reproduce the issue. We are able to compile the text_encoder and vae.decoder correctly. However, we are unsure on how exactly you are compiling the VAE encoder. Can you share the script you are using to compile the VAE encoder? Thank you!

**Comment by Cho-Geonwoo** [comment]
@aws-mvaria Thank you for your fast response.
Below is the script I used for inference.
Checkpoints are available at the [link](https://drive.google.com/file/d/1rJZJkHpaXU6_tyN8lTaiAPPoqzj16f-H/view?usp=drive_link)

```
import os

os.environ["NEURON_FUSE_SOFTMAX"] = "1"

import torch
import torch.nn as nn
import numpy as np
import torch_neuronx

import time
import copy

from safetensors import safe_open
from diffusers import StableDiffusionImg2ImgPipeline
from diffusers.models.unet_2d_condition import UNet2DConditionOutput
from diffusers.schedulers.scheduling_dpmsolver_sde import DPMSolverSDEScheduler

# Define datatype
DTYPE = torch.float32

class UNetWrap(nn.Module):
    def __init__(self, unet):
        super().__init__()
        self.unet = unet

    def forward(
        self, sample, timestep, encoder_hidden_states, cross_attention_kwargs=None
    ):
        out_tuple = self.unet(
            sample, timestep, encoder_hidden_states, return_dict=False
        )
        return out_tuple


class NeuronUNet(nn.Module):
    def __init__(self, unetwrap):
        super().__init__()
        self.unetwrap = unetwrap
        self.config = unetwrap.unet.config
        self.in_channels = unetwrap.unet.in_channels
        self.device = unetwrap.unet.device

    def forward(
        self, sample, timestep, encoder_hidden_states, cross_attention_kwargs=None
    ):
        sample = self.unetwrap(
            sample,
            timestep.to(dtype=DTYPE).expand((sample.shape[0],)),
            encoder_hidden_states,
        )[0]
        return UNet2DConditionOutput(sample=sample)


class NeuronTextEncoder(nn.Module):
    def __init__(self, text_encoder):
        super().__init__()
        self.neuron_text_encoder = text_encoder
        self.config = text_encoder.config
        self.dtype = text_encoder.dtype
        self.device = text_encoder.device

    def forward(self, emb, attention_mask=None):
        return [self.neuron_text_encoder(emb)["last_hidden_state"]]


COMPILER_WORKDIR_ROOT = "sd2_compile_dir_768"
model_id = "jzli/CyberRealistic-3.2"
pipe = StableDiffusionImg2ImgPipeline.from_pretrained(model_id, torch_type=DTYPE)
pipe.scheduler = DPMSolverSDEScheduler(noise_sampler_seed=1017878886409126)

import torch
unet_ckpt = torch.load("ckpt/dreambooth_unet.ckpt")
text_encoder = torch.load("ckpt/dreambooth_text_encoder.ckpt")
vae_decoder = torch.load("ckpt/dreambooth_vae_decoder.ckpt")
vae_encoder = torch.load("ckpt/dreambooth_vae_encoder.ckpt")
vae_quant_conv = torch.load("ckpt/dreambooth_vae_quant_conv.ckpt")
vae_post_quant_conv = torch.load("ckpt/dreambooth_vae_post_quant_conv.ckpt")

pipe.unet.load_state_dict(unet_ckpt["state_dict"])
pipe.text_encoder.load_state_dict(text_encoder["state_dict"])
pipe.vae.decoder.load_state_dict(vae_decoder["state_dict"])
pipe.vae.encoder.load_state_dict(vae_encoder["state_dict"])
pipe.vae.quant_conv.load_state_dict(vae_quant_conv["state_dict"])
pipe.vae.post_quant_conv.load_state_dict(vae_post_quant_conv["state_dict"])

encoder = pipe.vae.encoder

# Compile vae encoder
encoder_in = torch.randn([1, 4, 768, 768], dtype=DTYPE)
encoder_neuron = torch_neuronx.trace(
    encoder,
    encoder_in,
    compiler_workdir=os.path.join(COMPILER_WORKDIR_ROOT, "vae_encoder"),
    compiler_args=["--enable-fast-loading-neuron-binaries"],
)

# Enable asynchronous loading to speed up model load
torch_neuronx.async_load(encoder_neuron)

# Save the compiled vae encoder
encoder_filename = os.path.join(COMPILER_WORKDIR_ROOT, "vae_encoder/model.pt")
torch.jit.save(encoder_neuron, encoder_filename)
```

**Comment by aws-mvaria** [comment]
Hi @Cho-Geonwoo , I don't believe we have access to the link you posted above. Would you mind granting access, or sending us the artifacts in another way?
Thanks,
Meghal

**Comment by Cho-Geonwoo** [comment]
Hi @aws-mvaria .
I shared the file through your request.
If you can't download the file, I'll share the file in a different way.
Thanks.

**Comment by aws-mvaria** [comment]
Hi @Cho-Geonwoo,

Thank you for sharing the checkpoint file. We are unable to reproduce the issue with the script provided. Compiling the VAE encoder succeeds with a model.pt file generated. Note that we had to make the two following changes to your script:

1. In the line `encoder_in = torch.randn([1, 4, 768, 768], dtype=DTYPE)` , the second dimension should be 3, not 4. Otherwise there is a runtime error
2. We commented out loading the state dict for the text_encoder of the model (line 80), as otherwise we get this error: `Unexpected key(s) in state_dict: "text_model.embeddings.position_ids".`

We are using your AMI (Deep Learning AMI Neuron PyTorch 1.13 (Ubuntu 20.04)), but want to double check we have the same neuron versions. When running `pip3 list | grep neuron` , here is what we have:
```
aws-neuronx-runtime-discovery 2.9
libneuronxla                  0.5.391
neuronx-cc                    2.8.0.25+a3ad0f342
neuronx-hwm                   2.8.0.3+2b7c6da39
torch-neuronx                 1.13.1.1.9.0
torch-xla                     1.13.1+torchneuron8
```
Also, would you be able to send the full compile log? We believe the real error may be further up the compiler logs.

Thanks

**Comment by aws-mvaria** [comment]
Hi @Cho-Geonwoo ,
Closing this issue as we were unable to reproduce and have not heard back on the above reply. However, feel free to reopen if you are still encountering an issue.
Thanks.
