### ISSUE TITLE
The benchmark python file is 404

### ISSUE THREAD

**Issue by MaggieGao02** [aws-neuron/aws-neuron-sdk#735]
The benchmark python file for SD XL is 404. 

https://github.com/aws-neuron/aws-neuron-sdk/blob/master/src/benchmark/pytorch/sdxl_1024_benchmark.py

**Comment by jyang-aws** [comment]
Hi @MaggieGao02, 

Thanks for letting us know. The link indeed has issue, we'll fix it asap.
