### ISSUE TITLE
Is it possible to run llama2-13b on smaller inferentia instances?

### ISSUE THREAD

**Issue by VoVAllen** [aws-neuron/aws-neuron-sdk#741]
Is it possible to run llama2-13b on smaller inferentia instances such as inf2.8xlarge ?

**Comment by aws-taylor** [comment]
Hello @VoVAllen,

 Thank you for creating an issue. It's possible to fit LLaMA 13B on inf2.8xl in fp16 mode. However, this instance size will restrict the batch size and sequence-length that you can use for inference. You also may need to either specify a single `context_length_estimate` explicitly or disable it entirely with `context_length_estimate=0` to avoid hitting memory issues.
 
 -Taylor

**Comment by aws-donkrets** [comment]
Hi [VoVAllen](https://github.com/VoVAllen), aws-taylor@ answered your question so closing this ticket. If you have an issue running the llama model please open a new ticket.
