### ISSUE TITLE
[Bug] Model Compilation is incompatible with torch versions 1.12.0 and above for ml-inf1 instances

### ISSUE THREAD

**Issue by DanInacio** [aws-neuron/aws-neuron-sdk#743]
Hi

I have tested the compilation of a PyTorch Model so as to change its architecture into the Neuron architecture.
Within the Python 3.10.10 environment, it seems that model compilation for ml-inf1 instances, only works with torch 1.11.0 or lower.

Any version above that leads to the following error:
`ClientError: InputConfiguration: Unable to load PyTorch model:', 'version_ <= kMaxSupportedFileFormatVersionINTERNAL ASSERT FAILED at "../caffe2/serialize/inline_container.cc":146, please report a bug to PyTorch. Attempted to read a PyTorch file with version 10, but the maximum supported version for reading is 6. Your PyTorch installation may be too old.') For further troubleshooting common failures please visit: https://docs.aws.amazon.com/sagemaker/latest/dg/neo-troubleshooting-compilation.html`

Is the root cause for this related to the fact you cannot use a PyTorch framework version higher than 1.9 when running a compilation job for Neuron?

**Comment by aws-taylor** [comment]
Hello @DanInacio<

 > Is the root cause for this related to the fact you cannot use a PyTorch framework version higher than 1.9 when running a compilation job for Neuron?
 
 Correct. See https://github.com/aws-neuron/aws-neuron-sdk/issues/686 for related discussion. Support for PyTorch 2.0 will be coming in a future release.
 
 -Taylor

**Comment by aws-donkrets** [comment]
Hi [DanInacio](https://github.com/DanInacio), we expect to have PyTorch 2 support in a future release. New releases are announced on our documentation landing page, which you can find here - https://awsdocs-neuron.readthedocs-hosted.com/en/latest/index.html
