### ISSUE TITLE
Loading compiled SDXL model takes long time (10min) on inf2.xlarge

### ISSUE THREAD

**Issue by cshubhamrao** [aws-neuron/aws-neuron-sdk#753]
Steps:
1. Compiled sdxl through [HuggingFace SDXL Inference notebook](https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuronx/inference/hf_pretrained_sdxl_base_and_refiner_1024_inference.ipynb) on a inf2.8xlarge instance.
2. Ran inference and a couple of prompts
3. Copied the compiled model folder onto an inf2.xlarge instance to run just the cells related to inference
   1. the python process is OOMKilled by the kernel if no swap space is present on inf2.xlarge
5. Time it takes after `torch.jit.load()` is executed and all the models to appear on the output of `neuron-top` is 9-10 min

Am I missing something or this is expected?

P.S: is the source of `torch-neuronx` not publicly available?

**Comment by cshubhamrao** [comment]
> Thank you for raising this issue. We do not currently support running SDXL on inf2.xlarge. The OOM you encountered is expected.
> 
Are there additional steps to reproducing the [published benchmarks](https://github.com/aws-neuron/aws-neuron-sdk/blob/master/general/benchmarks/inf2/throughput_data_vision.csv#L18) (indicating inf2.xlarge)?

**Comment by aws-qing** [comment]
Hi,

We're really sorry about the confusion. There is a mistake in the published benchmarks - the instance type for SDXL base and SDXL base+refiner should be inf2.8xlarge, not inf2.xlarge.

Sorry once again for the inconvenience and thanks for letting us know! We will fix this in the upcoming release.

Qing
