### ISSUE TITLE
compile pytorch model failed due to the embedding layer

### ISSUE THREAD

**Issue by khwongbz** [aws-neuron/aws-neuron-sdk#758]
i have built my own model and i am trying to trace the model using pytorch neuron on inf1. Here is one of the member variables of my model:
**self.speaker_emb = nn.Embedding(2, 384)**

and i want to get back the embedding in the one of my function:
**tt = torch.ones((3, )).long()
tt_detached = tt.detach()
spk_emb = self.speaker_emb(tt_detached).unsqueeze(1)*

When i trace the model, i got the following error (part of the error which i believe is the most important part): I believe that the error appeared when i tried to get the embedding:
**File "/opt/aws_neuron_venv_pytorch_inf1/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    return F.embedding(
  File "/opt/aws_neuron_venv_pytorch_inf1/lib/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient**

May i know how to solve the above error?

**Comment by aws-taylor** [comment]
Hello @khwongbz,

 I've forwarded this issue to the appropriate team and we're taking a look. We'll update this ticket once we've got more information.
 
 -Taylor

**Comment by aws-donkrets** [comment]
Hi [khwongbz](https://github.com/khwongbz), First suggestion is see if adding the following code to your model helps:
```
for param in model.parameters():
    param.requires_grad = False
```

**Comment by mrnikwaws** [comment]
Closing this ticket as stale - please re-open and comment if this is still current
