### ISSUE TITLE
neuron-cc stuck to numpy<=1.21.6,>=1.20 and installing cuda-runtime

### ISSUE THREAD

**Issue by fabiozappo** [aws-neuron/aws-neuron-sdk#762]
As this is quite a strict requirement, I was wondering if someone is working to relax this requirement

**Comment by aws-taylor** [comment]
Hello @fabiozappo,

 We are actively working to support newer versions of numpy. We will update this ticket when this support is released.

-Taylor

**Comment by fabiozappo** [comment]
Also removing the installation of the nvidia-cuda-runtimes would be helpfull, as they are basically useless in a machine with no gpu accellerator. 

I am seeing that when running pip install torch-neuron==1.13.1.2.9.1.0 I see a lot of nvidia-cuda. Any way to avoid it?

![image](https://github.com/aws-neuron/aws-neuron-sdk/assets/46443190/1e1e096f-d3a1-45e1-a4f6-b189cb4dc55b)

**Comment by jeffhataws** [comment]
Hi @fabiozappo ,

The CUDA dependencies come in via torch pip wheel. To install CPU-only torch, please add "torch==1.13.0+cpu" to the installation command (ie "pip install torch-neuron==1.13.1.2.9.1.0 torch==1.13.0+cpu").

Numpy version support update will be in an upcoming release.

**Comment by fabiozappo** [comment]
Any update?
