### ISSUE TITLE
Known Issue: Transformers 4.35+ Serialization Issues

### ISSUE THREAD

**Issue by hannanjgaws** [aws-neuron/aws-neuron-sdk#786]
In versions of `transformers>=4.35` `model.save_pretrained` serializes models as `safetensors` instead of `pytorch_model.bin` files by default. This change breaks the `PretrainedModel.from_pretrained` and `save_pretrained_split` methods in `transformers-neuronx`, since they expect a `pytorch_model.bin` file.

This issue can be avoided by using an older `transformers` version:
```
pip install "transformers<4.35.0"
```

This limitation will be addressed in a future Neuron release.

**Comment by ernesttam** [comment]
Yes, I also bumped into this problem.

**Comment by dennj** [comment]
Hello, I made a pull request for a CR to add support for safetensors in `from_pretrained()`.
With this change I am able to use the last version of Huggingface transformers.

https://github.com/aws-neuron/transformers-neuronx/pull/62

**Comment by mrnikwaws** [comment]
Safe tensor loads are now fully supported in transformer_neuronx - closing.  Please re-open if there are further issues
