### ISSUE TITLE
`tensorflow-inference-neuron` is working on `inf1` but failing on `inf2` instances

### ISSUE THREAD

**Issue by debajyoti-truefoundry** [aws-neuron/aws-neuron-sdk#795]
[I am following this tutorial.](https://docs.aws.amazon.com/eks/latest/userguide/inferentia-support.html#deploy-tensorflow-serving-application)

Image:- `763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference-neuron:1.15.4-neuron-py37-ubuntu18.04`
Instance:- `inf2.xlarge`
AMI:- `ami-0199004a63b94a75b`

Logs:-
```
NRTD PID: 7
usage: deep_learning_container.py [-h] --framework {tensorflow,mxnet,pytorch}
                                  --framework-version FRAMEWORK_VERSION
                                  --container-type {training,inference}
deep_learning_container.py: error: the following arguments are required: --framework, --framework-version, --container-type
/usr/local/bin/entrypoint.sh: line 3:     7 Aborted   
```

```
root@eks-neuron-test-8675c677fd-njz28:/# ls /dev/neuron*
/dev/neuron0
root@eks-neuron-test-8675c677fd-njz28:/# cat /tmp/nrtd.log
nrtd[7]: [NRTD:nrtd_main] nrtd build using:1.1.1402.0
sh: 1: lspci: not found
nrtd[7]: [TDRV:reset_mla] Resetting 
neuron-rtd: /opt/workspace/KaenaRuntime/tdrv/tdrv.c:622: tpb_eng_init: Assertion `0' failed.
nrtd[7]: [NRTD:sig_abort_handler] ABORT:
/opt/aws/neuron/bin/neuron-rtd[0x66f912]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7fe761d70980]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7fe760e7afb7]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7fe760e7c921]
/lib/x86_64-linux-gnu/libc.so.6(+0x3048a)[0x7fe760e6c48a]
/lib/x86_64-linux-gnu/libc.so.6(+0x30502)[0x7fe760e6c502]
/opt/aws/neuron/bin/../lib/libtdrv.so(init_phase2_thread+0x6b6)[0x7fe762482296]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7fe761d656db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fe760f5d71f]
root@eks-neuron-test-8675c677fd-njz28:/# 
```

**Comment by jyang-aws** [comment]
@debajyoti-truefoundry, 
for inf2, you need an update on the neuron package: please refer to the setup in https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/tensorflow-neuronx.html#setup-tensorflow-neuronx or pick up the container from https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/tensorflow-neuronx.html#setup-tensorflow-neuronx with tensorflow-neuronx.

**Comment by debajyoti-truefoundry** [comment]
> @debajyoti-truefoundry, for inf2, you need an update on the neuron package: please refer to the setup in https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/tensorflow-neuronx.html#setup-tensorflow-neuronx or pick up the container from https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/tensorflow-neuronx.html#setup-tensorflow-neuronx with tensorflow-neuronx.

I tried with `763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference-neuronx:2.10.1-neuronx-py310-sdk2.14.1-ubuntu20.04` image, but it does not implement downloading model from S3.

```
FileSystemStoragePathSource encountered a filesystem access error: Could not find base path s3://tfy-wadhwani-orf-euwe1/resnet50_inf1 for servable resnet50_inf1 with error UNIMPLEMENTED: File system scheme 's3' not implemented (file: 's3://redacted/resnet50_inf1')
```

Do you have an image that implements it?

**Comment by mrnikwaws** [comment]
Hi @debajyoti-truefoundry,

We cannot guarantee that inf1 tutorials will work for inf2. However upon investigation it seems your issue may be related to tensorflow-2 itself (not neuron). Please see this ticket https://github.com/tensorflow/tensorflow/issues/51583. The suggested solution is to use tfio like so:

```
import tensorflow as tf
import tensorflow_io as tfio

v = tf.io.read_file('s3://1234567')
```

Please reopen this ticket if you still have issue - but I will assume this helps.
