### ISSUE TITLE
What is the best practice to scale?

### ISSUE THREAD

**Issue by mostafafarzaneh** [aws-neuron/aws-neuron-sdk#797]
Currently, we are using Elastic Inference for inferencing on AWS ECS. We use `inference_accelerators` in ecs.Ec2TaskDefinition to set up elastic inference. For scaling, we are monitoring `AcceleratorUtilization` metric to decide when to scale out or scale in.

Now that AWS recommends switching to AWS Inf instances, we plan to migrate from EI to Inf. We plan to use it in AWS ECS. How should we monitor Inf usage and scale our instances based on that? Is there any pre-defined metrics for this usage?

**Comment by aws-maens** [comment]
You can use [Neuron Monitor](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/tools/neuron-sys-tools/neuron-monitor-user-guide.html) , it should support [CloudWatch](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/tools/neuron-sys-tools/neuron-monitor-user-guide.html#neuron-monitor-cloudwatchpy).

**Comment by mostafafarzaneh** [comment]
Thanks @aws-maens 
Would SageMaker provide autoscaling for Inferentia out of the box? or do I need to produce the required metrics and alarms for scaling by myself?

**Comment by mrnikwaws** [comment]
You need to select a metric for SageMaker autoscaling: https://docs.aws.amazon.com/sagemaker/latest/dg/endpoint-auto-scaling-add-code-define.html.  There are some predefined metrics, or you can choose your own.  

General information is here: https://docs.aws.amazon.com/sagemaker/latest/dg/endpoint-auto-scaling.html

**Comment by mostafafarzaneh** [comment]
Thanks @mrnikwaws 
Is there any predefined metric for Inferentia? or do you know any documentation or blog about autoscaling with Inferentia?

I could not find a straightforward path to do Inferentia autoscaling. I was thinking of creating a lambda function that captures and averages all Inferentia instances, then using this as a new metric and use it to do autoscaling.

**Comment by mrnikwaws** [comment]
The predefined metrics are listed here for SageMaker: https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PredefinedMetricSpecification.html.  None are Neuron specific.

**Comment by shubhamkalra27** [comment]
> I could not find a straightforward path to do Inferentia autoscaling. I was thinking of creating a lambda function that captures and averages all Inferentia instances, then using this as a new metric and use it to do autoscaling.

Did this approach work for you? @mostafafarzaneh  or did you also look at Neuron Monitor cloudwatch linked above? which option worked for you?

**Comment by aws-taylor** [comment]
Hello @mostafafarzaneh,

 We haven't heard from you in a while, so I'm going to close this issue. Feel free to re-open if you have any further questions.
