### ISSUE TITLE
Issue on page /containers/tutorials/tutorial-oci-hook.html

### ISSUE THREAD

**Issue by jingli-wtbox** [aws-neuron/aws-neuron-sdk#799]
restart service `**containerd**` should be 

`sudo systemctl restart containerd`

instead of 

`sudo systemcl restart containerd`

**Comment by hannanjgaws** [comment]
Thanks for pointing out this mistake! We will fix this issue in our documentation or feel free to send a PR to fix it if you want to contribute.

**Comment by mrnikwaws** [comment]
Fixed
