### ISSUE TITLE
Missing ami image: Neuron 2.16 - Deep Learning AMI Neuron PyTorch 

### ISSUE THREAD

**Issue by michaelfeil** [aws-neuron/aws-neuron-sdk#812]
My goal is to run:
https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuronx/transformers-neuronx/inference/llama-70b-sampling.ipynb

I would like to use the ami image, for several reasons, e.g. reproducability. Despite the release of 2.16 a few weeks ago, I can't find a `ami-image` with 2.16, which I assume is needed for llama-70B.

```bash
aws ec2 describe-images --region us-west-2 --owners amazon --filters 'Name=name,Values=Deep Learning AMI Neuron PyTorch *' 'Name=state,Values=available' --query 'reverse(sort_by(Images, &CreationDate))'
```
Latest one: Neuron 2.15.9
```
region: us-west-2 
image_id: ami-0a1063844e84bee6a
```

**Comment by aws-mesharma** [comment]
Hi, You have found the right ami-id, that is,
ami-0a1063844e84bee6a
I checked that it has the 2.16 Neuron software installed
example
$ yum list installed | grep neuron
aws-neuronx-collectives.x86_64        2.19.7.0_530fb3064-1           @neuron    
aws-neuronx-dkms.noarch               2.15.9.0-dkms                  @neuron    
aws-neuronx-oci-hook.x86_64           2.2.45.0-1                     @neuron    
aws-neuronx-runtime-lib.x86_64        2.19.5.0_97e2d271b-1           @neuron    
aws-neuronx-tools.x86_64              2.16.1.0-1                     @neuron   
which are also mentioned here https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#trn1-packages
2.15.9 is the neuron driver (dkms) version in the 2.16 Neuron release

You can run the tutorial using this image-id.
If you require any further information, feel free to contact us. Thanks.

**Comment by bryantbiggs** [comment]
@aws-mesharma is there somewhere public that references what component versions are provided in a given Neuron release?

**Comment by aws-mesharma** [comment]
Yes, you can refer to our readthedocs website to find released versions of Neuron packages for any 
For latest release - https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#trn1-packages
You can go to previous releases by using tags like 2.16.0 here: https://awsdocs-neuron.readthedocs-hosted.com/en/v1.16.0/release-notes/index.html

**Comment by michaelfeil** [comment]
@aws-mesharma Thanks for the reply: I was looking forward to the new release of e.g. this: https://aws.amazon.com/marketplace/pp/prodview-gr3e6yiscria2 / Huggingface AMI Image
