### ISSUE TITLE
Does AWS Neuron supports GPT2LMHeadModel from Hugging Face (pytorch) ?

### ISSUE THREAD

**Issue by echatzikyriakidis** [aws-neuron/aws-neuron-sdk#828]
Hi everyone,

Does anyone knows if AWS Neuron supports GPT2LMHeadModel from Hugging Face (pytorch).

I am wondering if I can use it to train an LLM and use to for generation on Inferentia1/2 and Trainium1/2 instances?

Thanks!

**Comment by hannanjgaws** [comment]
Yes, you can train and run generative inference with GPT2 models on Neuron.

To get started with training, you can take at the following documentation:
- (Nemo) https://github.com/aws-neuron/aws-neuron-parallelcluster-samples/blob/master/examples/jobs/neuronx-nemo-megatron-gpt-job.md
- (ZeRO-1 + Neuronx-Distributed) https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/neuronx-distributed/tutorials/training-gpt-neox-20b.html
These examples can be modified for GPT2-style models.

For inference you can use `transformers-neuronx`, which is our optimized generative LLM inference library:
- General documentation: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/transformers-neuronx/index.html
- This Llama-13b inference example that can be updated for GPT2 by using the `GPT2ForSamplingWithContextBroadcasting` class: https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuronx/transformers-neuronx/inference/meta-llama-2-13b-sampling.ipynb

**Comment by echatzikyriakidis** [comment]
Thank you @hannanjgaws!
