### ISSUE TITLE
Trying to trace a model via torch_neuronx but getting issue: RuntimeError: The following operation failed in the TorchScript interpreter

### ISSUE THREAD

**Issue by ramsum56** [aws-neuron/aws-neuron-sdk#835]
I am trying to turn a Bert Model into a neuron traced model but I am seeing this issue on the line I am trying to execute the model. Further down I am also seeing an issue: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged. When running : lsmod | grep neuron
I see output: neuron                253952  0

**Comment by aws-donkrets** [comment]
Hi [ramsum56](https://github.com/ramsum56), Sorry you are having an issue. Can you provide the exact error or post a log file? Also, would be helpful to know what SDK version you are running. The output of the following commands would be helpful:

# (Copy/paste output from these commands):
            $ yum list installed | grep neuron    ## on AL2
            $ apt list | grep neuron | grep installed   ## on Ubuntu
            $ pip3 list | grep neuron   ## both AL2 and Ubuntu
            $ cat /sys/devices/virtual/dmi/id/product_name    ## both AL2 and Ubuntu

**Comment by mrnikwaws** [comment]
Hi @ramsum56 - closing since we have not heard back from you in two weeks.  Please re-open or create another ticket with the requested in if you are still seeing issues
