### ISSUE TITLE
Issue(non-blocking): PIP compile install defaults to older versions of neuron-cc

### ISSUE THREAD

**Issue by jhazenaai** [aws-neuron/aws-neuron-sdk#837]
# Issue

When running a PIP compile install of `neuron-cc=2.*` within the requirements.in file with `pip-compile` the default version installed is 2.3.0. This install sets the flag `--extra-index-url=https://pip.repos.neuron.amazonaws.com/`. 

## Details

Requirements 

`
...

neuronx-cc==2.*
`

Command

`pip-compile requirements.in --extra-index-url=https://pip.repos.neuron.amazonaws.com/`

# Workaround

This can be easily worked around by setting a more specific version for example `neuronx-cc==2.12.68.0+4480452af`

**Comment by aws-donkrets** [comment]
Hi [jhazenaai](https://github.com/jhazenaai), thx for reporting this issue. One reason we make the neuronx-cc setting so general is so we don't need to update the setting for each release, which happens approx every 4-6 weeks. We'll see if there is a way to avoid having the earlier (2.3.0) version selected while also not defining the version number so specific that it needs updating so often.

**Comment by aws-taylor** [comment]
Hi @jhazenaai,

 We haven't heard from you in a while, so I'm going to go ahead and resolve this. One other potential explanation for what you're seeing is that the dependencies that you have listed in `requirements.in` are such that 2.3.0 is the only version that is mutually compatible with your other dependencies. I would need to see the logs from pip to say for certain; feel free to attach these and re-open and we can take a look.
