### ISSUE TITLE
issue(blocking): neuron requires protobuf <3.20 

### ISSUE THREAD

**Issue by jhazenaai** [aws-neuron/aws-neuron-sdk#840]
# Issue

Currently we use a monorepo with a shared dependency tree for our interconnected services. We use `pip-compile` to manage our dependencies for install and we require a modern version of protobuf `protobuf~=4.25.1`. This conflicts with neuron which requires protobuf `<3.20`. This fails our dependency checks, thus preventing the integration of neuron/inferentia into code base. 

# Investigations

I am currently investigating workarounds within the context of our system and policies, but I have not found a viable alternative at this point that meets the minimum standards of code quality.

**Comment by jeffhataws** [comment]
@jhazenaai thanks for reporting the issue. We will work on this.

**Comment by jyang-aws** [comment]
@jhazenaai

We have upgraded the maximum protobuf for some of our packages following the 2.20 neuron release. Please refer to this table: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#supported-probuf-versions
