### ISSUE TITLE
Need to use swap memory for loading (sdxl turbo) model, But I can't set it in sagemaker

### ISSUE THREAD

**Issue by Suprhimp** [aws-neuron/aws-neuron-sdk#858]
Hi, I found that I can't load my model to sagemaker because inside the docker, my model cause OOM while loading in side the sagemaker deploy docker.

I checked that with My EC2 instance inf2.xlarge works well in this environement. (logged with `free -m`)

this environment the works very well with sdxl turbo
![스크린샷 2024-04-03 오전 2 04 45](https://github.com/aws-neuron/aws-neuron-sdk/assets/73486185/0bb92850-11b1-458c-a408-b7c7e2e577ee)

this environment gives me OOM error.
![스크린샷 2024-04-03 오전 2 15 26](https://github.com/aws-neuron/aws-neuron-sdk/assets/73486185/cae22b02-de7f-4499-9dba-5cfeab1c3514)

Is there any setting that I can use swap memory? especially I want to know How can I allocate swap memory (sagemaker docker env can't use `--privilege`flag).

**Comment by jeffhataws** [comment]
Hi @Suprhimp, will you help provide more information:
- Version of docker image
- Are you using SageMaker Notebooks or SageMaker Studio?

**Comment by Suprhimp** [comment]
https://github.com/aws/deep-learning-containers/blob/master/huggingface/pytorch/inference/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx


I used this docker image for sagemaker endpoint

I finally give up to use sdxl with neuronx in sagemaker environment 😂

But I build my backend with ec2.

**Comment by aws-taylor** [comment]
Hello @Suprhimp,

 Since this appears to be an issue with SageMaker itself, I suggest you reach out to https://repost.aws/tags/questions/TAT80swPyVRPKPcA0rsJYPuA?view=all.
