### ISSUE TITLE
support for aten::upsample_nearest3d

### ISSUE THREAD

**Issue by SimonRelu** [aws-neuron/aws-neuron-sdk#908]
We're looking into using Inf1 instances on AWS to run our GPU workloads. I was wondering if there are any plans on supporting the `aten::upsample_nearest3d` (torch) layer since this is the only one that we use that's currently not yet supported. 

Another question I had if there are any plans on supporting python 3.11 (and publishing wheels for it) since we recently made the switch.

Thank you for looking into this

**Comment by AWSGH** [comment]
3.11 is coming in a future release. For the model support, general guidance is to try with Inf2 in case the Neuron support for Inf1 is lacking an operator. Will you be able to test this specific model with Inf2?

**Comment by aws-taylor** [comment]
Hello @SimonRelu,

 We haven't heard from you in a while, so I'm going to resolve this. If you are able to test with inf2 and still have some problems don't hesitate to re-open this issue.
