### ISSUE TITLE
Issue on page /frameworks/torch/torch-neuronx/programming-guide/training/pytorch-neuron-programming-guide.html

### ISSUE THREAD

**Issue by yahavb** [aws-neuron/aws-neuron-sdk#912]
The note under [Automatic Mixed-Precision](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/programming-guide/training/pytorch-neuron-programming-guide.html#id11) misleads. It gives the impression that convolution on Neuron is sub-optimal. Can we pls remove it? Specifically, the note is "(NOTE: Although convolution is in the list below, it is currently unsupported by Neuron. See model-architecture-fit)"

**Comment by jeffhataws** [comment]
This is fixed in the latest doc. Thanks.
