### ISSUE TITLE
AWS NeuronX sdk installation

### ISSUE THREAD

**Issue by Zkarape** [aws-neuron/aws-neuron-sdk#916]
Hello, I am struggling with this error while installing neuronx both locally and on a SageMaker notebook instance on ml.m5.xlarge instance. Guide me please how to install correctly to compile my model to deploy on inf2 instance. If you need more info, let me know.

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/tensorflow_neuronx/__init__.py:1
----> 1 raise ImportError("WRONG PACKAGE. Please install the package from Neuron Repository - [pip.repos.neuron.amazonaws.com](http://pip.repos.neuron.amazonaws.com/)")

ImportError: WRONG PACKAGE. Please install the package from Neuron Repository - [pip.repos.neuron.amazonaws.com](http://pip.repos.neuron.amazonaws.com/)

I will highly appreciate any help and guidance.

**Comment by jyang-aws** [comment]
Hi Zkarape, 
could you follow these steps https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/neuron-setup/pytorch/neuronx/ubuntu/torch-neuronx-ubuntu20.html#setup-torch-neuronx-ubuntu20 based on your OS?
Please make sure to include 
`python -m pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com/`
Let us know if you still see any issues on the setup.

**Comment by Zkarape** [comment]
Thanks a lot for reaching out. Sure, I will try and let you know.

Regards,
Zhenya.

**Comment by jeffhataws** [comment]
@Zkarape let us know if you have further issues. Thanks.

**Comment by Zkarape** [comment]
Thanks again for reaching out, as I changed my direction I decided to stop trying for now. But I have tried to run this notebook (https://github.com/aws-neuron/aws-neuron-sagemaker-samples/blob/master/inference/inf2-bert-on-sagemaker/inf2_bert_sagemaker.ipynb)  step-by-step and the first run worked, but the second time when I rerun the same commands, on this command I have the same issue

%pip install --upgrade neuronx-cc==2.* torch-neuronx
