### ISSUE TITLE
Issue on page /general/appnotes/neuronx-cc/neuronx-cc-training-mixed-precision.html

### ISSUE THREAD

**Issue by yahavb** [aws-neuron/aws-neuron-sdk#920]
The [link](https://github.com/aws/aws-neuron-sdk/issues/36) referenced in the page referred to `inf1` and not relavant to the `inf2/trn1.trn1n` case which is the page.

**Comment by AWSGH** [comment]
Thanks @yahavb for the proposal. We are working on updating this roadmap project soon, stay tuned!
