### ISSUE TITLE
[Runtime API] Missing `nrt_get_dmabuf_fd` Function

### ISSUE THREAD

**Issue by JigaoLuo** [aws-neuron/aws-neuron-sdk#923]
Hi Runtime Team,

I noticed that in a previous Runtime API release, there was a function called `nrt_get_dmabuf_fd`. However, I can no longer find it in the current Runtime headers. Could you provide information about existence of this function, and its previous role in exporting DMA-buffers for allocated tensor addresses?

Thank you!

**Comment by awsilya** [comment]
@JigaoLuo which RT version are you running?  The function is still there as far as I can tell

```
ubuntu@ip-172-31-8-1:~$ grep nrt_get_dmabuf_fd /opt/aws/neuron/include/nrt/*
grep: /opt/aws/neuron/include/nrt/nds: Is a directory
/opt/aws/neuron/include/nrt/nrt.h:NRT_STATUS nrt_get_dmabuf_fd(uint64_t va, uint64_t size, int* fd);
ubuntu@ip-172-31-8-1:~$ 
```
Just curious, what are you using it for?

**Comment by JigaoLuo** [comment]
Hi,
for example this function is not in here: https://github.com/aws-neuron/aws-neuron-sdk/blob/master/src/libnrt/include/nrt/nrt.h

**Comment by JigaoLuo** [comment]
Thanks.

A side question on runtime function: is a memory copy from Neuron to host memory supported?
