### ISSUE TITLE
[Runtime API] Questions Regarding `memcpy` Between Devices & Between Host and Device

### ISSUE THREAD

**Issue by JigaoLuo** [aws-neuron/aws-neuron-sdk#931]
Hello Runtime Team,

I have mainly two questions regarding memory copying between the host and device using the Neuron SDK:
- Standard Interface for memcpy Between Host and 
  - Host to Device: I have identified two functions for copying memory from host to device: `nrt_memcpy_to_device` and `nrt_tensor_write`. Could you clarify **the standard interface or recommended function** for this operation? Are there specific use cases that determine which function should be used?
  - Device to Host: For copying memory from device to host, it seems that `nrt_tensor_read` is the only available option. 

- Achieving Optimal Performance for memcpy Operations:
  - I have conducted simple benchmarks comparing the performance of `nrt_memcpy_to_device` and `nrt_tensor_write` for host-to-device transfers. Surprisingly, `nrt_tensor_write` performed faster than `nrt_memcpy_to_device` in simple cases. **Is there any guidance or setup that can help achieve better performance for memcpy operations in general?**
  - An additional comment, I noticed that the libfabric library utilizes `nrt_memcpy_to_device` rather than `nrt_tensor_write`. Despite this, my tests show that `nrt_tensor_write` provides better performance. For reference, you can review the relevant code in libfabric here: [libfabric hmem_neuron.c](https://github.com/ofiwg/libfabric/blob/main/src/hmem_neuron.c). I also wonder why this function is preferred instead of the tensor one. 
  
Thank you for your assistance.

**Comment by shebbur-aws** [comment]
Hi [JigaoLuo](https://github.com/JigaoLuo),
nrt_tensor_write() - uses runtime's dedicated Host<->Device DMA to transfer data, which is good for large transfers
nrt_memcpy_to_device() - uses memcpy() to move data between the Host and Device, which is good for small transfers < 1K.
Hope this helps.

**Comment by JigaoLuo** [comment]
Hi @shebbur-aws,
thanks for the answer. Is that true that`nrt_memcpy_to_device` does not use Device DMA?

**Comment by JigaoLuo** [comment]
I would close this issue because I found the function `nrt_tensor_copy` in Runtime API and also asked at #936
