### ISSUE TITLE
[Runtime API] Benchmarking Device Memory Bandwidth with `nrt_tensor_copy`

### ISSUE THREAD

**Issue by JigaoLuo** [aws-neuron/aws-neuron-sdk#936]
Hi Runtime Team,

I wanted to benchmark the device memory bandwidth of a NeuronDevice. To do this, I used the `Trn1.2xlarge` instance, which has a single NeuronDevice, and focused on measuring its on-chip device memory performance. From the documentation, I couldn't find many useful APIs for this purpose. I tested `nrt_tensor_write` and `nrt_memcpy_to_device`, but both resulted in very low memcpy bandwidth.

Then I skimmed through the headers in `/opt/aws/neuron/include/nrt/` and `/opt/aws/neuron/lib/` and found the function `nrt_tensor_copy`, which can copy device memory within a single NeuronCore. I benchmarked it and achieved around **24 GiB/s** for large memory copies. However, this performance is still far from the documented device memory bandwidth of **820 GiB/s**.

Is there a way to achieve this bandwidth number via the Runtime API? Or is the 24 GB/s I obtained expected? Any insights would be appreciated.

(I understand that the Runtime API involves synchronous function calls issued from the host, which may introduce some measurement overhead. However, the discrepancy in the performance numbers seems too large to be explained by this alone.)

**Comment by aws-canepa** [comment]
So the short answer is none of the APIs you are using are designed to exercise internal memory bandwidth.  They are host based apis designed to move data between the host and device.  The performance you'e seeing is gated by host interaction.

**Comment by JigaoLuo** [comment]
Thanks for the answer. It make sense to me now :)

**Comment by aws-canepa** [comment]
No problem.  Glad to see people experimenting with the APIs :-)
