### ISSUE TITLE
Bug Report: Incorrect Tensor Indexing & `torch.index_select` on PyTorch NeuronX with `torch.int64`

### ISSUE THREAD

**Issue by JigaoLuo** [aws-neuron/aws-neuron-sdk#937]
Environment:
- Instance Type: trn1.2xlarge
- OS: al2023-ami-2023.5.20240722.0-kernel-6.1-x86_64
- PyTorch Version & More: directly setup from https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/neuron-setup/pytorch/neuronx/amazon-linux/torch-neuronx-al2023.html#setup-torch-neuronx-al2023

---
# Issue

Issue: Tensor indexing results in PyTorch on NeuronX are incorrect compared to common logic.

Not sure if this is a known issue or documented. I wonder if the issue on AWS Neuron might be due to an unsupported ATen operation, leading to the unexpected behavior. Hope to get an answer. Thanks :)

## Wrong results from Neuron

```python
import torch
import torch_xla
import torch_xla.core.xla_model as xm

device = xm.xla_device()
tensor = torch.tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], device=device)
index  = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device=device)
print(tensor[index])
```

The print result is `tensor([5, 0, 5, 0, 5, 0, 5, 0, 5, 0], device='xla:0')` . This result is stable and deterministic at my case, also able to reproduce at new Instance (I did only with trn1.2xlarge so far).

### Compiling Log
```
2024-07-29 08:41:44.000199:  33611  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-07-29 08:41:44.000200:  33611  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ec2-user/neuroncc_compile_workdir/57f12c59-60fd-4fa5-abb5-792181d2b354/model.MODULE_9051130542346537621+d41d8cd9.hlo_module.pb --output /tmp/ec2-user/neuroncc_compile_workdir/57f12c59-60fd-4fa5-abb5-792181d2b354/model.MODULE_9051130542346537621+d41d8cd9.neff --verbose=35
.
Compiler status PASS
```

## Correct results from CPU

```python
import torch
import torch_xla
import torch_xla.core.xla_model as xm

device = torch.device("cpu")
tensor = torch.tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], device=device)
index  = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device=device)
print(tensor[index])
```

The result is correct: `tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])`

**Comment by JigaoLuo** [comment]
Note: I reran the code on Google Colab using TPUv2 to perform a sanity check. The results on Google TPUv2 were correct, and I have pasted them here for reference.

```python
# !!!on Google Colab using TPUv2!!!
import torch
import torch_xla
import torch_xla.core.xla_model as xm

print("[GOOGLE COLAB] PyTorch version:", torch.__version__)
print("[GOOGLE COLAB] torch_xla version:", torch_xla.__version__)
print("[GOOGLE COLAB] TPU devices:", xm.get_xla_supported_devices())

device = xm.xla_device()
print("[GOOGLE COLAB] TPU Default device:", device)
tensor = torch.tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], device=device)
index  = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device=device)
print(tensor[index])
```

**Comment by JigaoLuo** [comment]
Thank you for getting back to me. I couldn't find any previous issues related to this bug. 

I'm also interested in finding a **workaround** to ensure this advanced indexing feature works correctly, as it does on CPU and Google TPU. My current code relies on these operations, and I would like to run it on AWS Neuron as well. :)

**Comment by JigaoLuo** [comment]
> Thanks for reporting the issue. We are looking into it and will get back shortly

Hi @shebbur-aws,
I am seeking for alternatives and tried with `torch.index_select` which also leads to the same wrong result: 
```python
import torch
import torch_xla
import torch_xla.core.xla_model as xm

device = xm.xla_device()
tensor = torch.tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], device=device)
index  = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device=device)
print(tensor[index])
another_result = torch.index_select(tensor, 0, index)
print(another_result)
``` 
with output
```
tensor([ 5,  0, -1, -1,  5,  0,  2,  0,  5,  0,  0,  0], device='xla:0')
tensor([ 5,  0, -1, -1,  5,  0,  2,  0,  5,  0,  0,  0], device='xla:0')
```

I think your would do the same thing to check if `torch.index_select` is working, so I also report with update

**Comment by shebbur-aws** [comment]
We found the issue you are running into is due to lack of int64 support natively in our compiler. Please see this in our documentation as a known issue - https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/compiler/neuronx-cc/index.html?highlight=int64#known-issues

While we are working towards providing a better user actionable message in the log, suggest you trying this as a workaround to unblock.

import torch
import torch_xla
import torch_xla.core.xla_model as xm

device = xm.xla_device()
tensor = torch.tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=torch.int32, device=device)
index  = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device=device)
print(tensor[index])

**Comment by JigaoLuo** [comment]
@shebbur-aws It makes sense to me. Thanks :)
I will close this issue
