### ISSUE TITLE
Trying to get the NEFF file when using the tensorflow neuronx trace API

### ISSUE THREAD

**Issue by kandakji** [aws-neuron/aws-neuron-sdk#943]
I need to run neuron profiler with my model. How can I get the NEFF file when using tensorflow neuronx trace API?

```
import os


for batch_size in range(1,2):
    image = tf.zeros([batch_size,512, 512, 3], tf.float32)
    os.environ["NEURON_CC_FLAGS"] = "--target inf2 --auto-cast none --optlevel 2 --output home/ubuntu/environment/tf_noteboks/file.neff"
    model_neuron = tfnx.trace(
        model,
        example_inputs = image
    )
    
    model_dir = './models_neuron_b{}'.format(batch_size)
    model_neuron.save(model_dir)
```

When removing the output flag, the compilation runs successfully, when I add the output flag, I get the following error

```
.WARNING:tensorflow:neuron-cc failed with:
2024-08-09T13:57:35Z [F139] neuronx-cc terminated abnormally - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new

WARNING:tensorflow:Warning: Your traced model has 0% of operators compiled to neuron.
INFO:tensorflow:Assets written to: ./models_neuron_b1/assets
```

**Comment by EmilyWebber** [comment]
Have you tried this?

NEURON_CC_FLAGS='--workdir ./artifacts' 

From the docs here: 
- https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/tensorflow/tensorflow-neuronx/tfneuronx-python-tracing-api.html 

I'd also suggest moving the flags to the top of the script, outside of the for-loop.
