### ISSUE TITLE
Number of instructions (8658944) is over the threshold (5000000)

### ISSUE THREAD

**Issue by hasadata** [aws-neuron/aws-neuron-sdk#987]
I am trying to trace a super resolution model using the following input torch.randn(1, 3, 512, 512) 

how can I avoid the threshold and reduce the memory footprint ? 

[XTP002] Number of instructions (8658944) is over the threshold (5000000). Tiling could potentially do a better job. - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.

i tried setting optlevel=1 getting same results

**Comment by jyang-aws** [comment]
@hasadata could you elaborate more on the model size and structure?

**Comment by hasadata** [comment]
The model is based on the ESRGAN architecture, it has around 16 million parameters

**Comment by hasadata** [comment]
running tracing on inf2 instance with latest sdk I get this error 
ValueError: Message torch_neuronx.pyhlo.HloModuleProto exceeds maximum protobuf size of 2GB: 2416960823

**Comment by jyang-aws** [comment]
This is usually triggered by large literal value in the HLO. 
Could you share what's the sequence length and batch size used in this case?

**Comment by hasadata** [comment]
this is the code I am using 
model = Swin2SRForImageSuperResolution.from_pretrained("caidas/swin2SR-classical-sr-x2-64")
example_input = torch.randn(1, 3, 256, 256) 
model_neuron = torch_neuronx.trace(model,example_input )
****

**Comment by aws-rhsoln** [comment]
With 2.20 release, I was able to run this example:
```
import torch
import torch_neuronx
from transformers import Swin2SRForImageSuperResolution


model = Swin2SRForImageSuperResolution.from_pretrained("caidas/swin2SR-classical-sr-x2-64")
example_input = torch.randn(1, 3, 256, 256)
model_neuron = torch_neuronx.trace(model,example_input )
print(model_neuron)
```

I had to run this code:
```
XLA_DISABLE_FUNCTIONALIZATION=0 python trace.py 
```

Can you try to upgrade torch-neuronx and compiler with the latest release.

**Comment by hasadata** [comment]
i tried using XLA_DISABLE_FUNCTIONALIZATION=0 but results were altered 
i had to split the model than trace
